import {test,expect,type Page} from '@playwright/test';
import {copy} from '../src/core/content.js';
import {start,target,go,settled,saved,workstation,putTile,premiere,collectKit,media,stage} from './helpers.js';
const button=(p:Page,id:string)=>p.getByRole('button',{name:copy(id),exact:true});
async function reduced(page:Page,large=false){await button(page,'CT.UI.MENU').click();await button(page,'CT.UI.SETTINGS').click();await page.getByLabel('Motion',{exact:true}).selectOption('reduced');await page.getByLabel('Sound',{exact:true}).selectOption('off');if(large){await page.getByLabel('Text size',{exact:true}).selectOption('largest');await page.getByLabel('Text spacing',{exact:true}).selectOption('roomier');}await page.keyboard.press('Escape');await page.keyboard.press('Escape');}
for(const size of [{width:320,height:568},{width:640,height:360}])test(`FIX11.ACCESS/UNMET ${size.width}x${size.height} whole unmet story, note inspection and native revision`,async({page})=>{
 await page.setViewportSize(size);await workstation(page);await reduced(page,true);await target(page,'ST.RAIL');await settled(page);for(const [tile,after]of [['FERRY',undefined],['PLANT','One Boat'],['BLOOM','Hill']] as const)await putTile(page,tile,after);await button(page,'CT.WORK.REHEARSE').click();await expect(page.getByRole('button',{name:'Continue rehearsal',exact:true})).toBeVisible();
 expect((await saved(page)).payload.playback?.puppet).toEqual({pip:'left',seed:'right',boats:'separate',lit:false});await page.getByRole('button',{name:'Watch rehearsal',exact:true}).click();const canvas=page.getByTestId('whole-story');await canvas.scrollIntoViewIfNeeded();const box=await canvas.boundingBox(),world=await page.locator('[data-world]').boundingBox();expect(box!.y).toBeGreaterThanOrEqual(world!.y+world!.height-1);expect(box!.y+box!.height).toBeLessThanOrEqual(size.height+1);await page.screenshot({path:`output/playwright/compact-${size.width}-unmet.png`,fullPage:false});
 await button(page,'CT.RAIL.ARRANGE_MODE').click();for(const id of ['CT.KIT.NOTE_JO','CT.KIT.NOTE_REMY']){await button(page,id).click();await settled(page);await page.locator('.reader .source-words').first().scrollIntoViewIfNeeded();await page.locator('.task-close button').click();await expect(button(page,id)).toBeFocused();}
 await button(page,'CT.STORY.OPEN').click();await expect(page.getByTestId('whole-story')).toHaveAttribute('aria-label',/Pip/);await page.locator('.task-close button').click();await target(page,'ST.RAIL');await settled(page);await page.getByRole('button',{name:'Continue rehearsal',exact:true}).click();await expect(page.getByRole('button',{name:'Continue to finish rehearsal',exact:true})).toBeVisible();await page.getByRole('button',{name:'Continue to finish rehearsal',exact:true}).click();await putTile(page,'BRIDGE','One Boat');const state=await premiere(page);expect(state.payload.premiere?.order).toEqual(['TILE.FERRY','TILE.BRIDGE','TILE.PLANT','TILE.BLOOM']);
});
test('FIX11.NPC reading is not delivery; one scope passage differs from both cancellation passages',async({page})=>{
 await start(page);await reduced(page);await go(page,'ST.EXIT.CY','Courtyard');await target(page,'CY.SOURCE.E3');await settled(page);await button(page,'CT.OBJ.NOTICE_FLATTEN').click();await settled(page);await page.locator('[data-content-id="CT.SRC.E3"]').scrollIntoViewIfNeeded();expect((await saved(page)).payload.npcReceived).toEqual([]);await target(page,'ACT.REMY');await settled(page);await button(page,'CT.TALK.CANCELED').click();await expect(page.getByText(copy('CT.REMY.CORRECT'),{exact:true})).toHaveCount(0);
 await button(page,'CT.PRESENT.OPEN').click();await page.locator('[data-ref="E3.a"]').check();await page.getByRole('button',{name:'Show Remy',exact:true}).click();await settled(page);await expect(page.getByText(copy('CT.NPC.SCOPE'),{exact:true})).toBeVisible();expect((await saved(page)).payload.npcReceived[0]?.refs).toEqual(['E3.a']);
 await button(page,'CT.PRESENT.OPEN').click();await page.locator('[data-ref="E3.a"]').check();await page.locator('[data-ref="E3.b"]').check();await page.getByRole('button',{name:'Show Remy',exact:true}).click();await settled(page);await expect(page.getByText(copy('CT.REMY.CORRECT'),{exact:true})).toBeVisible();expect((await saved(page)).payload.npcReceived[0]?.deliveryRecordIds).toHaveLength(2);
});
test('FIX11.ART_FAILURE all Canvas contexts denied still supports a complete native rehearsal and premiere',async({page})=>{
 await page.addInitScript(()=>{HTMLCanvasElement.prototype.getContext=(()=>null) as typeof HTMLCanvasElement.prototype.getContext;});await workstation(page);await reduced(page);await target(page,'ST.RAIL');await settled(page);for(const [tile,after]of [['BRIDGE',undefined],['PLANT','Joined Boats'],['BLOOM','Hill']] as const)await putTile(page,tile,after);await button(page,'CT.STORY.OPEN').click();await expect(page.getByTestId('whole-story')).toHaveAttribute('aria-label',/Pip/);await page.locator('.task-close button').click();await target(page,'ST.RAIL');await settled(page);expect((await premiere(page)).payload.premiere).not.toBeNull();
});
test('FIX11.RECAP fresh voluntary revision, post-outcome text, hint-then-trial and uncertain reload stay distinct',async({page})=>{
 test.setTimeout(180000);await start(page);await reduced(page);await button(page,'CT.UI.GOAL').click();await button(page,'CT.PLAN.SEARCH').click();await page.getByRole('textbox').fill('I think the whole premiere is canceled.');await button(page,'CT.PLAN.RECORD').click();await go(page,'ST.EXIT.CY','Courtyard');await target(page,'CY.SOURCE.E3');await settled(page);await button(page,'CT.OBJ.NOTICE_FLATTEN').click();await settled(page);await page.locator('[data-content-id="CT.SRC.E3"]').scrollIntoViewIfNeeded();await button(page,'CT.UI.GOAL').click();await button(page,'CT.PLAN.SEARCH').click();await page.getByRole('textbox').fill('Only the outdoor rehearsal is canceled. I can still get our premiere ready.');await button(page,'CT.PLAN.RECORD').click();
 await go(page,'CY.EXIT.WK','Workshop');await go(page,'WK.EXIT.MD','Media');await collectKit(page);await target(page,'ACT.LOOP');await settled(page);await stage(page);await target(page,'ST.DOCK');await settled(page);await target(page,'ST.RACK.BAY');await settled(page);for(const [tile,after]of [['BRIDGE',undefined],['PLANT','Joined Boats'],['BLOOM','Hill']] as const)await putTile(page,tile,after);await premiere(page);await button(page,'CT.ENDING.REOPEN').click();await expect(page.getByRole('heading',{name:copy('CT.RECAP.PLAN'),exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:copy('CT.RECAP.CHANGED'),exact:true})).toBeVisible();
 await button(page,'CT.UI.GOAL').click();await button(page,'CT.PLAN.SEARCH').click();await page.getByRole('textbox').fill('The seed and Pip planted together.');await button(page,'CT.PLAN.RECORD').click();await button(page,'CT.UI.GOAL').click();await button(page,'CT.ENDING.REOPEN').click();await expect(page.getByRole('heading',{name:copy('CT.RECAP.AFTER_RUN'),exact:true})).toBeVisible();
 await target(page,'ST.RAIL');await settled(page);await page.locator('.task-panel').getByRole('button',{name:'Help',exact:true}).click();await button(page,'CT.HELP.DIRECT').click();await page.locator('.help-response').scrollIntoViewIfNeeded();await saved(page);await target(page,'ST.RAIL');await settled(page);await button(page,'CT.PLAN.STORY').click();await page.getByRole('textbox').fill('I will use these tiles together again.');await button(page,'CT.PLAN.RECORD').click();await target(page,'ST.RAIL');await settled(page);await button(page,'CT.WORK.REHEARSE').click();await expect(button(page,'CT.WORK.REPLAY')).toBeVisible();await button(page,'CT.UI.GOAL').click();await button(page,'CT.ENDING.REOPEN').click();await expect(page.getByRole('heading',{name:copy('CT.RECAP.HINT_THEN_PLAN'),exact:true})).toBeVisible();
 await saved(page);await page.reload();await button(page,'CT.START.CONTINUE').click();await button(page,'CT.UI.GOAL').click();await button(page,'CT.ENDING.REOPEN').click();await expect(page.getByRole('heading',{name:copy('CT.RECAP.RECORDED_IDEA'),exact:true})).toBeVisible();
});
