import{test,expect}from'@playwright/test';import{writeFile}from'node:fs/promises';import{start}from'./helpers.js';import{copy}from'../src/core/content.js';
test('diagnostic WebKit failed module retry across reload and fresh document URL',async({page,context})=>{
 await start(page);const next=await context.newPage(),events:unknown[]=[];next.on('request',r=>{if(r.url().includes('/assets/'))events.push({request:r.url()});});next.on('requestfailed',r=>events.push({failed:r.url(),error:r.failure()}));next.on('pageerror',e=>events.push({error:e.message}));
 await next.route('**/assets/App-*.js',r=>r.abort());await next.goto('/');await expect(next.getByRole('heading',{name:copy('CT.TECH.CONTENT_ERROR'),exact:true})).toBeVisible();await next.unroute('**/assets/App-*.js');events.push({phase:'reload'});await next.getByRole('button',{name:'Retry',exact:true}).click();await next.waitForLoadState('networkidle');const reload=await next.locator('body').innerText();events.push({phase:'fresh URL'});await next.goto('/?recovery=diagnostic');await next.waitForLoadState('networkidle');const fresh=await next.locator('body').innerText();await writeFile('evidence/er13/chunk-retry-diagnostic.json',JSON.stringify({reload,fresh,events},null,2)+'\n');await next.close();
});
test('diagnostic HTTP error retry compared with Inspector abort while interception stays enabled',async({page,context})=>{
 await start(page);const results=[];
 for(const mode of ['http','inspector'] as const){const next=await context.newPage(),events:unknown[]=[];let failed=true;next.on('request',r=>{if(r.url().includes('/assets/App-'))events.push({request:r.url()});});next.on('response',r=>{if(r.url().includes('/assets/App-'))events.push({response:r.url(),status:r.status()});});
 await next.route('**/assets/App-*.js',r=>failed?(mode==='http'?r.fulfill({status:503,headers:{'cache-control':'no-store','content-type':'text/plain'},body:'Declared transient service error'}):r.abort()):r.continue());await next.goto('/');await expect(next.getByRole('heading',{name:copy('CT.TECH.CONTENT_ERROR'),exact:true})).toBeVisible();failed=false;if(mode==='http')await next.unroute('**/assets/App-*.js');await next.getByRole('button',{name:'Retry',exact:true}).click();await next.waitForLoadState('networkidle');results.push({mode,events,retryBody:await next.locator('body').innerText()});await next.close();}
 await writeFile('evidence/er13/chunk-retry-http-comparison.json',JSON.stringify(results,null,2)+'\n');
});
