import {test,expect,type Page} from '@playwright/test';
import {saved} from './helpers.js';
const selection={moveId:'CLARIFY',refs:[],interpretation:'unclear',uncertain:true};
async function begin(page:Page){await page.goto('/?coach-test=synthetic');await expect(page.locator('html')).toHaveAttribute('data-coach-test','synthetic-lifecycle-only');await page.getByRole('button',{name:'Start',exact:true}).click();await page.getByRole('button',{name:'Help',exact:true}).click();await page.getByRole('button',{name:'Your story plan',exact:true}).click();await page.getByRole('textbox').fill('It goes there.');await page.getByRole('button',{name:'Help me think',exact:true}).click();}
test('FIX11.COACH.CLOSED/FOCUS synthetic transport holds hidden reply and stable fallback wins once',async({page})=>{
 await begin(page);await page.evaluate(()=>{(window as any).__eqCoachTest.advance(2000);});await expect(page.getByText('Still working on your question.')).toBeVisible();await page.getByRole('button',{name:'Return to festival',exact:true}).click();
 await page.evaluate(()=>{(window as any).__eqCoachTest.advance(8000);});await expect(page.getByRole('button',{name:'Help available',exact:true})).toBeVisible();expect((await saved(page)).payload.coachingHistory).toEqual([]);await page.getByRole('button',{name:'Help available',exact:true}).click();
 const fallback=page.getByRole('button',{name:'Use a prepared hint',exact:true});await fallback.focus();await page.evaluate(selection=>(window as any).__eqCoachTest.respond(selection),selection);await expect(fallback).toBeFocused();await expect(page.getByRole('button',{name:'View new reply',exact:true})).toBeVisible();expect((await saved(page)).payload.coachingHistory).toEqual([]);
 await fallback.click();await page.locator('.help-response').scrollIntoViewIfNeeded();await page.evaluate(selection=>(window as any).__eqCoachTest.respond(selection),selection);const state=await saved(page);expect(state.payload.coachingHistory).toHaveLength(1);expect(state.payload.coachingHistory[0]?.origin).toBe('authored-fallback');expect(state.payload.coachingHistory[0]?.selection).toBeNull();await page.screenshot({path:'output/playwright/synthetic-focused-fallback.png',fullPage:true});
});
test('FIX11.COACH.STALE/TIMEOUT synthetic edit, retry, malformed reply and client deadline preserve gameplay',async({page})=>{
 await begin(page);await page.getByRole('textbox').fill('The seed goes there.');await expect(page.getByText('Your plan or situation changed. Ask again about this version.')).toBeVisible();await page.evaluate(selection=>(window as any).__eqCoachTest.respond(selection),selection);expect((await saved(page)).payload.coachingHistory).toEqual([]);
 await page.getByRole('button',{name:'Help me think',exact:true}).click();await page.evaluate(()=>(window as any).__eqCoachTest.raw({finish:true}));await expect(page.getByText('Help couldn’t get a reply. You can use a prepared hint or try again.')).toBeVisible();await page.getByRole('button',{name:'Retry help',exact:true}).click();await page.evaluate(()=>(window as any).__eqCoachTest.advance(20000));await expect(page.getByRole('button',{name:'Use a prepared hint',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Cancel request',exact:true}).click();await expect(page.getByRole('textbox')).toHaveValue('The seed goes there.');await page.reload();await page.getByRole('button',{name:'Continue',exact:true}).click();expect(await page.evaluate(()=>(window as any).__eqCoachTest.calls().length)).toBe(0);expect((await saved(page)).payload.coachingHistory).toEqual([]);
});
test('FIX11.COACH.TIMEOUT real development admission timer expires at fifteen seconds without opening the panel',async({page})=>{
 await begin(page);await page.getByRole('button',{name:'Return to festival',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__eqCoachTest.snapshot().session.coach.status),{timeout:20000}).toBe('expired');await expect(page.getByRole('button',{name:'Help available',exact:true})).toBeVisible();await expect(page.locator('.task-panel')).toHaveCount(0);expect((await saved(page)).payload.coachingHistory).toEqual([]);expect(await page.evaluate(()=>(window as any).__eqCoachTest.calls().length)).toBe(1);
});
