import {test,expect,type Page,type Locator} from '@playwright/test';
import {copy} from '../src/core/content.js';
import {saved,workstation} from './helpers.js';
test.use({hasTouch:true});
async function activate(page:Page,locator:Locator){await expect(locator).toHaveCount(1);for(let n=0;n<120;n++){if(await locator.evaluate(el=>el===document.activeElement)){await page.keyboard.press('Enter');return;}const earlier=await locator.evaluate(el=>!!(document.activeElement?.compareDocumentPosition(el)!&Node.DOCUMENT_POSITION_PRECEDING));await page.keyboard.press(earlier?'Shift+Tab':'Tab');}throw new Error('Native Tab order did not reach '+await locator.textContent());}
const button=(page:Page,id:string)=>page.getByRole('button',{name:copy(id),exact:true});
async function keyTarget(page:Page,owner:string){await activate(page,button(page,'CT.UI.MOVE'));await activate(page,page.locator(`[data-owner="${owner}"]`));await expect(page.getByRole('button',{name:'Stop walking',exact:true})).toHaveCount(0);await saved(page);}
async function settings(page:Page,keyboard:boolean){
 const use=async(l:Locator)=>keyboard?activate(page,l):l.tap();await use(button(page,'CT.UI.MENU'));await use(button(page,'CT.UI.SETTINGS'));
 for(const label of ['Sound','Motion','Text size','Text spacing']){const select=page.getByLabel(label,{exact:true});if(keyboard){for(let n=0;n<40&&!await select.evaluate(el=>el===document.activeElement);n++)await page.keyboard.press('Tab');await expect(select).toBeFocused();await page.keyboard.press('End');}else await select.selectOption(label==='Sound'?'off':label==='Motion'?'reduced':label==='Text size'?'largest':'roomier');}
 await page.keyboard.press('Escape');await page.keyboard.press('Escape');
}
test('FIX11.ACCESS fresh 320x568 Largest Roomier reduced-motion sound-off case entirely through Tab and Enter',async({page})=>{
 test.setTimeout(300000);await page.setViewportSize({width:320,height:568});await page.goto('/');await activate(page,page.getByRole('button',{name:'Join the crew',exact:true}));await settings(page,true);
 await keyTarget(page,'ST.EXIT.WK');await keyTarget(page,'WK.EXIT.MD');await keyTarget(page,'MD.ACCESS.E8');await activate(page,button(page,'CT.KIT.COLLECT'));await expect(page.getByRole('button',{name:'Stop walking',exact:true})).toHaveCount(0);await keyTarget(page,'ACT.LOOP');await keyTarget(page,'MD.EXIT.WK');await keyTarget(page,'WK.EXIT.ST');await keyTarget(page,'ST.RACK.BAY');await keyTarget(page,'ST.DOCK');await keyTarget(page,'ST.RAIL');
 for(const [tile,after]of [['BRIDGE',null],['PLANT','Joined Boats'],['BLOOM','Hill']] as const){await activate(page,page.locator(`[data-tile="TILE.${tile}"]`));await activate(page,page.getByRole('button',{name:after?`Insert after ${after}`:'Place at the start',exact:true}));}
 await activate(page,button(page,'CT.WORK.REHEARSE'));await expect(button(page,'CT.WORK.LAUNCH')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'output/playwright/compact-keyboard-rehearsal.png',fullPage:false});await activate(page,button(page,'CT.WORK.LAUNCH'));await expect(page.getByRole('heading',{name:copy('CT.ENDING.TITLE'),exact:true})).toBeVisible();expect((await saved(page)).payload.premiere).not.toBeNull();await page.screenshot({path:'output/playwright/compact-keyboard-premiere.png',fullPage:false});
});
test('FIX11.ACCESS touch Arrange and Watch keep the whole puppet story visible at 640x360 Largest',async({page})=>{
 await page.setViewportSize({width:640,height:360});await workstation(page);await settings(page,false);await page.getByRole('button',{name:'Move to…',exact:true}).tap();await page.locator('[data-owner="ST.RAIL"]').tap();await expect(button(page,'CT.RAIL.ARRANGE_MODE')).toBeVisible();
 for(const [tile,after]of [['BRIDGE',null],['PLANT','Joined Boats'],['BLOOM','Hill']] as const){await page.locator(`[data-tile="TILE.${tile}"]`).tap();await page.getByRole('button',{name:after?`Insert after ${after}`:'Place at the start',exact:true}).tap();}
 await button(page,'CT.WORK.REHEARSE').tap();await expect(button(page,'CT.WORK.LAUNCH')).toBeVisible();await expect.poll(async()=>{const box=(await page.getByTestId('whole-story').boundingBox())!,dock=(await page.locator('.world-dock').boundingBox())!,caption=(await page.locator('.narrated-show .local-feedback').boundingBox())!;return box.height<=240&&box.y>=dock.y+dock.height-1&&box.y+box.height<=361&&caption.y+caption.height<=361;}).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'output/playwright/compact-touch-whole-story.png',fullPage:false});await button(page,'CT.WORK.LAUNCH').tap();await expect(page.getByRole('heading',{name:copy('CT.ENDING.TITLE'),exact:true})).toBeVisible();expect((await saved(page)).payload.premiere).not.toBeNull();
});
