import {test,expect} from '@playwright/test';
import {start,saved,target,settled,closePanel,workstation,putTile,injectSlots} from './helpers.js';
import {copy} from '../src/core/content.js';
test('ER13 fresh purpose, optional opening, re-entry, readings and exact word context',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'Our story needs an ending.'})).toBeVisible();await page.getByRole('button',{name:'Join the crew',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Jo story writer'})).toBeVisible();await expect(page.getByText(/There you are! Welcome to SparkFest/)).toBeVisible();await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByAltText('The red backpack you helped make')).toBeVisible();
 await page.getByRole('button',{name:'Keep exploring',exact:true}).click();await page.locator('.mission-control').click();await expect(page.getByRole('heading',{name:'Our story so far',exact:true})).toBeVisible();await expect(page.locator('[data-task]')).not.toContainText('Indoor recording room');
 await page.getByRole('button',{name:'Meet the crew',exact:true}).click();await expect(page.getByText(/This is Pip, our paper traveler/)).toBeVisible();await page.getByRole('button',{name:'Keep exploring',exact:true}).click();await page.getByRole('button',{name:'Read with the crew',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Welcome to our show',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:"Pip's promise",exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Our ending',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Show reading phrases',exact:true}).click();await page.getByRole('button',{name:'My turn',exact:true}).click();await expect(page.getByText(/Read it aloud when you’re ready/)).toBeVisible();await page.getByRole('button',{name:'I finished my turn',exact:true}).click();await page.getByRole('button',{name:'Try it again',exact:true}).click();await expect(page.getByText('This time, let your voice welcome the audience to our show.')).toBeVisible();
 await page.getByRole('button',{name:'Use this as my narrator card',exact:true}).click();await page.getByRole('button',{name:'together.',exact:true}).click();await expect(page.locator('.word-card blockquote')).toHaveText('We made the paper characters together.');await expect(page.getByText('With each other.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Return to the passage',exact:true}).click();
 const data=await saved(page);expect(data.payload.experience?.narratorCard).toBe('READ.WELCOME');expect(data.payload.observations.filter(o=>o.kind==='reading-practice-requested')).toHaveLength(2);expect(data.payload.observations.filter(o=>o.kind==='reading-self-reported')).toHaveLength(1);expect(data.payload.exposures).toEqual([]);expect(data.payload.certificate).toBeNull();await page.screenshot({path:'evidence/er13/reading-welcome.png',fullPage:true});
});
test('ER13 actual browser voice is used or its local English limitation is truthful',async({page})=>{
 await start(page);await page.getByRole('button',{name:'Read with the crew',exact:true}).click();await page.getByRole('button',{name:'Listen',exact:true}).click();
 await expect(page.locator('.speech-status')).toContainText(/Listening to this passage|not available in this browser|did not play/);
 const status=await page.locator('.speech-status').textContent(),data=await saved(page);if(status?.includes('Listening'))expect(data.payload.observations.some(o=>o.kind==='reading-model-played')).toBe(true);else expect(data.payload.observations.some(o=>o.kind==='reading-model-played')).toBe(false);
 await page.screenshot({path:'evidence/er13/browser-voice-status.png',fullPage:true});await closePanel(page);expect((await saved(page)).payload.physical.room).toBe('SC.ST');
});
test('ER13 still meanings remain bounded to actual source contexts and full notice support is supplied',async({page})=>{
 test.setTimeout(120000);await start(page);await target(page,'ST.SOURCE.E4');await settled(page);await page.locator('[data-word=STILL]').click();await expect(page.getByText('Not moving.',{exact:true})).toBeVisible();await expect(page.locator('.word-card blockquote')).toHaveText('I need a plain wall and paper petals that stay still.');await page.getByRole('button',{name:'Return to the passage',exact:true}).click();
 await target(page,'ST.EXIT.CY');await settled(page);await target(page,'CY.SOURCE.E3');await settled(page);expect((await saved(page)).payload.experience?.supports).toEqual([]);await page.getByRole('button',{name:'Flatten and secure notice',exact:true}).click();await settled(page);await page.locator('[data-word=STILL]').click();await expect(page.getByText('Continuing to be true.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Return to the passage',exact:true}).click();await page.locator('.crew-support').scrollIntoViewIfNeeded();await expect(page.getByText('The outdoor practice was canceled. The first public show is still planned.',{exact:true})).toBeVisible();await expect.poll(async()=>(await saved(page)).payload.experience?.supports).toContain('CT.ER13.SCOPE');
 expect((await saved(page)).payload.observations.some(o=>o.kind==='supplied-support')).toBe(true);
});
test('ER13 narrator card pauses actual cues once and stays optional for the whole show',async({page})=>{
 await workstation(page);await target(page,'ST.SOURCE.E6');await settled(page);await page.locator('[data-task]').getByRole('button',{name:'Read with the crew',exact:true}).click();await page.getByRole('button',{name:'Use this as my narrator card',exact:true}).click();await target(page,'ST.RAIL');await settled(page);await putTile(page,'BRIDGE');await putTile(page,'PLANT','Joined Boats');await putTile(page,'BLOOM','Hill');await page.getByRole('button',{name:'Pause between story steps for my narration',exact:true}).click();await page.getByRole('button',{name:'Try this ending',exact:true}).click();
 await expect.poll(async()=>(await saved(page)).payload.playback?.nextCue).toBe(1);expect((await saved(page)).payload.playback?.status).toBe('paused');await page.getByRole('button',{name:'Watch the show without pauses',exact:true}).click();await page.getByRole('button',{name:'Continue rehearsal',exact:true}).click();await expect(page.getByRole('button',{name:'Start premiere',exact:true})).toBeVisible();const data=await saved(page);expect(data.payload.playback?.cueResultIds).toHaveLength(3);expect(data.payload.certificate).not.toBeNull();await page.getByRole('button',{name:'Start premiere',exact:true}).click();await expect(page.getByRole('heading',{name:'The premiere',exact:true})).toBeVisible();await page.getByRole('button',{name:'Read our ending with the crew',exact:true}).click();await expect(page.getByRole('heading',{name:'Our ending',exact:true})).toBeVisible();
});
test('ER13 legacy save is preserved without forced introduction and compact reading stays operable',async({page})=>{
 await start(page);const old=await saved(page);delete old.payload.experience;old.payload.drafts[0]!.text='Keep my idea';await injectSlots(page,{current:JSON.stringify(old)});await page.reload();await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('heading',{name:'Jo story writer'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Meet the crew / Our story so far',exact:true})).toBeVisible();expect((await saved(page)).payload.drafts[0]!.text).toBe('Keep my idea');
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Read with the crew',exact:true}).click();await page.getByRole('button',{name:'Show reading phrases',exact:true}).click();await page.getByRole('button',{name:'My turn',exact:true}).click();await expect(page.getByRole('button',{name:'I finished my turn',exact:true})).toBeVisible();await page.screenshot({path:'evidence/er13/compact-reading.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});


test('ER13 physical model gives a readable consequence and reachable big-screen action at laptop size',async({page})=>{
 await page.setViewportSize({width:1422,height:800});await start(page);await target(page,'ST.MODEL.TAB');await settled(page);
 await expect(page.getByRole('heading',{name:'Our paper model',exact:true})).toBeVisible();const model=page.getByTestId('paper-model'),box=await model.boundingBox();expect(box!.width).toBeGreaterThan(350);
 await expect(page.getByText('Pip reaches the river, but the broken bridge stops him. Grandma is waiting across the water.',{exact:true})).toBeInViewport();await expect(page.getByRole('button',{name:'Try the big screen',exact:true})).toBeInViewport();
 const c=(await saved(page)).payload;expect(c.physical.objects.modelTabTried).toBe(true);expect(c.playback).toBeNull();expect(c.certificate).toBeNull();expect(c.grants).toEqual([]);await page.screenshot({path:'evidence/er13/physical-model-result.png',fullPage:true});
 await page.getByRole('button',{name:'Try the big screen',exact:true}).click();await settled(page);await expect(page.getByText(/Loop isn't in the dock/).first()).toBeInViewport();expect((await saved(page)).payload.physical.objects.previewTried).toBe(true);
});

test('ER13 clipped narrator words become source exposure only after their own card is scrolled',async({page})=>{
 await workstation(page);await target(page,'ST.SOURCE.E6');await settled(page);await page.locator('[data-task]').getByRole('button',{name:'Read with the crew',exact:true}).click();await page.getByRole('button',{name:'Use this as my narrator card',exact:true}).click();
 await page.getByRole('button',{name:'Menu',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByLabel('Text size',{exact:true}).selectOption('largest');await page.keyboard.press('Escape');await page.keyboard.press('Escape');
 // Explicit synthetic exposure reset isolates a granted but uninspected narrator card.
 const preset=await saved(page);preset.slotRevision++;preset.payload.exposures=[];preset.payload.readerResume=null;preset.payload.experience!.wordContexts=[];await injectSlots(page,{current:JSON.stringify(preset)});await page.reload();await page.getByRole('button',{name:'Continue',exact:true}).click();expect((await saved(page)).payload.exposures).toEqual([]);await target(page,'ST.RAIL');await settled(page);await page.getByRole('button',{name:'Watch rehearsal',exact:true}).click();
 const card=page.locator('.narrator-card .source-words');await card.scrollIntoViewIfNeeded();let state=(await saved(page)).payload;const extent=()=>Math.max(0,...state.exposures.filter(e=>e.ctId==='CT.SRC.E6').flatMap(e=>e.spans.map(s=>s[1])));
 expect(extent()).toBeLessThan(Array.from(copy('CT.SRC.E6')).length);
 await card.evaluate(el=>{el.scrollTop=el.scrollHeight;});await expect.poll(async()=>{state=(await saved(page)).payload;return extent();}).toBe(Array.from(copy('CT.SRC.E6')).length);
});

test('ER13 lower world reading control restores a visible panel heading and return action',async({page})=>{
 await page.setViewportSize({width:1422,height:800});await start(page);const initial=await saved(page);await page.reload();await page.getByRole('button',{name:'Continue',exact:true}).click();
 await target(page,'ST.MODEL.TAB');await settled(page);await page.getByRole('button',{name:'Try the big screen',exact:true}).click();await settled(page);await closePanel(page);
 const reading=page.getByRole('button',{name:'Read with the crew',exact:true});await reading.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>scrollY)).toBeGreaterThan(0);const before=(await saved(page)).payload.physical;
 await reading.click();await expect(page.getByRole('heading',{name:'Welcome to our show',exact:true})).toBeFocused();await expect(page.getByRole('heading',{name:'Welcome to our show',exact:true})).toBeInViewport();await expect(page.getByRole('button',{name:'Return to story',exact:true})).toBeInViewport();
 const after=(await saved(page)).payload;expect(after.caseRunId).toBe(initial.payload.caseRunId);expect(after.physical).toEqual(before);expect(after.playback).toBeNull();await page.screenshot({path:'evidence/er13/reading-panel-position.png',fullPage:false});
});

test('ER13 seed-only pause keeps the whole consequence visible and permits a revised premiere',async({page})=>{
 await page.setViewportSize({width:1422,height:800});await workstation(page);await putTile(page,'FERRY');await putTile(page,'PLANT','One Boat');await putTile(page,'BLOOM','Hill');await page.getByRole('button',{name:'Try this ending',exact:true}).click();
 await expect.poll(async()=>(await saved(page)).payload.playback?.pauseReason).toBe('unmet');await expect(page.getByRole('button',{name:'Watch rehearsal',exact:true})).toHaveAttribute('aria-pressed','true');
 const scene=await page.getByTestId('whole-story').boundingBox();expect(scene!.y).toBeGreaterThanOrEqual(-1);expect(scene!.y+scene!.height).toBeLessThanOrEqual(801);await expect(page.locator('.narrated-show .caption')).toContainText('Grandma has the seed. Pip is still across the river.');await expect(page.locator('.narrated-show .caption')).toBeInViewport();
 const c=(await saved(page)).payload;expect(c.playback?.puppet).toEqual({pip:'left',seed:'right',boats:'separate',lit:false});expect(c.certificate).toBeNull();await page.screenshot({path:'evidence/er13/seed-only-visible-consequence.png',fullPage:false});
 await page.getByRole('button',{name:'Arrange tiles',exact:true}).click();await page.locator('[data-tile="TILE.BRIDGE"]').click();await page.getByRole('button',{name:'Replace One Boat',exact:true}).click();await page.getByRole('button',{name:'Try this ending',exact:true}).click();await expect(page.getByRole('button',{name:'Start premiere',exact:true})).toBeVisible();await page.getByRole('button',{name:'Start premiere',exact:true}).click();await expect(page.getByRole('heading',{name:'The premiere',exact:true})).toBeVisible();expect((await saved(page)).payload.premiere).not.toBeNull();
});
