import {completeConversation} from './garden-actions.js';
import {test,expect,type Page} from '@playwright/test';
test.use({launchOptions:{args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']}});
test.setTimeout(90000);
const button=(p:Page,name:string)=>p.getByRole('button',{name,exact:true});
async function mara(p:Page){await p.goto('/garden');await button(p,'Begin Pip’s adventure').click();await button(p,'Start playing').click();await button(p,'Go to Mara').click();await button(p,'Talk to Mara E').click();await completeConversation(p);}
async function record(p:Page){const box=p.locator('.g-practice-overlay');await box.getByRole('button',{name:'Start listening',exact:true}).click();await expect(box).toHaveAttribute('data-recording','listening');await expect(box.locator('.g-mic-live')).toBeVisible();await p.waitForTimeout(450);await box.getByRole('button',{name:'Stop',exact:true}).click();await expect(box).toHaveAttribute('data-recording','review');await expect.poll(async()=>Number(await box.getAttribute('data-local-audio-bytes'))).toBeGreaterThan(44);return box;}
test('Synthetic microphone device: local capture, replay, explicit feedback, discard and leave cleanup',async({page},info)=>{
 const requests:string[]=[];page.on('request',r=>{if(r.url().includes('/api/garden/'))requests.push(r.url());});await mara(page);await button(page,'Read a short part aloud').click();await expect(page.locator('.g-mic-off')).toContainText('Your microphone is off');const box=await record(page);expect(requests).toEqual([]);
 const localURL=await box.locator('audio').getAttribute('src');expect(localURL).toMatch(/^blob:/);await box.locator('audio').evaluate((audio:HTMLAudioElement)=>audio.play());await expect.poll(()=>box.locator('audio').evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeGreaterThan(0);
 await box.getByRole('button',{name:'Get feedback',exact:true}).click();await expect(box).toContainText("Reading feedback isn't available right now");expect(requests).toHaveLength(1);await page.screenshot({path:info.outputPath('temporary-reading-review.png')});
 await box.getByRole('button',{name:'Discard recording'}).click();await expect(box).toHaveAttribute('data-local-audio-bytes','0');await expect(box.locator('audio')).toHaveCount(0);expect(await page.evaluate(async url=>{try{await fetch(url!);return false;}catch{return true;}},localURL)).toBe(true);
 await record(page);await box.getByRole('button',{name:'Back to the story',exact:true}).click();await expect(page.locator('.g-practice-overlay')).toHaveCount(0);await expect(button(page,'Read a short part aloud')).toBeFocused();
 const disk=await page.evaluate(async()=>new Promise<string>(resolve=>{const r=indexedDB.open('evidence-quest-garden-adventure-v1');r.onsuccess=()=>{const db=r.result,t=db.transaction('slots'),q=t.objectStore('slots').getAll();t.oncomplete=()=>{resolve(JSON.stringify(q.result));db.close();};};}));expect(disk).not.toContain('base64');expect(disk).not.toContain('blob:');await info.attach('audio-proof-boundary',{body:'Synthetic Chromium audio input exercised actual capture/WAV/replay/discard handlers. Not a human pronunciation or provider assessment.',contentType:'text/plain'});
});
test('Late synthetic meaning feedback cannot replace an edited answer; compact reading controls remain reachable',async({page},info)=>{
 let release:()=>void=()=>{},received:()=>void=()=>{};const hit=new Promise<void>(r=>received=r),hold=new Promise<void>(r=>release=r);
 await page.route('**/api/garden/feedback',async route=>{const q=route.request().postDataJSON();received();await hold;await route.fulfill({json:{requestId:q.requestId,status:'supported',feedback:'STALE SYNTHETIC REPLY',scene:null}}).catch(()=>{});});
 await mara(page);await button(page,"I'll ask Grandma to start the next gathering later.").click();const activity=page.getByRole('region',{name:'How would starting later help me get to the gathering?'});await activity.getByRole('textbox').fill('Mara finishes work after the boat returns.');await activity.getByRole('button',{name:'Ask for feedback'}).click();await hit;await activity.getByRole('textbox').fill('My newer answer is still mine.');release();await expect(activity).not.toContainText('STALE SYNTHETIC REPLY');await expect(activity.getByRole('textbox')).toHaveValue('My newer answer is still mine.');
 await page.setViewportSize({width:320,height:568});await button(page,'Read a short part aloud').click();const overlay=page.locator('.g-practice-overlay');await expect(overlay.getByRole('button',{name:'Start listening'})).toBeInViewport();await overlay.getByRole('button',{name:'Back to the story',exact:true}).scrollIntoViewIfNeeded();await expect(overlay.getByRole('button',{name:'Back to the story',exact:true})).toBeInViewport();await page.screenshot({path:info.outputPath('compact-reading-practice.png')});await page.keyboard.press('Escape');await expect(button(page,'Read a short part aloud')).toBeFocused();
});
