import {test,expect} from '@playwright/test';
import {completeConversation} from './garden-actions.js';
import {sources} from '../src/garden/content.js';
import {readWholeStory} from './garden-story-reading.js';
test.setTimeout(90000);
test('Complete reading: the whole story is heard in order, can stop, and resumes without sending the page',async({page},info)=>{
 // Explicit synthetic local voice callbacks: exact text and cancellation only, not voice quality.
 await page.addInitScript(()=>{
  const track={stop(){},addEventListener(){}};Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia:async()=>({getTracks:()=>[track],getAudioTracks:()=>[track]})},configurable:true});
  (window as any).AudioContext=class{sampleRate=16000;state='running';destination={};audioWorklet={addModule:async()=>{}};createMediaStreamSource(){return{connect(){}};}async resume(){}async close(){this.state='closed';}};
  (window as any).AudioWorkletNode=class{port:any={onmessage:null,postMessage:()=>{this.port.onmessage?.({data:{samples:new Float32Array(16000)}});this.port.onmessage?.({data:{done:true}});},close(){}};connect(){}disconnect(){}};
  const state={spoken:[]as string[],pending:null as any};(window as any).__storyVoice=state;
  Object.defineProperty(window,'speechSynthesis',{configurable:true,value:{getVoices:()=>[{localService:true,lang:'en-US'}],speak:(u:any)=>{state.spoken.push(u.text);state.pending=u;},cancel:()=>{}}});
  Object.defineProperty(window,'SpeechSynthesisUtterance',{configurable:true,value:class{constructor(public text:string){}}});
 });
 const button=(name:string)=>page.getByRole('button',{name,exact:true});
 await page.goto('/garden');await button('Begin Pip’s adventure').click();await button('Start playing').click();await button('Go to Mara').click();await button('Talk to Mara E').click();await completeConversation(page);await button('I can read your story to Grandma.').click();await expect(page.locator('.garden-reading-scroll')).toContainText('Pip is carrying her copy.');await button('Backpack').click();await page.locator('.g-item').filter({has:page.locator('strong',{hasText:'The Torn Wing'})}).getByRole('button',{name:'Read',exact:true}).click();
 const tools=page.getByRole('region',{name:'Read the complete The Torn Wing',exact:true});await tools.getByRole('button',{name:'Hear the whole story',exact:true}).click();
 for(let i=0;i<10&&await tools.getByRole('button',{name:'Stop listening',exact:true}).count();i++)await page.evaluate(()=>(window as any).__storyVoice.pending.onend());
 expect(await page.evaluate(()=>(window as any).__storyVoice.spoken.join(''))).toBe(sources.story.paragraphs.join('\n\n'));
 await tools.getByRole('button',{name:'Hear the whole story',exact:true}).click();await tools.getByRole('button',{name:'Stop listening',exact:true}).click();const count=await page.evaluate(()=>(window as any).__storyVoice.spoken.length);await page.evaluate(()=>(window as any).__storyVoice.pending.onend());expect(await page.evaluate(()=>(window as any).__storyVoice.spoken.length)).toBe(count);
 await tools.getByRole('button',{name:'Hear the whole story',exact:true}).click();const closingCount=await page.evaluate(()=>(window as any).__storyVoice.spoken.length);await button('Back to the backpack').click();await page.evaluate(()=>(window as any).__storyVoice.pending.onend());expect(await page.evaluate(()=>(window as any).__storyVoice.spoken.length)).toBe(closingCount);await page.locator('.g-item').filter({has:page.locator('strong',{hasText:'The Torn Wing'})}).getByRole('button',{name:'Read',exact:true}).click();
 await readWholeStory(page,'The Torn Wing',sources.story.paragraphs.join('\n\n'));await tools.getByRole('button',{name:'Read the whole story aloud',exact:true}).click();await expect(page.locator('.g-reading-pages')).toContainText('Page 2 of 2');await expect(button('Next reading page')).toBeDisabled();await button('Previous reading page').click();await expect(page.locator('.g-practice-words')).toContainText(sources.story.paragraphs[0]!);await page.setViewportSize({width:320,height:568});await expect(button('Start listening')).toBeVisible();await expect(button('Back to the story')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('whole-story-compact.png')});await page.locator('.g-practice-overlay').getByRole('button',{name:'Hear this part',exact:true}).click();await button('Start listening').click();await expect(page.locator('.g-practice-overlay')).toHaveAttribute('data-recording','listening');await page.locator('.g-practice-overlay').evaluate(el=>{el.scrollTop=el.scrollHeight;});await expect(button('Stop')).toBeInViewport({ratio:1});await page.locator('.g-practice-overlay').evaluate(el=>{el.scrollTop=0;});await expect(button('Stop')).toBeInViewport({ratio:1});await expect(button('Next reading page')).toBeDisabled();await button('Stop').click();await button('Discard recording').click();await button('Back to the story').click();await expect(tools.getByRole('button',{name:'Stop listening',exact:true})).toHaveCount(0);await button('Back to the backpack').click();await expect(page.locator('.g-item').filter({hasText:'The Torn Wing'})).toBeVisible();
 await info.attach('scope',{body:'Ordinary page controls, complete text, local resume and page possession. Model speech and microphone capture use labeled synthetic seams. No native microphone, replay decoder, provider or acoustic qualification.',contentType:'text/plain'});
});
