import {playBakery,completeConversation} from './garden-actions.js';
import{test,expect,type Page}from'@playwright/test';import{OrthographicCamera,Vector3}from'three';
test.setTimeout(150000);const b=(p:Page,name:string)=>p.getByRole('button',{name,exact:true});
async function writing(p:Page){await p.goto('/garden');await b(p,'Begin Pip’s adventure').click();await b(p,'Start playing').click();await b(p,'Go to the bridge pieces').click();await b(p,'Arrange bridge').click();await b(p,'Take the repair ropes').click();for(const[name,x]of[['A',-.775],['B',.775]]as const){await p.locator('.g-select-sections').getByRole('button',{name:'Section '+name,exact:true}).click();const box=(await p.locator('.garden-scene canvas').boundingBox())!,aspect=box.width/box.height,h=Math.max(6.5,10.2/aspect),camera=new OrthographicCamera(-h*aspect,h*aspect,h,-h,.1,100);camera.position.set(8.75,16,19.1);camera.lookAt(1.25,0,.1);camera.updateMatrixWorld();const pt=new Vector3(x,.13,3).project(camera);await p.mouse.click(box.x+(pt.x*.5+.5)*box.width,box.y+(-pt.y*.5+.5)*box.height);}await b(p,'Join sections').click();await p.getByRole('button',{name:'Fasten dock-side end'}).click();await p.getByRole('button',{name:'Fasten garden-side end'}).click();await b(p,'Back to Pip').click();await b(p,'Go to Grandma').click();await b(p,'Talk to Grandma E').click();await p.locator('.g-reader-top .g-close').click();await playBakery(p);await b(p,'Talk to Sol').click();await completeConversation(p);await b(p,'Let’s finish the ending together.').click();}
test('Actual draft word view: local unavailable help, synthetic spelling suggestion, selected-occurrence edit and undo',async({page},info)=>{
 await writing(page);const original='Rina brought me a loaf to show her apreciation. I felt apreciation too.';await page.getByLabel('Your ending for Sol’s story',{exact:true}).fill(original);await b(page,'Read my ending aloud').click();await expect(page.locator('.g-draft-reader')).toContainText('Read your ending aloud as Sol. Pause at each full stop.');await page.locator('.g-draft-reader .g-manuscript').getByRole('button',{name:'apreciation',exact:true}).first().click();const card=page.getByRole('complementary',{name:'Your word: apreciation'});await card.getByRole('button',{name:'Ask for word help'}).click();await expect(card).toContainText("Word help isn't available for this word right now. Your writing is unchanged.");await expect(page.getByLabel('Your ending for Sol’s story',{exact:true})).toHaveValue(original);
 await page.route('**/api/garden/word',async route=>{const q=route.request().postDataJSON();await route.fulfill({json:{requestId:q.requestId,revision:q.revision,start:q.start,end:q.end,word:q.word,status:'supported',meaning:'A feeling of thanks.',explanation:'Synthetic spelling suggestion for the selected occurrence only.',spelling:'appreciation'}});});await card.getByRole('button',{name:'Ask for word help'}).click();await expect(card.getByRole('button',{name:'Hear suggested word'})).toBeVisible();await card.getByRole('button',{name:'Use appreciation',exact:true}).click();await expect(page.getByLabel('Your ending for Sol’s story',{exact:true})).toHaveValue('Rina brought me a loaf to show her appreciation. I felt apreciation too.');await b(page,'Undo spelling change').click();await expect(page.getByLabel('Your ending for Sol’s story',{exact:true})).toHaveValue(original);await b(page,'Read it again').click();await expect(page.locator('.g-draft-reader')).toContainText('Try reading those words with more emphasis.');await page.screenshot({path:info.outputPath('own-ending-reading.png')});await b(page,'Back to my ending').click();await expect(page.getByLabel('Your ending for Sol’s story',{exact:true})).toBeFocused();
 await b(page,'Read my ending aloud').click();
 for(const width of [1440,320]){await page.setViewportSize({width,height:width===320?568:1000});const actions=page.locator('.g-draft-reader .g-row>button');const sizes=await actions.evaluateAll(nodes=>nodes.map(node=>({width:node.getBoundingClientRect().width,client:node.clientWidth,scroll:node.scrollWidth})));for(const size of sizes){expect(size.width).toBeGreaterThanOrEqual(140);expect(size.scroll).toBeLessThanOrEqual(size.client+1);}await b(page,'Read with feedback').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('reading-buttons-'+width+'.png')});}
 await b(page,'Back to my ending').click();await page.setViewportSize({width:1440,height:1000});
 await page.getByLabel('Your ending for Sol’s story',{exact:true}).fill('My repair helped Rina bake the bread she had promised.');let calls=0;await page.route('**/api/garden/feedback',async route=>{calls++;const q=route.request().postDataJSON();await route.fulfill({json:q.disputed?{requestId:q.requestId,status:'unavailable'}:{requestId:q.requestId,status:'contradiction',feedback:'SYNTHETIC DISPUTED CLAIM',scene:null}});});const activity=page.getByRole('region',{name:'Would you like help with your ending?'});await activity.getByRole('button',{name:'Ask for feedback'}).click();await activity.getByRole('button',{name:'Check that feedback'}).click();await expect(activity).not.toContainText('SYNTHETIC DISPUTED CLAIM');await expect(activity).toContainText("I couldn't check that feedback reliably. You can keep your ending or change it after rereading Sol's story.");expect(calls).toBe(2);await expect(page.getByLabel('Your ending for Sol’s story',{exact:true})).toHaveValue('My repair helped Rina bake the bread she had promised.');await info.attach('synthetic-boundary',{body:'Actual connected reading/edit/recheck controls, with explicitly injected provider responses. No live model accuracy or pronunciation acceptance.',contentType:'text/plain'});
});
