import {savedChapter as saved} from './garden-save-fixture.js';
import {test,expect,type Page} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {playSpeakingTurn,playLoopStory} from './garden-actions.js';
import {installPlaybackVoice,finishVoiceSegment} from './garden-playback-voice.js';
test.setTimeout(180000);
const button=(p:Page,name:string)=>p.getByRole('button',{name,exact:true});
test('Finale: authentic prior-save fixture, actual memory placement, lantern source return, compact show and replay recovery',async({page},info)=>{
 await installPlaybackVoice(page);
 const captures=JSON.parse(readFileSync('evidence/group-7-review-20260915/group-6-migration-inputs.json','utf8').replace(/^\uFEFF/,'')),fixture=captures.cases.find((c:any)=>c.name==='later-pip-prepared-before-pip-moment');
 await info.attach('fixture-boundary',{body:'Unedited actual-handler Group6 moment checkpoint transported into isolated automated browser. Later controls are ordinary UI actions. This is migration/connected-browser evidence, not a fresh native journey or provider qualification.',contentType:'text/plain'});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/garden');await saved(page);
 await page.evaluate(async record=>new Promise<void>(resolve=>{const r=indexedDB.open('evidence-quest-garden-adventure-v1');r.onsuccess=()=>{const db=r.result,t=db.transaction('slots','readwrite');t.objectStore('slots').put(record,'current');t.oncomplete=()=>{db.close();resolve();};};}),fixture.envelope);await page.reload();const before=await saved(page);
 await page.locator('.garden-access>summary').click();await page.getByText('Inspect a particular flower',{exact:true}).click();await button(page,'Pip’s promise · Pip').click();await expect(page.locator('[data-lantern="pip"]')).toContainText('Grandma has shared her story');await button(page,'Back to Pip').click();await expect(button(page,'Pip’s promise · Pip')).toBeFocused();await page.locator('.garden-access>summary').click();await button(page,'Talk to Grandma E').click();await button(page,'Continue the gathering').click();await button(page,'Sharing our stories').click();await page.getByRole('navigation',{name:'Reading tools',exact:true}).getByRole('button',{name:'Help',exact:true}).click();await button(page,'Back to the gathering').click();await expect(button(page,'Sharing our stories')).toHaveAttribute('aria-pressed','true');expect(await page.locator('.garden-reader .g-story-stage').count()).toBe(0);await button(page,'Keep this moment').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-action-kind','keepMemory');await page.screenshot({path:info.outputPath('pip-places-actual-memory.png')});await button(page,'Hear Grandma and Mara finish their conversation').click();await page.screenshot({path:info.outputPath('actual-closing-speakers.png')});await playSpeakingTurn(page);await button(page,'Finish the chapter').click();
 await button(page,'Read the garden’s stories').click();await expect(page.locator('.g-lantern-library article')).toHaveCount(6);await expect(page.locator('.g-lantern-library canvas')).toHaveCount(0);await button(page,'Open A Small Repair').click();await expect(page.locator('.garden-reader')).toContainText(before.gathering.solPerformed.text);await expect(page.locator('.garden-reader')).toContainText('The ending Sol shared');await button(page,'Back to the lantern stories').click();await button(page,'Inspect A Small Repair').click();await expect(page.locator('[data-world-activity="lantern-inspect"]')).toContainText(before.gathering.solPerformed.text);await expect(page.locator('[data-world-activity="lantern-inspect"]')).toContainText('Your suggested ending');await button(page,'Read A Small Repair with help').click();await expect(page.locator('.garden-reader')).toContainText('The ending Sol shared');await expect(page.locator('.garden-reader')).toContainText(before.gathering.solPerformed.text);await button(page,'Back to this lantern').click();await expect(page.locator('[data-lantern="sol"]')).toBeVisible();await button(page,'Back to the lantern stories').click();await button(page,'Back to Loop').click();
 await button(page,'Narrate the ending').click();await expect(page.getByRole('group',{name:'Whole story playback',exact:true})).toHaveAttribute('data-playback-mode','captions');await button(page,'Pause story').click();await expect(page.locator('.garden-reader')).toHaveCount(0);await expect(page.locator('[data-stage-scene="planting"]')).toBeVisible();await page.setViewportSize({width:320,height:568});await page.screenshot({path:info.outputPath('compact-loop-world.png')});for(const name of ['Resume story','Read the whole story with help','Pause · Back to studio']){const rect=await button(page,name).boundingBox();expect(rect?.width).toBeGreaterThan(0);expect(rect?.height).toBeGreaterThanOrEqual(48);}const picture=await page.locator('.garden-world-activity>.g-story-stage').boundingBox();expect(picture?.height).toBeGreaterThanOrEqual(200);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await button(page,'Read the whole story with help').click();await expect(page.locator('.g-reader-context')).toContainText('Loop is waiting at this picture');await button(page,'kept').click();await expect(page.getByRole('complementary',{name:'Word help: kept'})).toContainText('Did what he had said he would do.');await button(page,'Close word help').click();await page.getByRole('region',{name:'Read the complete Pip’s adventure',exact:true}).getByRole('button',{name:'Read the whole story aloud',exact:true}).click();await expect(page.locator('.g-mic-off')).toContainText('Your microphone is off');await page.locator('.g-practice-overlay').getByRole('button',{name:'Back to the story',exact:true}).click();await button(page,'Back to Loop’s picture show').click();await expect(page.locator('[data-presentation-page="0"]')).toBeVisible();await page.setViewportSize({width:1440,height:1000});
 await button(page,'Pause · Back to studio').click();await button(page,'Watch the ending').click();await playLoopStory(page);await button(page,'Watch the ending').click();await expect(page.locator('[data-presentation-page="0"]')).toBeVisible();for(let i=0;i<3;i++){await finishVoiceSegment(page);await expect(page.locator('[data-presentation-page='+JSON.stringify(String(i+1))+']')).toBeVisible();}await button(page,'Pause · Back to studio').click();await expect.poll(async()=>(await saved(page)).story.presentation.inProgress).toBe(true);await page.reload();await button(page,'Watch your ending').click();await button(page,'Watch the ending').click();await expect(page.locator('[data-presentation-page="3"]')).toBeVisible();await page.screenshot({path:info.outputPath('replay-restores-picture-four.png')});await playLoopStory(page);const end=await saved(page);for(const key of ['seed','river','sections','page','mara','bakery','pip'])expect(end[key]).toEqual(before[key]);expect(end.story.records.pip).toBe('gathering');expect(end.story.solEnding).toEqual(before.story.solEnding);expect(end.story.presentation).toMatchObject({page:3,finished:true,inProgress:false});expect(errors).toEqual([]);await info.attach('finale-result',{body:JSON.stringify(end,null,2),contentType:'application/json'});
});
