import {deliverMaraReport} from './garden-actions.js';
import {test,expect,type Page} from '@playwright/test';
import {playBird,completeConversation} from './garden-actions.js';
test.setTimeout(180000);
const button=(p:Page,name:string)=>p.getByRole('button',{name:name==='Back to Pip'?/^(Back to Pip|Continue to the game)$/:name==='Plan the gathering with Grandma'?/^(Plan the gathering with Grandma|Review the gathering plan with Grandma)$/:name==='Let’s talk about why Mara stopped visiting.'?/^(Let’s talk about why Mara stopped visiting\.|Tell Grandma what Mara said)$/:name,exact:true});
async function saved(p:Page){await expect(p.locator('.g-save')).toHaveText('Saved in this browser');return p.evaluate(async()=>new Promise<any>(resolve=>{const r=indexedDB.open('evidence-quest-garden-adventure-v1');r.onsuccess=()=>{const db=r.result,t=db.transaction('slots'),q=t.objectStore('slots').get('current');t.oncomplete=()=>{db.close();resolve(q.result.payload);};};}));}
test('G4 ordinary early telling: actual duty, no source shortcut, compact repair, pause/reload and same present-day facts',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/garden');await button(page,'Begin Pip’s adventure').click();await button(page,'Start playing').click();await button(page,'Go to Mara').click();await button(page,'Talk to Mara E').click();
 await button(page,'Watch Mara help these passengers').click();await expect(page.locator('.garden-feedback')).toContainText('operator');await page.screenshot({path:info.outputPath('dock-service.png')});await expect(page.locator('.garden-scene')).toHaveAttribute('data-dock-service','served');await completeConversation(page);await button(page,'I can read your story to Grandma.').click();await expect(page.locator('.garden-reading-scroll')).toContainText('Pip is carrying her copy.');await button(page,'I can bring you a story if you’re still working.').click();expect((await saved(page)).mara.returnOffered).toBe(true);await button(page,'Back to Pip').click();
 await button(page,'Go to the bridge pieces').click();await button(page,'Arrange bridge').click();await button(page,'Take the repair ropes').click();await expect(button(page,'Take the repair ropes')).toHaveCount(0);
 for(const [section,side]of [['A','dock'],['B','garden']]as const){await page.locator('.g-select-sections').getByRole('button',{name:'Section '+section,exact:true}).click();await button(page,`Narrow crossing · ${side}-side post`).click();await page.getByRole('button',{name:'Place section'}).click();}
 await button(page,'Join sections').click();await page.getByRole('button',{name:'Fasten dock-side end'}).click();await page.getByRole('button',{name:'Fasten garden-side end'}).click();await button(page,'Back to Pip').click();await button(page,'Go to Grandma').click();await button(page,'Talk to Grandma E').click();await page.getByRole('button',{name:'Give Grandma Mara’s page'}).click();await deliverMaraReport(page);await page.getByRole('button',{name:'Read The Torn Wing'}).click();const before=await saved(page);expect(before.story.records.mara).toBe(null);
 await page.locator('.g-reader-top .g-close').click();expect((await saved(page)).story.records.mara).toBe(null);await page.getByRole('button',{name:'Read The Torn Wing'}).click();await button(page,'Share The Torn Wing with Grandma').click();await expect(page.locator('.g-mara-scene')).toHaveAttribute('data-bird-stage','ask');
 await page.setViewportSize({width:320,height:568});await page.screenshot({path:info.outputPath('earlier-dock-compact.png')});const box=await page.locator('.g-mara-scene canvas').boundingBox();expect(box?.width).toBeGreaterThan(200);expect(box?.height).toBeGreaterThanOrEqual(145);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await button(page,'Speak to the boy').click();await button(page,'Would you like some help?').click();await button(page,'Walk to the dock office').click();await button(page,'Pick up the tape').click();await expect(page.locator('.g-mara-scene')).toHaveAttribute('data-tape','mara');await button(page,'Pause').click();await button(page,'Back to Mara’s earlier story').click();await page.reload();await expect(page.locator('.g-mara-scene')).toHaveAttribute('data-tape','mara');await button(page,'Return to the boy').click();await button(page,'Line up the torn wing').click();await button(page,'Tape beside the tear').click();await button(page,'Place the strip').click();await expect(page.locator('.g-mara-scene')).toHaveAttribute('data-strip','beside');await page.screenshot({path:info.outputPath('misplaced-strip.png')});await button(page,'Tape across the tear').click();await page.keyboard.press('Escape');await expect(page.locator('.g-mara-scene')).toBeVisible();await expect(page.locator('.garden-reader')).toHaveCount(0);await expect(page.locator('.g-mara-scene')).toHaveAttribute('data-preview','');await button(page,'Tape across the tear').click();await button(page,'Help').click();await button(page,'Read Grandma’s letter').click();await button(page,'Back to Help').click();await button(page,'Back to Mara’s earlier story').click();await expect(page.locator('.g-mara-scene')).toHaveAttribute('data-preview','');await expect(page.locator('.g-mara-scene')).toHaveAttribute('data-strip','beside');
 await button(page,'Tape across the tear').click();await button(page,'Place the strip').click();await button(page,'Let the boy carry his bird').click();await button(page,'Return to Grandma’s garden').click();await expect(button(page,'A promise to his sister')).toBeVisible();await button(page,'A promise to his sister').click();const end=await saved(page);expect(end.mara.participated).toBe(true);expect(end.mara.sharedAt).toBe('early');expect(end.story.records.mara).toBe('promise');for(const key of ['pip','seed','page','sections','river'])expect(end[key]).toEqual(before[key]);expect(end.story.plan).toEqual(before.story.plan);expect(end.story.maraInvitation).toBe(null);expect(errors).toEqual([]);
 await button(page,'Share The Torn Wing again').click();await expect(page.locator('.garden-reader')).toBeVisible();await expect(page.locator('.g-mara-scene')).toHaveCount(0);await page.screenshot({path:info.outputPath('shared-picture.png')});
});
