import {buildStagedBridge} from './garden-actions.js';
import {openDirections} from './garden-actions.js';
import {playBakery,completeConversation} from './garden-actions.js';
import {savedChapter} from './garden-save-fixture.js';
import{test,expect,type Page}from'@playwright/test';import{worldPoint}from'./garden-actions.js';
test.setTimeout(240000);const b=(p:Page,name:string)=>p.getByRole('button',{name,exact:true});
async function writing(p:Page){await p.goto('/garden');await b(p,'Begin Pip’s adventure').click();await b(p,'Start playing').click();await buildStagedBridge(p);await b(p,'Go to Grandma').click();await b(p,'Talk to Grandma E').click();await p.locator('.g-reader-top .g-close').click();await playBakery(p);await b(p,'Talk to Sol').click();await completeConversation(p);await b(p,'Let’s finish the ending together.').click();}
test('Actual draft word view: local unavailable help, synthetic spelling suggestion, selected-occurrence edit and undo',async({page},info)=>{
 await writing(page);const original='Rina brought me a loaf to show her apreciation. I felt apreciation too.';await page.getByLabel('Your ending for Sol’s story',{exact:true}).fill(original);await b(page,'Review my ending').click();await expect(page.locator('.g-draft-reader')).toContainText('Read your ending aloud as Sol. Pause at each full stop.');await page.locator('.g-draft-reader .g-manuscript').getByRole('button',{name:'apreciation',exact:true}).first().click();const card=page.getByRole('complementary',{name:'Your word: apreciation'});await card.getByRole('button',{name:'Ask for word help'}).click();await expect(card).toContainText("Word help isn't available for this word right now. Your writing is unchanged.");await expect(page.getByLabel('Your ending for Sol’s story',{exact:true})).toHaveValue(original);
 await page.route('**/api/garden/word',async route=>{const q=route.request().postDataJSON();await route.fulfill({json:{requestId:q.requestId,revision:q.revision,start:q.start,end:q.end,word:q.word,status:'supported',meaning:'A feeling of thanks.',explanation:'Synthetic spelling suggestion for the selected occurrence only.',spelling:'appreciation'}});});await card.getByRole('button',{name:'Ask for word help'}).click();await expect(card.getByRole('button',{name:'Hear suggested word'})).toBeVisible();await card.getByRole('button',{name:'Use appreciation',exact:true}).click();await expect(page.getByLabel('Your ending for Sol’s story',{exact:true})).toHaveValue('Rina brought me a loaf to show her appreciation. I felt apreciation too.');await b(page,'Undo spelling change').click();await expect(page.getByLabel('Your ending for Sol’s story',{exact:true})).toHaveValue(original);await b(page,'Read it again').click();await expect(page.locator('.g-draft-reader')).toContainText('Try reading those words with more emphasis.');await page.screenshot({path:info.outputPath('own-ending-reading.png')});await b(page,'Back to my ending').click();await expect(page.getByLabel('Your ending for Sol’s story',{exact:true})).toBeFocused();
 await b(page,'Review my ending').click();
 for(const width of [1440,320]){await page.setViewportSize({width,height:width===320?568:1000});const actions=page.locator('.g-draft-reader .g-row>button');const sizes=await actions.evaluateAll(nodes=>nodes.map(node=>({width:node.getBoundingClientRect().width,client:node.clientWidth,scroll:node.scrollWidth})));for(const size of sizes){expect(size.width).toBeGreaterThanOrEqual(140);expect(size.scroll).toBeLessThanOrEqual(size.client+1);}await b(page,'Practise reading my ending').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('reading-buttons-'+width+'.png')});}
 await b(page,'Back to my ending').click();await page.setViewportSize({width:1440,height:1000});
 await page.getByLabel('Your ending for Sol’s story',{exact:true}).fill('My repair helped Rina bake the bread she had promised.');let calls=0,suggest=false,releaseReply=()=>{};let replyGate:Promise<void>|null=null;
 await page.route('**/api/garden/feedback',async route=>{calls++;const q=route.request().postDataJSON(),binding={requestId:q.requestId,revision:q.revision,draftRevision:q.draftRevision};if(replyGate)await replyGate;await route.fulfill({json:suggest?{...binding,status:'supported',feedback:'SYNTHETIC PICTURE SUGGESTION',scene:'bread'}:q.disputed?{...binding,status:'unavailable'}:{...binding,status:'contradiction',feedback:'SYNTHETIC DISPUTED CLAIM',scene:null}});});
 await page.getByText('Support for my ending',{exact:true}).click();const activity=page.getByRole('region',{name:'Would you like help with your ending?'});await activity.getByRole('button',{name:'Ask for feedback'}).click();await activity.getByRole('button',{name:'Check that feedback'}).click();await expect(activity).not.toContainText('SYNTHETIC DISPUTED CLAIM');await expect(activity).toContainText("I couldn't check that feedback reliably. You can keep your ending or change it after rereading Sol's story.");expect(calls).toBe(2);await expect(page.getByLabel('Your ending for Sol’s story',{exact:true})).toHaveValue('My repair helped Rina bake the bread she had promised.');
 const scrollChanges:unknown[]=[];
 async function scrollUnchangedDraft(){const before=await savedChapter(page);await page.locator('.garden-reading-scroll').hover();await page.mouse.wheel(0,-500);await expect.poll(async()=>JSON.stringify((await savedChapter(page)).reading)).not.toBe(JSON.stringify(before.reading));const after=await savedChapter(page);expect(after.revision).toBeGreaterThan(before.revision);expect(after.story.solDraft).toEqual(before.story.solDraft);scrollChanges.push({before:before.revision,after:after.revision,draftRevision:after.story.solDraft.revision});}
 suggest=true;await b(page,'Rina thanks Sol').click();replyGate=new Promise<void>(resolve=>releaseReply=resolve);await activity.getByRole('button',{name:'Ask for feedback'}).click();await expect.poll(()=>calls).toBe(3);await scrollUnchangedDraft();releaseReply();replyGate=null;
 await expect(activity.getByRole('button',{name:'Use suggested picture'})).toBeVisible();await expect(b(page,'Rina thanks Sol')).toHaveAttribute('aria-pressed','true');await activity.getByRole('button',{name:'Keep my picture'}).click();await expect(b(page,'Rina thanks Sol')).toHaveAttribute('aria-pressed','true');
 await activity.getByRole('button',{name:'Ask for feedback'}).click();await expect(activity.getByRole('button',{name:'Use suggested picture'})).toBeVisible();await scrollUnchangedDraft();await activity.getByRole('button',{name:'Use suggested picture'}).click();await expect(b(page,'Rina bakes the bread')).toHaveAttribute('aria-pressed','true');expect(calls).toBe(4);
 await info.attach('reading-position-preserves-feedback',{body:JSON.stringify(scrollChanges),contentType:'application/json'});
 await info.attach('synthetic-boundary',{body:'Actual connected reading/edit/recheck controls, native wheel changes while a reply is pending and before explicit picture acceptance, with injected revision-bound provider responses. Neither receiving nor declining a suggestion changes the chosen picture. No live model accuracy or pronunciation acceptance.',contentType:'text/plain'});
});
