import {test,expect} from '@playwright/test';

for(const viewport of [{width:1440,height:1000},{width:320,height:568}])test(`SparkFest welcome: approved cast illustration, Loop identity and supported entry at ${viewport.width}px`,async({page},info)=>{
 await page.setViewportSize(viewport);await page.goto('/garden');const welcome=page.locator('.festival-welcome');await expect(welcome).toBeVisible();await expect(welcome).toContainText('SparkFest');await expect(welcome).toContainText('The Garden Adventure is one of the stories you can step into.');await expect(welcome).toContainText('Meet Loop, our rolling projector.');await expect(welcome).toContainText('Loop shines pictures onto a screen');await expect(welcome).toContainText('When Pip’s adventure ends, we’ll return here.');
 const cast=welcome.locator('img[src="/art/sparkfest/cast-original.png"]');await expect(cast).toBeVisible();await expect.poll(()=>cast.evaluate((image:HTMLImageElement)=>image.complete&&image.naturalWidth===1774&&image.naturalHeight===887)).toBe(true);
 await expect(welcome.locator('.festival-loop-portrait img')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('sparkfest-welcome.png')});
 const help=page.getByRole('button',{name:'Read the welcome with help',exact:true});await help.scrollIntoViewIfNeeded();
 // Normalize Firefox fractional-geometry precision to 0.001 CSS pixels; keep the 48px minimum.
 expect(Math.round((await help.boundingBox())!.height*1000)/1000).toBeGreaterThanOrEqual(48);await help.click();const reader=page.locator('.garden-reader');await expect(page.getByRole('heading',{name:'SparkFest and Loop',exact:true})).toBeVisible();await expect(reader).toContainText('Jo · story writer');await expect(reader.getByRole('button',{name:'Hear SparkFest and Loop’s welcome',exact:true})).toBeVisible();await expect(reader.getByRole('button',{name:'Read SparkFest and Loop’s welcome aloud',exact:true})).toBeVisible();
 const helpCast=reader.locator('img[src="/art/sparkfest/cast-original.png"]');await expect(helpCast).toBeVisible();await expect.poll(()=>helpCast.evaluate((image:HTMLImageElement)=>image.complete&&image.naturalWidth===1774&&image.naturalHeight===887)).toBe(true);
 const word=reader.getByRole('button',{name:'projector',exact:true});await word.click();const card=page.getByRole('complementary',{name:'Word help: projector',exact:true});await expect(card).toBeVisible();const definition=card.locator(':scope > p').first();await expect(definition).toHaveText('A device that uses light to show pictures on a screen.');await expect(definition).not.toContainText(/unavailable|isn.t available|not available/i);await page.screenshot({path:info.outputPath('projector-word-help.png')});await page.getByRole('button',{name:'Close word help',exact:true}).click();await expect(word).toBeFocused();await reader.locator('.g-reader-top .g-close').click();await expect(help).toBeFocused();await expect(welcome).toBeVisible();
 await page.getByRole('button',{name:'Begin Pip’s adventure',exact:true}).click();await expect(page.getByRole('button',{name:'Start playing',exact:true})).toBeVisible();await expect(page.locator('.garden-passage')).toContainText('Grandma');await expect(page.locator('.garden-scene')).toHaveAttribute('data-chapter-phase','planning');await expect(page.getByRole('button',{name:'Watch the ending',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('garden-opening-after-festival.png')});
 await info.attach('scope',{body:'Ordinary fresh browser entry. Approved existing cast image URL and native decoded 1774×887 asset in the welcome and help reader, Loop identity, contextual word help, original introduction return focus and opening transition. No assertion of a playable festival map or a festival assignment for Pip.',contentType:'text/plain'});
});
