import {test,expect,type Page} from '@playwright/test';
import {completeConversation} from './garden-actions.js';
test.setTimeout(90000);
const button=(p:Page,name:string)=>p.getByRole('button',{name,exact:true});
async function begin(p:Page){await p.goto('/garden');await button(p,'Begin Pip’s adventure').click();await button(p,'Start playing').click();await button(p,'Go to Mara').click();await button(p,'Talk to Mara E').click();await completeConversation(p);}
async function saved(p:Page){await expect(p.locator('.g-save')).toHaveText('Saved in this browser');return p.evaluate(async()=>new Promise<any>(resolve=>{const r=indexedDB.open('evidence-quest-garden-adventure-v1');r.onsuccess=()=>{const db=r.result,t=db.transaction('slots'),q=t.objectStore('slots').get('current');t.oncomplete=()=>{db.close();resolve(q.result.payload);};};}));}

test('Reading support: inspect choices without selecting, then read every green reply with word help and oral practice',async({page},info)=>{
 // Synthetic local voice seam verifies exact speech requests, not audible voice quality.
 await page.addInitScript(()=>{const spoken:string[]=[];(window as any).__readingSpeech=spoken;Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[{localService:true,lang:'en-US'}],speak:(u:any)=>{spoken.push(u.text);u.onend?.();},cancel:()=>{}},configurable:true});Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class{constructor(public text:string){}},configurable:true});});
 await begin(page);const initial=await saved(page);
 await button(page,'Help me read these choices').click();const preview=page.getByRole('region',{name:'Read the choices before choosing'});
 await expect(preview).toContainText("I'll ask Grandma to start the next gathering later.");await preview.getByRole('button',{name:'gathering',exact:true}).click();await expect(page.getByRole('complementary',{name:'Word help: gathering'})).toContainText('people come together');await button(page,'Close word help').click();
 const inspected=await saved(page);expect(inspected.mara.asking).toBe(initial.mara.asking);expect(inspected.page).toBe(initial.page);expect(inspected.story).toEqual(initial.story);
 await button(page,"I'll ask Grandma to start the next gathering later.").click();
 const reply=page.locator('.g-dialogue-response').filter({has:page.locator('.g-speaker',{hasText:'Mara says'})});
 await reply.getByRole('button',{name:'Starting',exact:true}).click();await expect(page.getByRole('complementary',{name:'Word help: Starting'})).toContainText('Begin doing something');await button(page,'Hear the word').click();expect(await page.evaluate(()=>(window as any).__readingSpeech.at(-1))).toBe('Starting');await button(page,'Close word help').click();
 await button(page,'Hear Mara’s reply').click();const words='Please ask her. Starting after the last boat returns would give me time to finish work.';expect(await page.evaluate(()=>(window as any).__readingSpeech.at(-1))).toBe(words);
 await button(page,'Read Mara’s reply aloud').click();const practice=page.getByRole('dialog',{name:'Reading practice',exact:true});await expect(practice.locator('.g-practice-words')).toHaveText(words);await expect(practice).toHaveAttribute('data-recording','ready');await practice.getByRole('button',{name:'work',exact:true}).click();await expect(button(page,'Hear the sentence')).toBeVisible();await button(page,'Close word help').click();await expect(practice).toBeVisible();await button(page,'Back to the story').click();
 const after=await saved(page);expect(after.story.maraReported).toBe(false);expect(after.story.timeAgreed).toBe(null);expect(after.exposed.some((x:string)=>x.startsWith('GA.SRC.READING')||x.startsWith('GA.SRC.:'))).toBe(false);
 await page.screenshot({path:info.outputPath('supported-replies.png')});
});

test('Reading support: own message and compact choice help retain words, place and font size',async({page},info)=>{
 await begin(page);await button(page,"I'll ask Grandma to start the next gathering later.").click();await button(page,'Tell Grandma in your own words').click();const message='Mara needs to finish helping passengers. We could start the gathering later.';
 await page.getByLabel('Your message to Grandma',{exact:true}).fill(message);await page.getByText('Read my message before using it',{exact:true}).click();await button(page,'Read my message aloud').click();await expect(page.locator('.g-practice-words')).toHaveText(message);await button(page,'Back to the story').click();await button(page,'Use my message').click();await page.locator('blockquote').getByRole('button',{name:'passengers',exact:true}).click();await expect(page.getByRole('complementary',{name:'Word help: passengers'})).toContainText('travelling');await button(page,'Close word help').click();
 await page.getByRole('navigation',{name:'Reading tools'}).getByRole('button',{name:'Pause',exact:true}).click();await page.getByLabel('Largest reading text',{exact:true}).check();await page.getByLabel('More space between lines',{exact:true}).check();await button(page,'Back to Mara').click();await page.setViewportSize({width:320,height:568});await button(page,'Help me read these choices').click();const preview=page.getByRole('region',{name:'Read the choices before choosing'});await preview.getByRole('button',{name:'message',exact:true}).click();await expect(button(page,'Close word help')).toBeInViewport();await button(page,'Close word help').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect((await saved(page)).story.maraMessage.text).toBe(message);await page.screenshot({path:info.outputPath('compact-reading-help.png')});
});

test('Reading support: exact world controls can be inspected without placing a bridge section',async({page})=>{
 await page.goto('/garden');await button(page,'Begin Pip’s adventure').click();await button(page,'Start playing').click();await button(page,'Go to the bridge pieces').click();await button(page,'Arrange bridge').click();await button(page,'Narrow crossing · dock-side post').click();
 const before=await saved(page);await button(page,'Read what’s on screen').click();await expect(page.getByRole('heading',{name:'Read what’s on screen',exact:true})).toBeVisible();await expect(page.locator('.garden-reading-scroll')).toContainText('Place section');await page.locator('.garden-reading-scroll').getByRole('button',{name:'section',exact:true}).first().click();await button(page,'Close word help').click();await button(page,'Back to the bridge pieces').click();await expect(page.getByRole('button',{name:'Place section'})).toBeEnabled();expect((await saved(page)).sections).toEqual(before.sections);await page.getByRole('button',{name:'Place section'}).click();expect((await saved(page)).sections).not.toEqual(before.sections);
});

test('Reading support: synthetic capture keeps Stop visible and pauses replay before word help',async({page})=>{
 // Local microphone/AudioWorklet/playback seam; this proves input ownership, not device, decoder or acoustic accuracy.
 await page.addInitScript(()=>{
  const track={stop(){},addEventListener(){}};Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia:async()=>({getTracks:()=>[track],getAudioTracks:()=>[track]})},configurable:true});
  (window as any).AudioContext=class{sampleRate=16000;state='running';destination={};audioWorklet={addModule:async()=>{}};createMediaStreamSource(){return{connect(){}};}async resume(){}async close(){this.state='closed';}};
  (window as any).AudioWorkletNode=class{port:any={onmessage:null,postMessage:()=>{this.port.onmessage?.({data:{samples:new Float32Array(16000)}});this.port.onmessage?.({data:{done:true}});},close(){}};connect(){}disconnect(){}};
  HTMLMediaElement.prototype.play=async function(){this.setAttribute('data-synthetic-playing','true');};HTMLMediaElement.prototype.pause=function(){this.setAttribute('data-synthetic-playing','false');};
 });
 await begin(page);await button(page,"I'll ask Grandma to start the next gathering later.").click();await button(page,'Read Mara’s reply aloud').click();await button(page,'Start listening').click();const practice=page.getByRole('dialog',{name:'Reading practice',exact:true});await expect(practice).toHaveAttribute('data-recording','listening');await expect(practice.locator('.g-practice-words button')).toHaveCount(0);await expect(page.locator('#garden-reader-title')).toHaveAttribute('inert','');await expect(page.locator('.garden-tools')).toHaveAttribute('inert','');await expect(button(page,'Stop')).toBeVisible();await button(page,'Stop').click();await expect(practice).toHaveAttribute('data-recording','review');
 await practice.locator('audio').evaluate(async(el:HTMLAudioElement)=>{await el.play();});await practice.getByRole('button',{name:'work',exact:true}).click();await expect(practice.locator('audio')).toHaveAttribute('data-synthetic-playing','false');await expect(button(page,'Close word help')).toBeVisible();await button(page,'Close word help').click();await button(page,'Back to the story').click();
});

test('Reading support: long own writing is complete, bounded and resumes its reading page after reload',async({page})=>{
 await begin(page);await button(page,"I'll ask Grandma to start the next gathering later.").click();await button(page,'Tell Grandma in your own words').click();const message='Mara needs time to finish helping the passengers. '.repeat(140)+'This is the final sentence.';
 await page.getByLabel('Your message to Grandma',{exact:true}).fill(message);await page.getByText('Read my message before using it',{exact:true}).click();await button(page,'Read my message aloud').click();const first=await page.locator('.g-practice-words').textContent();await button(page,'Next reading page').click();const second=await page.locator('.g-practice-words').textContent();expect(second!.length).toBeLessThanOrEqual(1800);await button(page,'Back to the story').click();await saved(page);await page.reload();await button(page,'Talk to Mara E').click();await page.getByText('Read my message before using it',{exact:true}).click();await button(page,'Read my message aloud').click();await expect(page.locator('.g-reading-pages')).toContainText('Page 2 of');await expect(page.locator('.g-practice-words')).toHaveText(second!);await button(page,'Previous reading page').click();let collected=await page.locator('.g-practice-words').textContent();expect(collected).toBe(first);
 for(let i=0;i<30&&await button(page,'Next reading page').isEnabled();i++){await button(page,'Next reading page').click();collected+=(await page.locator('.g-practice-words').textContent())??'';}
 expect(collected).toBe(message);await button(page,'Back to the story').click();expect((await saved(page)).story.maraMessage.text).toBe(message);expect((await saved(page)).story.maraMessage.confirmed).toBe(false);
});
