import {test,expect,type Page} from '@playwright/test';
test.setTimeout(180000);
const button=(p:Page,name:string)=>p.getByRole('button',{name,exact:true});
async function begin(p:Page){await p.goto('/garden');await button(p,'Begin Pip’s adventure').click();await button(p,'Start playing').click();await button(p,'Go to the bridge pieces').click();await button(p,'Arrange bridge').click();await button(p,'Take the repair ropes').click();await expect(button(p,'Take the repair ropes')).toHaveCount(0);}
async function place(p:Page,section:'A'|'B',side:'dock'|'garden'){await p.locator('.g-select-sections').getByRole('button',{name:'Section '+section,exact:true}).press('Enter');await button(p,`Narrow crossing · ${side}-side post`).press('Enter');await p.getByRole('button',{name:'Place section'}).press('Enter');}
async function saved(p:Page){await expect(p.locator('.g-save')).toHaveText('Saved in this browser');return p.evaluate(async()=>new Promise<any>(resolve=>{const r=indexedDB.open('evidence-quest-garden-adventure-v1');r.onsuccess=()=>{const db=r.result,tx=db.transaction('slots'),q=tx.objectStore('slots').get('current');tx.oncomplete=()=>{db.close();resolve(q.result.payload);};};}));}
test('G3 ordinary controls: named placement, actual far-held collapse, reload, recovery and first garden context',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await begin(page);await place(page,'A','dock');await place(page,'B','garden');await button(page,'Join sections').click();await page.getByRole('button',{name:'Fasten garden-side end'}).click();await button(page,'Back to Pip').click();await button(page,'Try crossing the bridge').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-bridge-action','collapsing');await page.screenshot({path:info.outputPath('far-anchor-collapse.png')});await expect(page.locator('.garden-feedback')).toContainText('garden-side rope holds');
 const failed=await saved(page);expect(failed.east).toBe(true);expect(failed.west).toBe(false);expect(failed.joined).toBe(false);expect(failed.river.attachments.east).toBe('b');await page.reload();expect((await saved(page)).river.attachments.east).toBe('b');
 await button(page,'Go to the bridge pieces').click();await button(page,'Arrange bridge').click();await place(page,'A','dock');await button(page,'Join sections').click();await page.getByRole('button',{name:'Fasten dock-side end'}).click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-bridge-ready','true');await button(page,'Back to Pip').click();expect((await saved(page)).crossed).toBe(false);await button(page,'Go to Grandma').click();await button(page,'Talk to Grandma E').click();await expect(page.locator('.garden-reader')).toContainText('The two older lanterns hold stories');await expect(page.locator('.garden-reader')).toContainText('The other flowers can hold the new stories Mara, Sol and I share.');await page.getByRole('button',{name:'Plant the seed with Grandma'}).click();await expect(page.locator('.garden-feedback')).toContainText('kept his promise');const c=await saved(page);expect(c.history.filter((v:string)=>['B','P','L'].includes(v))).toEqual(['B','P','L']);expect(c.river.soilPrepared).toBe(true);expect(errors).toEqual([]);await page.screenshot({path:info.outputPath('garden-arrival.png')});
});
test('G3 ordinary boat controls: loaded cargo, wrong dock, pause/reload, player steering and explicit receipt',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await begin(page);await button(page,'Back to Pip').click();await button(page,'Read the note').click();await button(page,'Load the seed into the boat').click();await expect(button(page,'Launch the seed boat')).toBeVisible();await button(page,'Launch the seed boat').click();await button(page,'Try docking at Grandma’s landing').click();await expect(page.locator('.garden-feedback')).toContainText('Grandma can reach the boat at her blue landing');
 await page.setViewportSize({width:320,height:568});
 const canvas=await page.locator('.garden-scene canvas').boundingBox();expect(canvas?.width).toBeGreaterThan(200);expect(canvas?.height).toBeGreaterThanOrEqual(140);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect((await button(page,'Upstream ↑').boundingBox())?.height).toBeGreaterThanOrEqual(48);
 await page.screenshot({path:info.outputPath('compact-boat.png')});
 await button(page,'Help').click();await expect(page.locator('.garden-reader')).toBeVisible();await button(page,'Back to the seed boat').click();
 await button(page,'Upstream ↑').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-z','0.250');await button(page,'Garden side →').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-x','-0.850');await button(page,'Pause').click();const paused=await saved(page);expect(paused.seed).toBe('boat');await page.getByLabel('Reduced motion',{exact:true}).check();await button(page,'Back to the seed boat').click();await page.reload();const restored=await saved(page);expect(restored.river.boat.position).toEqual(paused.river.boat.position);expect(restored.history.includes('F')).toBe(false);await page.screenshot({path:info.outputPath('boat-paused-cargo.png')});
 await page.setViewportSize({width:1440,height:1000});
 for(const x of [-.3,.25,.8,1.35]){await button(page,'Garden side →').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-x',x.toFixed(3));}
 await button(page,'Downstream ↓').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-z','0.800');expect((await saved(page)).seed).toBe('boat');await button(page,'Give the seed to Grandma').click();await expect(page.locator('.garden-feedback')).toContainText('Grandma takes the seed');const end=await saved(page);expect(end.seed).toBe('grandma');expect(end.river.boat.position).toEqual({x:1.4,z:.8});expect(end.river.soilPrepared).toBe(true);expect(end.history.filter((v:string)=>v==='F')).toHaveLength(1);expect(end.pip).toEqual(paused.pip);expect(errors).toEqual([]);await page.screenshot({path:info.outputPath('received-seed.png')});
});
