import {buildStagedBridge} from './garden-actions.js';
import {openDirections} from './garden-actions.js';
import {test,expect,type Page} from '@playwright/test';
import {completeConversation} from './garden-actions.js';
test.setTimeout(180000);
const button=(p:Page,name:string)=>p.getByRole('button',{name,exact:true});
async function saved(p:Page){await expect(p.locator('.g-save')).toHaveText('Saved in this browser');return p.evaluate(async()=>new Promise<any>(resolve=>{const r=indexedDB.open('evidence-quest-garden-adventure-v1');r.onsuccess=()=>{const db=r.result,t=db.transaction('slots'),q=t.objectStore('slots').get('current');t.oncomplete=()=>{db.close();resolve(q.result.payload);};};}));}
async function begin(p:Page){await p.goto('/garden');await button(p,'Begin Pip’s adventure').click();await button(p,'Start playing').click();await button(p,'Go to Mara').click();await button(p,'Talk to Mara E').click();await completeConversation(p);}
async function grandma(p:Page){
 await button(p,'Continue to the game').click();await buildStagedBridge(p);await button(p,'Go to Grandma').click();await button(p,'Talk to Grandma E').click();
}
for(const mode of ['prepared','own'] as const)test('Conversation sequence: '+mode+' relay advances, persists, and is delivered at Grandma',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await begin(page);
 await button(page,"I'll ask Grandma to start the next gathering later.").click();
 const flow=page.locator('.garden-reading-scroll'),footer=page.locator('.g-reader-actions');
 await expect(flow.locator('.g-speaker')).toHaveText(['Pip says','Mara says']);await expect(flow).toContainText('Starting after the last boat returns');await expect(button(page,'I can read your story to Grandma.')).toHaveCount(0);await expect(page.locator('#mara-message')).toHaveCount(0);await expect(page.locator('textarea:visible')).toHaveCount(0);await expect(page.getByLabel('Your answer, in your own words',{exact:true})).toBeHidden();await expect(footer.locator('.g-dialogue-response,.g-choices')).toHaveCount(0);
 await expect(flow.getByRole('group',{name:'How will you carry Mara’s message?'}).locator('.g-choice-select > span:first-child')).toHaveText(['Let Grandma know what Mara said','Tell Grandma in your own words']);await page.screenshot({path:info.outputPath('01-next-choices-together.png')});
 const bounds=await flow.boundingBox(),nav=await footer.boundingBox();expect(nav!.y-(bounds!.y+bounds!.height)).toBeLessThan(12);expect(await footer.evaluate(e=>e.scrollHeight-e.clientHeight)).toBeLessThanOrEqual(1);
 await button(page,mode==='own'?'Tell Grandma in your own words':'Let Grandma know what Mara said').click();const words='Mara wants to hear the stories. She has to finish helping passengers after the last boat. Can we meet then?';
 if(mode==='own'){
  const message=page.getByLabel('Your message to Grandma',{exact:true});await message.fill(words);await expect(message).toBeFocused();await page.getByRole('navigation',{name:'Reading tools'}).getByRole('button',{name:'Help',exact:true}).click();await button(page,'Back to Mara').click();await expect(message).toHaveValue(words);await expect(page.getByRole('navigation',{name:'Reading tools'}).getByRole('button',{name:'Help',exact:true})).toBeFocused();await button(page,'Use my message').click();await expect(page.getByRole('heading',{name:'At Mara’s dock'})).toBeFocused();await button(page,'Change the message').click();await expect(message).toHaveValue(words);await saved(page);await page.reload();await button(page,'Talk to Mara E').click();await expect(message).toHaveValue(words);await button(page,'Use my message').click();
 }
 const ready=await saved(page);expect(ready.story.maraMessage.confirmed).toBe(true);expect(ready.story.maraMessage.delivered).toBe(null);expect(ready.story.maraReported).toBe(false);expect(ready.story.timeAgreed).toBe(null);expect(ready.page).toBe('mara');await page.screenshot({path:info.outputPath('02-message-ready-not-delivered.png')});
 await grandma(page);await button(page,'Tell Grandma what Mara said').click();await expect(button(page,'Tell Grandma')).toBeVisible();expect((await saved(page)).story.maraReported).toBe(false);await button(page,'Tell Grandma').click();
 const delivered=await saved(page);expect(delivered.story.maraReported).toBe(true);expect(delivered.story.timeAgreed).toBe(null);expect(delivered.story.maraMessage.delivered).toEqual({mode,text:ready.story.maraMessage.text});await expect(flow.locator('.g-dialogue-response').first()).toContainText(ready.story.maraMessage.text);await expect(flow.locator('[data-source-component^="GA.SRC.REPORT"]')).toHaveCount(0);
 if(mode==='own'){await expect(flow.locator('.g-remembered-account')).toContainText('Mara’s words at the dock');await expect(flow.locator('.g-dialogue-response').first()).toContainText(words);}
 await expect(footer.locator('.g-dialogue-response,.g-choices')).toHaveCount(0);await page.screenshot({path:info.outputPath('03-delivered-conversation.png')});await button(page,'Let’s start after the last boat returns.').click();expect((await saved(page)).story.timeAgreed).toBe('later');await expect(button(page,'Let’s start after the last boat returns.')).toHaveCount(0);expect(errors).toEqual([]);
});
test('Conversation sequence: largest text keeps one scroll, adjacent navigation and an optional own-message editor',async({page},info)=>{
 await begin(page);await button(page,"I'll ask Grandma to start the next gathering later.").click();await page.getByRole('navigation',{name:'Reading tools'}).getByRole('button',{name:'Pause',exact:true}).click();await page.getByLabel('Largest reading text',{exact:true}).check();await page.getByLabel('More space between lines',{exact:true}).check();await button(page,'Back to Mara').click();await page.setViewportSize({width:320,height:568});
 const flow=page.locator('.garden-reading-scroll'),footer=page.locator('.g-reader-actions');expect((await flow.boundingBox())!.height).toBeGreaterThanOrEqual(220);expect(await flow.locator('.g-dialogue-response').first().evaluate(e=>getComputedStyle(e).fontSize)).toBe('28px');
 await button(page,'Tell Grandma in your own words').scrollIntoViewIfNeeded();await expect(button(page,'Tell Grandma in your own words')).toBeInViewport();await page.screenshot({path:info.outputPath('compact-current-choices.png')});await button(page,'Tell Grandma in your own words').click();await page.getByLabel('Your message to Grandma',{exact:true}).fill('She needs to finish helping passengers.');await button(page,'Use my message').scrollIntoViewIfNeeded();await expect(button(page,'Use my message')).toBeInViewport();await button(page,'Use my message').click();await expect(button(page,'Continue to the game')).toBeInViewport();expect(await footer.evaluate(e=>e.scrollHeight-e.clientHeight)).toBeLessThanOrEqual(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('compact-ready-message.png')});
});
