import {completeConversation} from './garden-actions.js';
import {test,expect,type Page,type TestInfo} from '@playwright/test';
import {OrthographicCamera,Vector3} from 'three';
import {checksum} from '../src/garden/persistence.js';
const DB='evidence-quest-garden-adventure-v1';
test.use({video:{mode:'on',size:{width:1440,height:1000}}});
test.describe('First Garden Adventure encounter',()=>{
 test.setTimeout(240000);
 async function capture(page:Page,info:TestInfo,name:string){await expect.poll(()=>page.locator('.garden-scene').evaluate(e=>{const canvas=e.querySelector('canvas')!;return Number((e as HTMLElement).dataset['renderedWidth'])===canvas.width&&Number((e as HTMLElement).dataset['renderedHeight'])===canvas.height;})).toBe(true);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await page.screenshot({path:info.outputPath(name)});}
 async function begin(page:Page){await page.goto('/garden');await page.getByRole('button',{name:'Begin Pip’s adventure',exact:true}).click();await page.getByRole('button',{name:'Start playing',exact:true}).click();}
 async function save(page:Page):Promise<any>{await expect(page.locator('.g-save')).toHaveText('Saved in this browser');return page.evaluate(async name=>new Promise((resolve,reject)=>{const req=indexedDB.open(name,1);req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result,tx=db.transaction('slots'),r=tx.objectStore('slots').get('current');tx.oncomplete=()=>{db.close();resolve(r.result);};};}),DB);}
 async function pageFromMara(page:Page){await page.getByRole('button',{name:'Go to Mara',exact:true}).click();await page.getByRole('button',{name:'Talk to Mara E',exact:true}).click();await completeConversation(page);await page.getByRole('button',{name:'I can read your story to Grandma.',exact:true}).click();await expect(page.locator('.garden-reading-scroll')).toContainText('Pip is carrying her copy.');await page.getByRole('button',{name:'Back to Pip',exact:true}).click();}
 async function sections(page:Page){await page.getByRole('button',{name:'Go to the bridge pieces',exact:true}).click();await expect(page.getByRole('button',{name:'Arrange bridge',exact:true})).toBeVisible();}
 async function xy(page:Page,x:number,z:number,y=.13){const box=(await page.locator('.garden-scene canvas').boundingBox())!;const aspect=box.width/box.height,h=Math.max(6.5,10.2/aspect),camera=new OrthographicCamera(-h*aspect,h*aspect,h,-h,.1,100);camera.position.set(8.75,16,19.1);camera.lookAt(1.25,0,.1);camera.updateMatrixWorld();const p=new Vector3(x,y,z).project(camera);return {x:box.x+(p.x*.5+.5)*box.width,y:box.y+(-p.y*.5+.5)*box.height};}
 async function place(page:Page,id:'A'|'B',x:number,z:number){await page.locator('.g-select-sections').getByRole('button',{name:'Section '+id,exact:true}).click();const p=await xy(page,x,z);await page.mouse.click(p.x,p.y);}
 async function joinAt(page:Page,z=3,center=0){await page.getByRole('button',{name:'Arrange bridge',exact:true}).click();{const ropeButton=page.getByRole('button',{name:'Take the repair ropes',exact:true});if(await ropeButton.count()){await ropeButton.click();await expect(ropeButton).toHaveCount(0);}}await place(page,'A',center-.775,z);await place(page,'B',center+.775,z);await page.getByRole('button',{name:'Join sections',exact:true}).click();await expect(page.getByRole('button',{name:'Sections joined',exact:true})).toBeVisible();}
 async function fasten(page:Page){for(const name of ['Fasten dock-side end','Fasten garden-side end']){const control=page.getByRole('button',{name,exact:false});if(!await control.isDisabled())await control.click();}await expect(page.locator('.garden-scene')).toHaveAttribute('data-bridge-ready','true');await page.getByRole('button',{name:'Back to Pip',exact:true}).click();}
 async function steerDelivery(page:Page){await page.getByRole('button',{name:'Launch the seed boat',exact:true}).click();await page.getByRole('button',{name:'Upstream ↑',exact:true}).click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-z','0.250');for(const x of [-.85,-.3,.25,.8,1.35]){await page.getByRole('button',{name:'Garden side →',exact:true}).click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-x',x.toFixed(3));}await page.getByRole('button',{name:'Downstream ↓',exact:true}).click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-z','0.800');}
 async function finish(page:Page){await page.getByRole('button',{name:'Go to Grandma',exact:true}).click();await page.getByRole('button',{name:'Talk to Grandma E',exact:true}).click();await page.getByRole('button',{name:'Plant the seed with Grandma',exact:false}).click();await expect(page.locator('.garden-status')).toContainText('kept his promise');await page.getByRole('button',{name:'Talk to Grandma E',exact:true}).click();await page.getByRole('button',{name:'Give Grandma Mara’s page',exact:false}).click();await expect(page.getByRole('heading',{name:'Tell Grandma what you learned',exact:true})).toBeVisible();await page.getByRole('button',{name:'Let Pip explain',exact:true}).click();await page.getByRole('button',{name:'Read The Torn Wing',exact:false}).click();await expect(page.getByRole('heading',{name:'The Torn Wing',exact:true})).toBeVisible();}
 test('carried-seed route: real placement, reading, page/report, return and legacy-save isolation',async({page},info)=>{
  const errors:string[]=[],requests:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
  await page.goto('/garden');
  // Synthetic legacy save sentinel: isolation evidence only, not a valid legacy route.
  await page.evaluate(async()=>new Promise<void>(resolve=>{const r=indexedDB.open('evidence-quest',1);r.onupgradeneeded=()=>r.result.createObjectStore('caseSlots');r.onsuccess=()=>{const db=r.result,t=db.transaction('caseSlots','readwrite');t.objectStore('caseSlots').put('PRESERVE-LEGACY-SENTINEL','current');t.oncomplete=()=>{db.close();resolve();};};}));
  await page.getByRole('button',{name:'Begin Pip’s adventure',exact:true}).click();await page.getByRole('button',{name:'Start playing',exact:true}).click();
  await page.getByRole('button',{name:'Go to Mara',exact:true}).click();await page.getByRole('button',{name:'Talk to Mara E',exact:true}).click();await completeConversation(page);
  const choices=await Promise.all(['I can read your story to Grandma.',"I'll ask Grandma to start the next gathering later."].map(name=>page.getByRole('button',{name,exact:true}).evaluate(e=>({height:e.getBoundingClientRect().height,width:e.getBoundingClientRect().width,background:getComputedStyle(e).backgroundColor,fontSize:getComputedStyle(e).fontSize}))));
  expect(choices[0]!.width).toBe(choices[1]!.width);for(const choice of choices){expect(choice.height).toBeGreaterThanOrEqual(48);expect(choice.background).not.toBe('rgba(0, 0, 0, 0)');expect(parseFloat(choice.fontSize)).toBeGreaterThanOrEqual(16);}expect(choices[0]!.background).not.toBe(choices[1]!.background);
  await page.getByRole('button',{name:"I'll ask Grandma to start the next gathering later.",exact:true}).click();await expect(page.locator('.g-dialogue-response')).toContainText('give me time to finish work');await capture(page,info,'visible-story-choices.png');
  const before=await save(page);await page.getByRole('button',{name:'obligation',exact:true}).click();await expect(page.getByRole('complementary',{name:'Word help: obligation'})).toContainText('responsibility');
  await page.keyboard.press('ArrowRight');const after=await save(page);expect(after.payload.pip).toEqual(before.payload.pip);
  await capture(page,info,'word-help.png');await page.getByRole('button',{name:'Close word help'}).click();await expect(page.getByRole('button',{name:'obligation',exact:true})).toBeFocused();
  await page.getByRole('button',{name:'I can read your story to Grandma.',exact:true}).click();await expect(page.locator('.garden-reading-scroll')).toContainText('Pip is carrying her copy.');await page.getByRole('button',{name:'Back to Pip',exact:true}).click();
  await sections(page);await joinAt(page);await fasten(page);const bridge=await save(page);expect(bridge.payload.crossed).toBe(false);expect(bridge.payload.page).toBe('pip');
  await capture(page,info,'crossing.png');await page.reload();await expect(page.locator('.garden-scene')).toHaveAttribute('data-bridge-ready','true');await finish(page);
  const end=await save(page);expect(end.payload.seed).toBe('soil');expect(end.payload.bloomed).toBe(true);expect(end.payload.page).toBe('grandma');expect(end.payload.grandmaHeard).toBe(true);expect(end.payload.history.filter((h:string)=>['F','B','P','L'].includes(h))).toEqual(['B','P','L']);
  await capture(page,info,'mara-story.png');for(let depth=0;depth<20&&await page.locator('.garden-reader').count();depth++)await page.locator('.garden-reader .g-reader-top .g-close').click();await expect(page.locator('.garden-reader')).toHaveCount(0);await expect(page.locator('.garden-scene')).toHaveAttribute('data-rendered-view','walk');await capture(page,info,'planted-garden.png');
  await page.locator('.garden-access>summary').click();await page.locator('.garden-access').getByRole('button',{name:'Go to Mara',exact:true}).click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-pip-x',/-3\.500/);await expect(page.getByRole('button',{name:'Talk to Mara E',exact:true})).toBeVisible();
  const legacy=await page.evaluate(async()=>new Promise(resolve=>{const r=indexedDB.open('evidence-quest',1);r.onsuccess=()=>{const db=r.result,t=db.transaction('caseSlots'),q=t.objectStore('caseSlots').get('current');t.oncomplete=()=>{db.close();resolve(q.result);};};}));expect(legacy).toBe('PRESERVE-LEGACY-SENTINEL');expect(errors).toEqual([]);expect(requests.filter(u=>/\/api\//.test(u))).toEqual([]);
  await info.attach('ending-state',{body:JSON.stringify(end,null,2),contentType:'application/json'});
  // The first leg is no longer chapter completion. Restart remains available through Pause.
  expect(end.payload.story.ending).toBeNull();await page.getByRole('button',{name:'Pause',exact:true}).click();
  const replay=page.getByRole('button',{name:'Start a new adventure',exact:true});await expect(replay).toBeInViewport();page.once('dialog',d=>d.dismiss());await replay.click();expect((await save(page)).payload.runId).toBe(end.payload.runId);
  await capture(page,info,'replay-mid-chapter.png');page.once('dialog',d=>d.accept());await replay.click();await expect(page.getByRole('button',{name:'Begin Pip’s adventure',exact:true})).toBeVisible();const fresh=await save(page);expect(fresh.payload.runId).not.toBe(end.payload.runId);expect(fresh.payload.seed).toBe('pip');expect(fresh.payload.page).toBe('mara');expect(fresh.payload.bloomed).toBe(false);expect(fresh.payload.joined).toBe(false);await capture(page,info,'fresh-adventure.png');
  const archivedEnd=await page.evaluate(async name=>new Promise<any[]>(resolve=>{const r=indexedDB.open(name,1);r.onsuccess=()=>{const db=r.result,t=db.transaction('slots'),s=t.objectStore('slots'),keys=s.getAllKeys(),values=s.getAll();t.oncomplete=()=>{db.close();resolve(values.result.filter((_,i)=>String(keys.result[i]).startsWith('archive-')));};};}),DB);expect(archivedEnd.some(row=>row.payload.runId===end.payload.runId&&row.payload.bloomed&&row.payload.page==='grandma')).toBe(true);
 });
 test('seed first: separate boat trip, fixed bridge pieces, real drag, wide gap and full report',async({page},info)=>{
  await begin(page);await pageFromMara(page);await sections(page);const start=await save(page);
  await expect(page.getByRole('button',{name:'Seed boat',exact:true})).toBeVisible();await capture(page,info,'separate-boat-and-bridge-pieces.png');
  await page.getByRole('button',{name:'Read the note',exact:true}).click();await expect(page.getByRole('heading',{name:'The boat and the broken bridge',exact:true})).toBeVisible();await page.getByRole('button',{name:'Load the seed into the boat',exact:true}).click();
  const scene=page.locator('.garden-scene');await steerDelivery(page);await expect(scene).toHaveAttribute('data-ferry-phase','steering');await page.screenshot({path:info.outputPath('seed-boat-crossing-water.png'),animations:'disabled'});
  const sailing=await scene.evaluate(e=>({...((e as HTMLElement).dataset)}));expect(Number(sailing['seedBoatZ'])).toBe(.8);expect(Math.abs(Number(sailing['seedX'])-Number(sailing['seedBoatX']))).toBeLessThan(.02);expect(Math.abs(Number(sailing['seedZ'])-.8)).toBeLessThan(.02);expect(JSON.parse(sailing['renderedSections']!)).toEqual(start.payload.sections);
  expect(Number(sailing['seedBoatX'])).toBeGreaterThan(-1.4);expect(Number(sailing['seedBoatX'])).toBeLessThan(1.4);expect(Number(sailing['pipX'])).toBeCloseTo(start.payload.pip.x,2);expect(Number(sailing['pipZ'])).toBeCloseTo(start.payload.pip.z,2);await info.attach('actual-sailing-transforms',{body:JSON.stringify(sailing,null,2),contentType:'application/json'});
  await page.getByRole('button',{name:'Give the seed to Grandma',exact:true}).click();await expect(page.locator('.garden-status')).toContainText('Grandma takes the seed');const ferried=await save(page);expect(ferried.payload.pip).toEqual(start.payload.pip);expect(ferried.payload.seed).toBe('grandma');expect(ferried.payload.ferrySide).toBe('east');expect(ferried.payload.sections).toEqual(start.payload.sections);expect(ferried.payload.page).toBe(start.payload.page);await expect(scene).toHaveAttribute('data-seed-boat-x','1.400');await capture(page,info,'seed-delivered-bridge-unmoved.png');
  await joinAt(page,-2,-.8);await page.getByRole('button',{name:'Fasten dock-side end',exact:false}).click();await page.getByRole('button',{name:'Fasten garden-side end',exact:false}).click();await expect(page.locator('.garden-status')).toContainText("This end doesn't reach the bank yet");await capture(page,info,'wide-gap.png');
  const beforeHint=await save(page);await page.getByRole('button',{name:'Give me a hint',exact:true}).click();await expect(page.locator('.garden-status')).toContainText('Hint');await expect(page.locator('.garden-status')).toContainText('banks are closer together');const afterHint=await save(page);expect(afterHint.payload.sections).toEqual(beforeHint.payload.sections);expect(afterHint.payload.pip).toEqual(beforeHint.payload.pip);expect(afterHint.payload.exposed).toEqual(beforeHint.payload.exposed);
  const hintBox=(await page.locator('.garden-status').boundingBox())!,sceneBox=(await page.locator('.garden-scene').boundingBox())!;expect(hintBox.y+hintBox.height).toBeLessThanOrEqual(sceneBox.y+1);await expect(page.locator('.garden-status[role=status]')).toHaveCount(1);await capture(page,info,'visible-crossing-hint.png');
  await page.getByRole('button',{name:'Release ropes to move sections',exact:true}).click();
  // Pointer drag on actual rendered Section A, maintaining its pointer offset.
  const from=await xy(page,-1.575,-2,.15),to=await xy(page,-.775,3,.15);await page.mouse.move(from.x+6,from.y+10);await page.mouse.down();await page.mouse.move(to.x+6,to.y+10,{steps:30});await page.mouse.up();
  await page.getByRole('button',{name:'Fasten dock-side end',exact:false}).click();await expect(page.locator('.garden-status')).toContainText('an end is loose');await page.getByRole('button',{name:'Back to Pip',exact:true}).click();await page.locator('.garden-access>summary').click();await page.locator('.garden-access').getByRole('button',{name:'Go to Grandma',exact:true}).click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-bridge-action','collapsing');await expect(page.locator('.garden-status')).toContainText('Recover the same pieces');await page.locator('.garden-access>summary').click();expect((await save(page)).payload.story.bridgeFailures).toBe(1);
  await sections(page);await joinAt(page);await fasten(page);await finish(page);const end=await save(page);expect(end.payload.history.filter((h:string)=>['F','B','P','L'].includes(h))).toEqual(['F','B','P','L']);expect(end.payload.page).toBe('grandma');await info.attach('seed-first-ending',{body:JSON.stringify(end,null,2),contentType:'application/json'});
 });
 test('version-1 upgrade archives the exact save and keeps the bridge fixed during a boat trip',async({page},info)=>{
  await begin(page);await pageFromMara(page);await sections(page);await joinAt(page);await fasten(page);await page.getByRole('button',{name:'Pause',exact:true}).click();const before=await save(page);
  // Synthetic old-format disk record; the real previous-format decoder, upgrade and IndexedDB transaction run below.
  const payload=structuredClone(before.payload);payload.boats=payload.sections;delete payload.sections;delete payload.ferrySide;payload.version=1;payload.content='garden-encounter-1';payload.exposed=payload.exposed.filter((id:string)=>!id.startsWith('GA.SRC.SECTIONS.'));payload.exposed.push('GA.SRC.BOATS.1','GA.SRC.BOATS.1.W1');payload.reading.boats=84;
  const legacy={...before,revision:before.revision+1,writer:'synthetic-prior-client',content:'garden-encounter-1',payload,checksum:checksum(JSON.stringify(payload))};
  await page.evaluate(async({name,record})=>new Promise<void>(resolve=>{const r=indexedDB.open(name,1);r.onsuccess=()=>{const db=r.result,t=db.transaction('slots','readwrite');t.objectStore('slots').put(record,'current');t.oncomplete=()=>{db.close();resolve();};};}),{name:DB,record:legacy});
  await page.reload();const upgraded=await save(page);expect(upgraded.content).toBe('garden-chapter-3');expect(upgraded.payload.version).toBe(3);expect(upgraded.payload.runId).toBe(payload.runId);expect(upgraded.payload.pip).toEqual(payload.pip);expect(upgraded.payload.page).toBe(payload.page);expect(upgraded.payload.seed).toBe(payload.seed);expect(upgraded.payload.history).toEqual(payload.history);expect(upgraded.payload.sections).toEqual(payload.boats);expect(upgraded.payload.ferrySide).toBe('west');expect(upgraded.payload.exposed.some((id:string)=>/GA.SRC.(BOATS|SECTIONS)\./.test(id))).toBe(false);
  await expect(page.locator('.garden-scene')).toHaveAttribute('data-bridge-ready','true');expect(upgraded.payload.crossed).toBe(false);
  const archived=await page.evaluate(async({name,key})=>new Promise(resolve=>{const r=indexedDB.open(name,1);r.onsuccess=()=>{const db=r.result,t=db.transaction('slots'),q=t.objectStore('slots').get(key);t.oncomplete=()=>{db.close();resolve(q.result);};};}),{name:DB,key:'archive-v1-'+payload.runId+'-'+legacy.revision});expect(archived).toEqual(legacy);
  await page.getByRole('button',{name:'Read the note',exact:true}).click();const ferry=page.getByRole('button',{name:'Load the seed into the boat',exact:true});await expect(ferry).toBeEnabled();await ferry.click();await steerDelivery(page);await expect(page.locator('.garden-scene')).toHaveAttribute('data-ferry-phase','steering');await capture(page,info,'seed-boat-beside-fastened-footbridge.png');
  await page.getByRole('button',{name:'Give the seed to Grandma',exact:true}).click();await expect(page.locator('.garden-status')).toContainText('Grandma takes the seed');const after=await save(page);expect(after.payload.sections).toEqual(payload.boats);expect(after.payload.pip).toEqual(payload.pip);expect(after.payload.crossed).toBe(false);expect(after.payload.seed).toBe('grandma');await expect(page.locator('.garden-scene')).toHaveAttribute('data-bridge-ready','true');
  await info.attach('save-upgrade',{body:JSON.stringify({before:legacy,upgraded,archived,after},null,2),contentType:'application/json'});
 });
 test('keyboard construction, reading focus, largest text and compact layouts',async({page},info)=>{
  await begin(page);await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByLabel('Reduced motion',{exact:true}).check();await page.getByRole('button',{name:'Back to Pip',exact:true}).click();await pageFromMara(page);await sections(page);await page.getByRole('button',{name:'Arrange bridge',exact:true}).click();{const ropeButton=page.getByRole('button',{name:'Take the repair ropes',exact:true});if(await ropeButton.count()){await ropeButton.click();await expect(ropeButton).toHaveCount(0);}}await expect(page.locator('.garden-scene')).toHaveAttribute('data-rendered-view','arrange');
  await page.locator('.g-select-sections').getByRole('button',{name:'Section A',exact:true}).click();for(let i=0;i<28;i++)await page.keyboard.press('ArrowRight');for(let i=0;i<20;i++)await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
  await page.locator('.g-select-sections').getByRole('button',{name:'Section B',exact:true}).click();for(let i=0;i<44;i++)await page.keyboard.press('ArrowRight');for(let i=0;i<5;i++)await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
  await page.getByRole('button',{name:'Join sections',exact:true}).click();await fasten(page);
  await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByLabel('Largest reading text',{exact:true}).check();await page.getByLabel('More space between lines',{exact:true}).check();await page.getByRole('button',{name:'Back to Pip',exact:true}).click();await page.getByRole('button',{name:'Help',exact:true}).click();await page.getByRole('button',{name:'Reread Mara’s account',exact:true}).click();
  for(const size of [{width:1440,height:900},{width:800,height:800},{width:390,height:844},{width:320,height:568}]){
   await page.setViewportSize(size);await expect(page.getByRole('heading',{name:"Mara's story can travel",exact:true})).toBeVisible();await page.getByRole('button',{name:'obligation',exact:true}).click();const card=page.getByRole('complementary',{name:'Word help: obligation'});await expect(card).toBeVisible();
   const widths=await page.locator('.garden-reading-scroll').evaluate(e=>({w:e.clientWidth,scroll:e.scrollWidth,h:e.clientHeight}));expect(widths.scroll).toBeLessThanOrEqual(widths.w+1);expect(widths.h).toBeGreaterThan(60);for(const height of await card.locator('button.g-secondary').evaluateAll(buttons=>buttons.map(button=>button.getBoundingClientRect().height)))expect(height).toBeGreaterThanOrEqual(48);
   await capture(page,info,`reader-${size.width}-${size.height}.png`);await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'obligation',exact:true})).toBeFocused();
  }
  await page.getByRole('button',{name:'Back to Help',exact:true}).click();await page.getByRole('button',{name:'Back to Pip',exact:true}).click();await page.getByRole('button',{name:'Arrange bridge',exact:true}).click();{const ropeButton=page.getByRole('button',{name:'Take the repair ropes',exact:true});if(await ropeButton.count()){await ropeButton.click();await expect(ropeButton).toHaveCount(0);}}await page.getByRole('button',{name:'Give me a hint',exact:true}).click();await expect(page.locator('.garden-status')).toContainText('Both ends are secure');await expect(page.locator('.garden-feedback-content')).toHaveCSS('animation-name','none');
  const compact=await page.locator('.garden-app').evaluate(e=>({width:e.clientWidth,scrollWidth:e.scrollWidth,height:e.clientHeight,scrollHeight:e.scrollHeight}));expect(compact.scrollWidth).toBeLessThanOrEqual(compact.width+1);expect(compact.scrollHeight).toBeLessThanOrEqual(compact.height+1);await capture(page,info,'compact-crossing-hint.png');
  const places=(await page.locator('.garden-access>summary').boundingBox())!,builder=(await page.locator('.garden-builder').boundingBox())!;expect(places.y+places.height).toBeLessThanOrEqual(builder.y);await page.locator('.garden-access>summary').click();await page.locator('.garden-access').getByRole('button',{name:'Go to Mara',exact:true}).scrollIntoViewIfNeeded();await expect(page.locator('.garden-access').getByRole('button',{name:'Go to Mara',exact:true})).toBeInViewport();
  await page.getByRole('button',{name:'Pause',exact:true}).click();await expect(page.getByRole('button',{name:'Start a new adventure',exact:true})).toBeInViewport();await expect(page.getByRole('button',{name:'Back to the bridge pieces',exact:true})).toBeInViewport();await capture(page,info,'compact-pause-restart.png');
 });
 test('damaged-current recovery preserves previous save; archive preserves original state',async({page},info)=>{
  await begin(page);await pageFromMara(page);await sections(page);const current=await save(page);
  // Labeled synthetic disk corruption, followed by the actual boot/restore UI.
  await page.evaluate(async name=>new Promise<void>(resolve=>{const r=indexedDB.open(name,1);r.onsuccess=()=>{const db=r.result,t=db.transaction('slots','readwrite'),s=t.objectStore('slots'),q=s.get('current');q.onsuccess=()=>{s.put(q.result,'previous');s.put({...q.result,checksum:'damaged'},'current');};t.oncomplete=()=>{db.close();resolve();};};}),DB);
  await page.reload();await expect(page.getByRole('alert')).toContainText('latest save could not be read');await page.getByRole('button',{name:'Restore previous save'}).click();const restored=await save(page);expect(restored.payload).toEqual(current.payload);
  await page.getByRole('button',{name:'Pause',exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Start a new adventure',exact:true}).click();await expect(page.getByRole('button',{name:'Begin Pip’s adventure',exact:true})).toBeVisible();const fresh=await save(page);expect(fresh.payload.runId).not.toBe(current.payload.runId);
  const archive=await page.evaluate(async name=>new Promise<any[]>(resolve=>{const r=indexedDB.open(name,1);r.onsuccess=()=>{const db=r.result,t=db.transaction('slots'),s=t.objectStore('slots'),keys=s.getAllKeys(),rows=s.getAll();t.oncomplete=()=>{db.close();resolve(keys.result.map((key,i)=>({key,value:rows.result[i]})));};};}),DB);expect(archive.some(row=>String(row.key).startsWith('archive-')&&row.value.payload.runId===current.payload.runId)).toBe(true);await info.attach('recovery',{body:JSON.stringify({previous:current.payload.runId,new:fresh.payload.runId,archiveCount:archive.filter(r=>String(r.key).startsWith('archive-')).length}),contentType:'application/json'});
 });
 test('two windows reject stale saves and archive, then load the actual latest progress',async({page,context})=>{
  await begin(page);await save(page);const second=await context.newPage();await second.goto('/garden');await second.getByRole('button',{name:'Pause',exact:true}).click();await second.getByLabel('Reduced motion',{exact:true}).check();await save(second);await page.bringToFront();await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByLabel('Larger reading text',{exact:true}).check();await expect(page.getByRole('alert')).toContainText('Another window has newer progress');
  page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Start a new adventure',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Another window has newer progress');
  await page.getByRole('button',{name:'Load latest progress'}).click();await expect(page.getByRole('alert')).toHaveCount(0);expect((await save(page)).payload.started).toBe(true);await second.close();
 });
 test('WebGL context-loss recovery and measured rendering retain actual save',async({page},info)=>{
  await begin(page);await pageFromMara(page);const before=await save(page);
  // Synthetic hardware-loss request, using the browser WebGL extension on the real renderer.
  await page.locator('.garden-scene canvas').evaluate((canvas:HTMLCanvasElement)=>canvas.getContext('webgl2')!.getExtension('WEBGL_lose_context')!.loseContext());await expect(page.getByRole('button',{name:'Restore view',exact:true})).toBeVisible();await page.getByRole('button',{name:'Restore view',exact:true}).click();await expect(page.getByRole('button',{name:'Restore view',exact:true})).toHaveCount(0);await expect(page.locator('.garden-scene canvas')).toHaveCount(1);expect((await save(page)).payload).toEqual(before.payload);
  await sections(page);await expect(page.locator('.garden-scene')).toHaveAttribute('data-metrics',/activeSamples/);const metrics=await page.locator('.garden-scene').getAttribute('data-metrics');await info.attach('renderer-metrics',{body:metrics!,contentType:'application/json'});
 });
});
