import {GRANDMA_CUSHION_MS} from '../src/garden/grandmaTravel.js';
import {anchors} from '../src/garden/worldLayout.js';
import {savedChapter as saved} from './garden-save-fixture.js';
import {test,expect,type Page} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {playSpeakingTurn,waitForWalk} from './garden-actions.js';
import {installPlaybackVoice,finishVoiceSegment} from './garden-playback-voice.js';
import {welcomeWords} from '../src/garden/gathering.js';
test.setTimeout(180000);
const button=(p:Page,name:string)=>p.getByRole('button',{name:name==='Back to Pip'?/^(Back to Pip|Continue to the game)$/:name==='Plan the gathering with Grandma'?/^(Plan the gathering with Grandma|Review the gathering plan with Grandma)$/:name==='Let’s talk about why Mara stopped visiting.'?/^(Let’s talk about why Mara stopped visiting\.|Tell Grandma what Mara said)$/:name,exact:true});
async function gathering(p:Page){return JSON.parse((await p.locator('.garden-scene').getAttribute('data-gathering'))!);}
test('Gathering: authentic prior-save fixture, arrival recovery, compact world telling and exact chosen contribution',async({page},info)=>{
 await installPlaybackVoice(page,{legacySources:true});
 const source=JSON.parse(readFileSync('evidence/group-6-review-20260915/group-5-migration-inputs.json','utf8').replace(/^\uFEFF/,''));
 const fixture=source.cases.find((c:any)=>c.name==='both-informed-later-pip');
 await info.attach('fixture-boundary',{body:'Unedited real-handler Group5 save transported into an isolated automated browser. This is a labeled migration fixture, not native play or provider evidence. All subsequent actions use ordinary visible controls.',contentType:'text/plain'});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/garden');await saved(page);
 await page.evaluate(async record=>new Promise<void>(resolve=>{const r=indexedDB.open('evidence-quest-garden-adventure-v1');r.onsuccess=()=>{const db=r.result,t=db.transaction('slots','readwrite');t.objectStore('slots').put(record,'current');t.oncomplete=()=>{db.close();resolve();};};}),fixture.envelope);await page.reload();
 const prior=await saved(page);expect(prior.gathering.arrival).toBe('not-started');expect(prior.story.solDraft.text).not.toBe(prior.story.solEnding.text);
 await page.locator('.garden-access>summary').click();await page.locator('.garden-access').getByRole('button',{name:'Go to Grandma',exact:true}).click();await page.locator('.garden-access>summary').click();await waitForWalk(page,'Grandma',prior);await button(page,'Talk to Grandma E').click();await button(page,'Plan the gathering with Grandma').click();await button(page,'Tell Grandma everyone has agreed').click();await button(page,'Begin the gathering').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-action-kind','finalBoat');
 await button(page,'Help').click();await button(page,'Back to Pip').click();await expect.poll(async()=>(await saved(page)).gathering.arrival).toBe('boat-moored');await page.reload();const waiting=await saved(page);await page.keyboard.press('ArrowUp');expect((await saved(page)).pip).toEqual(waiting.pip);
 await button(page,'Help the last passengers ashore').click();await expect.poll(async()=>(await gathering(page)).arrival).toBe('passengers-ashore');expect((await gathering(page)).offDuty).toBe(true);await expect.poll(async()=>(await saved(page)).gathering.arrival).toBe('passengers-ashore');await page.reload();await button(page,'Let Sol walk to the garden').click();await expect.poll(async()=>(await gathering(page)).arrival).toBe('sol-arrived');await button(page,'Let Mara cross to the garden').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-action-kind','maraArrival');await page.screenshot({path:info.outputPath('mara-actual-crossing.png')});
 await expect.poll(async()=>(await gathering(page)).arrival,{timeout:25000,message:'Mara completes the physical 18-second route across the actual bridge'}).toBe('ready');
 const welcomeOpener=button(page,'Practise the welcome'),welcomeBefore=await saved(page);await welcomeOpener.click();const practice=page.getByRole('dialog',{name:'Reading practice',exact:true});await expect(practice).toHaveAttribute('data-recording','ready');await expect(practice.locator('.g-mic-off')).toContainText('Your microphone is off');await expect(practice.locator('.g-practice-words')).toHaveText(welcomeWords(welcomeBefore));await expect(practice).toHaveAttribute('data-local-audio-bytes','0');await practice.getByRole('button',{name:'Back to the story',exact:true}).click();await expect(practice).toHaveCount(0);await expect(welcomeOpener).toBeFocused();expect((await saved(page)).story.phase).toBe('welcome');expect((await saved(page)).gathering.turn).toBe(null);
 await button(page,'Welcome everyone in the garden').click();await page.setViewportSize({width:320,height:568});await expect(page.locator('.garden-gathering-controls')).toBeVisible();const canvas=await page.locator('.garden-scene canvas').boundingBox();expect(canvas!.height).toBeGreaterThanOrEqual(145);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await button(page,'Read the whole story with help').scrollIntoViewIfNeeded();expect((await button(page,'Read the whole story with help').boundingBox())!.height).toBeGreaterThanOrEqual(44);await page.screenshot({path:info.outputPath('compact-world-welcome.png')});
 await button(page,'Read the whole story with help').click();await expect(page.locator('.garden-reading-scroll')).toContainText('paused');await button(page,'Back to the world telling').click();expect((await saved(page)).gathering.turn.kind).toBe('welcome');await playSpeakingTurn(page);await page.setViewportSize({width:1440,height:1000});await button(page,'Share The Torn Wing').click();await playSpeakingTurn(page);await expect(button(page,'Invite Sol to share')).toBeVisible();await button(page,'Invite Sol to share').click();await button(page,'Let Sol share with everyone').click();await finishVoiceSegment(page);await expect.poll(async()=>(await saved(page)).gathering.turn.index).toBe(1);await finishVoiceSegment(page);await expect.poll(async()=>(await saved(page)).gathering.turn.index).toBe(2);const mid=await saved(page);expect(mid.gathering.solPerformed).toBe(null);await button(page,'Read the whole story with help').click();await page.getByRole('navigation',{name:'Reading tools'}).getByRole('button',{name:'Help',exact:true}).click();await button(page,'Back to the gathering').click();await button(page,'Back to the world telling').click();await page.reload();expect((await saved(page)).gathering.turn).toEqual(mid.gathering.turn);await page.screenshot({path:info.outputPath('restored-sol-world-turn.png')});await playSpeakingTurn(page);expect((await saved(page)).gathering.solPerformed).toEqual(prior.story.solEnding);
 await button(page,'Hear Grandma ask Sol').click();await playSpeakingTurn(page);await button(page,'Let Grandma bring out the cushions').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-action-kind','bringCushions');await expect.poll(async()=>{const p=JSON.parse((await page.locator('.garden-scene').getAttribute('data-mara-page'))!);return p.holderX>anchors.garden.person.x+.3;}).toBe(true);const held=JSON.parse((await page.locator('.garden-scene').getAttribute('data-mara-page'))!);expect(held.x).toBeCloseTo(held.palm[0],4);expect(held.y).toBeCloseTo(held.palm[1]+.025,4);expect(held.z).toBeCloseTo(held.palm[2]+.015,4);await page.screenshot({path:info.outputPath('moving-grandma-retains-mara-page.png')});await expect(button(page,'Let Grandma finish her account')).toBeVisible({timeout:GRANDMA_CUSHION_MS+5000});await button(page,'Let Grandma finish her account').click();await expect(page.getByRole('heading',{name:'The Empty Bench · by Grandma'})).toBeVisible();await page.screenshot({path:info.outputPath('two-distinct-pages.png')});await button(page,'Let Grandma share her story').click();await playSpeakingTurn(page);const end=await saved(page);expect(end.gathering).toMatchObject({solDisclosed:true,cushions:true,pageComplete:true,grandmaPerformed:true});for(const key of ['seed','river','bakery','page'])expect(end[key]).toEqual(prior[key]);expect(errors).toEqual([]);await info.attach('gathering-result',{body:JSON.stringify(end,null,2),contentType:'application/json'});
});
