import {anchors,BRIDGE_LEVELS} from '../src/garden/worldLayout.js';
import {collectRepairRopes,closeHandControls,placeBridgeSection,secureSpan,walkBridgePoint,worldPoint,plantWithGrandma,finishBoatDelivery,waitForBoatStop} from './garden-actions.js';
import {test,expect,type Page} from '@playwright/test';
import {readPersistedChapter} from './garden-save-fixture.js';
test.setTimeout(180000);
const button=(p:Page,name:string)=>p.getByRole('button',{name,exact:true});
async function begin(p:Page){await p.goto('/garden');await button(p,'Begin Pip’s adventure').click();await button(p,'Start playing').click();await button(p,'Go to the bridge pieces').click();await expect(p.locator('.garden-scene')).toHaveAttribute('data-pip-x',anchors.crossing.approach.x.toFixed(3));await collectRepairRopes(p);await closeHandControls(p);}
async function saved(p:Page){await expect(p.locator('.g-save')).toHaveText('Saved in this browser');return p.evaluate(async()=>new Promise<any>(resolve=>{const r=indexedDB.open('evidence-quest-garden-adventure-v1');r.onsuccess=()=>{const db=r.result,tx=db.transaction('slots'),q=tx.objectStore('slots').get('current');tx.oncomplete=()=>{db.close();resolve(q.result.payload);};};}));}
test('G3 ordinary controls: secured first span survives loose second collapse, reload, recovery and first garden context',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await begin(page);await placeBridgeSection(page,'a','Near bank at the narrow crossing');await secureSpan(page,'west');await walkBridgePoint(page,-.775,3);await placeBridgeSection(page,'b','Connect to the first section');await closeHandControls(page);
 const before=await saved(page),loose=await worldPoint(page,.775,3,BRIDGE_LEVELS.deck);await page.mouse.click(loose.x,loose.y);await expect(page.locator('.garden-scene')).toHaveAttribute('data-bridge-action','collapsing');await page.screenshot({path:info.outputPath('secured-first-span-collapse.png')});
 await expect.poll(async()=>(await saved(page)).story.bridgeFailures).toBe(1);const failed=await saved(page);expect(failed.west).toBe(true);expect(failed.east).toBe(false);expect(failed.joined).toBe(false);expect(failed.story.bridgeFailures).toBe(1);expect(failed.sections.a).toEqual(before.sections.a);expect(failed.river.construction.ropes).toEqual(before.river.construction.ropes);await page.reload();const restored=await saved(page);expect(restored.river.construction).toEqual(failed.river.construction);expect(restored.sections).toEqual(failed.sections);
 await walkBridgePoint(page,-.775,3);await placeBridgeSection(page,'b','Connect to the first section');await secureSpan(page,'east');await expect(page.locator('.garden-scene')).toHaveAttribute('data-bridge-ready','true');expect((await saved(page)).crossed).toBe(false);await button(page,'Go to Grandma').click();await button(page,'Talk to Grandma E').click();await page.getByText('Ask Grandma about the lantern flowers',{exact:true}).click();await expect(page.locator('.garden-reader')).toContainText('Those two lanterns hold The Windy Picnic and The Unexpected Duet.');await expect(page.locator('.garden-reader')).toContainText('The waiting flowers have room for the stories Mara, Sol and I share next.');await plantWithGrandma(page);await expect(page.locator('.garden-feedback')).toContainText('kept his promise');const c=await saved(page);expect(c.history.filter((v:string)=>['B','P','L'].includes(v))).toEqual(['B','P','L']);expect(c.river.soilPrepared).toBe(true);expect(errors).toEqual([]);await page.screenshot({path:info.outputPath('garden-arrival.png')});
});
test('G3 ordinary boat controls: loaded cargo, wrong dock, pause/reload, player steering and automatic receipt',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await begin(page);await button(page,'Read the note').click();await button(page,'Load the seed into the boat').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-ferry-phase','steering');await expect(button(page,'Launch the seed boat')).toHaveCount(0);await button(page,'Try docking at Grandma’s landing').click();await expect(page.locator('.garden-feedback')).toContainText('Grandma can reach the boat at her blue landing');
 await page.setViewportSize({width:320,height:568});
 const canvas=await page.locator('.garden-scene canvas').boundingBox();expect(canvas?.width).toBeGreaterThan(200);expect(canvas?.height).toBeGreaterThanOrEqual(140);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect((await button(page,'Upstream ↑').boundingBox())?.height).toBeGreaterThanOrEqual(48);
 await page.screenshot({path:info.outputPath('compact-boat.png')});
 await button(page,'Help').click();await expect(page.locator('.garden-reader')).toBeVisible();await button(page,'Back to the seed boat').click();
 await button(page,'Upstream ↑').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-z','0.250');await waitForBoatStop(page);await button(page,'Garden side →').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-x','-0.850');await waitForBoatStop(page);await button(page,'Pause').click();const paused=await saved(page);expect(paused.seed).toBe('boat');await page.getByLabel('Reduced motion',{exact:true}).check();await button(page,'Back to the seed boat').click();await page.reload();const restored=await saved(page);expect(restored.river.boat.position).toEqual(paused.river.boat.position);expect(restored.history.includes('F')).toBe(false);await page.screenshot({path:info.outputPath('boat-paused-cargo.png')});
 await page.setViewportSize({width:1440,height:1000});
 for(const x of [-.3,.25,.8,1.35]){await button(page,'Garden side →').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-x',x.toFixed(3));await waitForBoatStop(page);}
 await button(page,'Downstream ↓').click();await expect(page.locator('.garden-scene')).toHaveAttribute('data-seed-boat-z','0.800');expect((await saved(page)).seed).toBe('boat');const end=await finishBoatDelivery(page,true);await expect(page.locator('.garden-feedback')).toContainText('Grandma holds the seed');expect(end.seed).toBe('grandma');expect(end.river.boat.position).toEqual(anchors.boat.landing);expect(end.river.soilPrepared).toBe(false);expect(end.history.filter((v:string)=>v==='F')).toHaveLength(1);expect(end.pip).toEqual(paused.pip);expect(end.river.collection.phase).toBe('return');
 // A long uninterrupted NPC trip must write intermediate progress. Waiting for
 // the entire return would conceal starvation in the persistence debounce.
 await expect.poll(async()=>{const now=await readPersistedChapter(page);return now.river.collection?.phase==='return'&&now.river.collection.distance<end.river.collection.distance;},{timeout:3000}).toBe(true);
 const travelling=await readPersistedChapter(page);await page.reload();await expect(page.locator('.garden-scene')).toHaveAttribute('data-rendered-view','walk');const resumed=await readPersistedChapter(page);expect(resumed.seed).toBe('grandma');expect(resumed.river.collection.phase).toBe('return');expect(resumed.river.collection.distance).toBeLessThanOrEqual(travelling.river.collection.distance);expect(resumed.history.filter((v:string)=>v==='F')).toHaveLength(1);expect(errors).toEqual([]);await page.screenshot({path:info.outputPath('received-seed.png')});
});
