import{test,expect}from'@playwright/test';import{writeFile,mkdir}from'node:fs/promises';import{start,workstation,putTile,saved}from'./helpers.js';import{measuredScene}from'./production-measurements.js';import production from'../content/production-assets.json'with{type:'json'};
const evidence=process.env['EQ_EVIDENCE_DIR']??'evidence/er13';
test.beforeEach(async()=>{await mkdir(evidence,{recursive:true});});
test('TASK11.20 Home uses its actual cover density and a decoded PNG backdrop when WebP fails',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:{width:1440,height:1000},deviceScaleFactor:2}),page=await context.newPage();await page.route('**/art/runtime/*.webp',route=>route.abort());await page.goto('/');
 const background=page.locator('.home-backplate');await expect(background).toHaveAttribute('data-art-state','ready');await expect(background).toHaveAttribute('data-density','2');await expect(background).toHaveAttribute('data-art-url',/\.png$/);expect(await background.evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);await expect(page.locator('.home-cast [data-art-ready=true]')).toHaveCount(3);
 await page.screenshot({path:`${evidence}/home-png-${info.project.name}.png`});await page.getByRole('button',{name:'Join the crew',exact:true}).click();await page.getByRole('button',{name:'Keep exploring',exact:true}).click();await page.waitForLoadState('networkidle');const snapshot=await measuredScene(page);const backdrop=await background.count();expect(backdrop).toBe(0);const url=production['ASSET.ENV.ST.BACKPLATE/base'].levels['2'].frames[0].fallbackUrl;expect(snapshot.resources.filter(r=>r.url===url&&r.encodedBytes>0)).toHaveLength(1);expect(snapshot.unknownImages).toEqual([]);await writeFile(`${evidence}/home-png-${info.project.name}.json`,JSON.stringify(snapshot,null,2)+'\n');await context.close();
});
test('TASK11.20 cold failed opaque room retains light wood and explicit Retry replaces incomplete scenery',async({page},info)=>{
 const urls=Object.values(production['ASSET.ENV.ST.BACKPLATE/base'].levels).flatMap(l=>l.frames.flatMap(f=>[f.url,f.fallbackUrl]));let failed=true;await page.route('**/art/runtime/*',r=>failed&&urls.includes(new URL(r.request().url()).pathname)?r.abort():r.continue());await start(page);await expect(page.locator('.render-error')).toBeVisible();const pixel=()=>page.getByTestId('world').evaluate((c:HTMLCanvasElement)=>[...c.getContext('2d')!.getImageData(0,0,1,1).data]);expect(await pixel()).toEqual([238,198,157,255]);await page.screenshot({path:`${evidence}/cold-room-${info.project.name}.png`});failed=false;await page.locator('.render-error button').click();await expect(page.locator('.render-error')).toHaveCount(0);await expect.poll(pixel).not.toEqual([238,198,157,255]);await page.screenshot({path:`${evidence}/retried-room-${info.project.name}.png`});
});
test('TASK11.20 live projection retains static ownership, resize invalidates exact surfaces and Stop preserves the cue',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:{width:1440,height:1000},deviceScaleFactor:2}),page=await context.newPage();await workstation(page);await putTile(page,'BRIDGE');await putTile(page,'PLANT','Joined Boats');await putTile(page,'BLOOM','Hill');await page.waitForLoadState('networkidle');await page.getByRole('button',{name:'Try this ending',exact:true}).click();await expect.poll(()=>page.getByTestId('world').evaluate((c:HTMLCanvasElement & {artFrameStats?:{projection:number}})=>c.artFrameStats?.projection??0)).toBeGreaterThan(0);await page.getByRole('button',{name:'Stop',exact:true}).click();expect((await saved(page)).payload.playback?.status).toBe('paused');const before=await measuredScene(page);await page.setViewportSize({width:320,height:568});await expect.poll(()=>page.getByTestId('world').evaluate((c:HTMLCanvasElement)=>c.width===Math.ceil(c.getBoundingClientRect().width*2))).toBe(true);const after=await measuredScene(page);expect(after.rasterReserved).toBeLessThan(before.rasterReserved);expect(after.rasterPeak).toBeLessThanOrEqual(24*1024*1024);expect(after.encodedPeak).toBeLessThanOrEqual(8*1024*1024);await page.getByRole('button',{name:'Continue rehearsal',exact:true}).click();await expect(page.getByRole('button',{name:'Start premiere',exact:true})).toBeVisible();expect((await saved(page)).payload.certificate).not.toBeNull();await writeFile(`${evidence}/render-resize-${info.project.name}.json`,JSON.stringify({before,after},null,2)+'\n');await context.close();
});
