import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {start,target,settled,saved,closePanel,go,collectKit,putTile} from './helpers.js';
import {actorHome,actorHeight,doorBounds,stageLeft,stageRight,mediaKitStop} from '../src/physical/presentation.js';
import {actorContentBounds,overlaps} from '../src/world/actor-geometry.js';

const evidence=process.env['EQ_EVIDENCE_DIR']??'evidence/scale-20260912';
async function clickWorld(page:Page,x:number,y:number){const world=page.getByTestId('world');await world.scrollIntoViewIfNeeded();const box=await world.boundingBox();await world.click({position:{x:x/120*box!.width,y:y/80*box!.height}});}
async function chooseOverlap(page:Page,id:string){const choice=page.locator(`[data-owner="${id}"]`);if(await choice.isVisible())await choice.click();}
for(const compact of [false,true])test(`ER13.06 scale ${compact?'compact':'1469x1105'} connected rooms, actual head targets, carried kit and side console`,async({page},info)=>{
 test.setTimeout(240000);await mkdir(evidence,{recursive:true});await page.setViewportSize(compact?{width:320,height:568}:{width:1469,height:1105});const label=`${info.project.name}-${compact?'compact':'1469x1105'}`,errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await start(page);if(compact){await page.getByRole('button',{name:'Menu',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByLabel('Text size',{exact:true}).selectOption('largest');await page.getByLabel('Text spacing',{exact:true}).selectOption('roomier');await page.keyboard.press('Escape');await page.keyboard.press('Escape');}const visits:unknown[]=[];
 async function capture(name:string){await page.waitForLoadState('networkidle');await page.getByTestId('world').scrollIntoViewIfNeeded();await page.screenshot({path:`${evidence}/${label}-${name}.png`});visits.push({name,physical:(await saved(page)).payload.physical,bundles:await page.evaluate(()=>performance.getEntriesByType('resource').map(e=>new URL(e.name).pathname).filter(n=>n.startsWith('/assets/App-')&&n.endsWith('.js')))});}
 async function person(id:string,name:string){const [x,y]=actorHome(id);await clickWorld(page,x,y-actorHeight(id)*.83);await chooseOverlap(page,id);await settled(page);await expect(page.locator('.speaker h2')).toContainText(name);await closePanel(page);await capture(name.toLowerCase()+'-approach');}
 await capture('stage');await person('ACT.JO','Jo');await target(page,'ST.MODEL');await settled(page);await closePanel(page);await capture('model-approach');
 // The top of the enlarged door is outside the former tiny hit rectangle.
 const door=doorBounds('ST.EXIT.CY')!;await clickWorld(page,(door[0]+door[2])/2,door[1]+3);await chooseOverlap(page,'ST.EXIT.CY');await expect(page.locator('.game-header strong')).toHaveText('Courtyard');await capture('courtyard');await person('ACT.REMY','Remy');
 await target(page,'CY.SOURCE.E7');await settled(page);await closePanel(page);await capture('courtyard-bench');await go(page,'CY.EXIT.WK','Workshop');await capture('workshop');await clickWorld(page,25,48);await settled(page);await capture('workshop-bench');
 await go(page,'WK.EXIT.MD','Media room');await capture('media');await person('ACT.ARI','Ari');await target(page,'MD.ACCESS.E8');expect((await settled(page)).payload.physical.avatar).toEqual(mediaKitStop());await closePanel(page);await capture('media-rack');await collectKit(page);await closePanel(page);await target(page,'ACT.LOOP');await settled(page);await capture('carrying-with-loop');
 const before=(await saved(page)).payload;expect(before.physical.caddyHost).toBe('ACT.PLAYER');expect(before.physical.loop.mode).toBe('following');expect(before.exposures.some(e=>e.refId.startsWith('E6.'))).toBe(false);
 await clickWorld(page,80,65);await settled(page);await expect.poll(async()=>{const p=(await saved(page)).payload.physical;return !overlaps(actorContentBounds('ACT.PLAYER',p.avatar,'carry-front'),actorContentBounds('ACT.LOOP',p.loop.feet,'rolling-front'));}).toBe(true);await capture('down-screen-follow');
 await go(page,'MD.EXIT.WK','Workshop');await capture('carrying-workshop');await go(page,'WK.EXIT.CY','Courtyard');await capture('carrying-courtyard');await go(page,'CY.EXIT.ST','Stage');await capture('carrying-stage');
 await target(page,'ST.DOCK');await settled(page);await target(page,'ST.RACK.BAY');let caseState=(await settled(page)).payload;expect(caseState.physical.avatar).toEqual(stageLeft());expect(caseState.physical.facing).toBe('right');expect(caseState.physical.caddyHost).toBe('ST.RACK.BAY');await capture('console-left');
 await target(page,'ST.CONTROL.REHEARSE');caseState=(await settled(page)).payload;expect(caseState.physical.avatar).toEqual(stageRight());expect(caseState.physical.facing).toBe('left');await capture('console-right');
 await putTile(page,'BRIDGE');await putTile(page,'PLANT','Joined Boats');await putTile(page,'BLOOM','Hill');await page.getByRole('button',{name:'Try this ending',exact:true}).click();await page.getByRole('button',{name:'Stop',exact:true}).click();const paused=(await saved(page)).payload;expect(paused.playback?.status).toBe('paused');
 await page.reload();await page.getByRole('button',{name:'Continue',exact:true}).click();await target(page,'ST.RAIL');await settled(page);await page.getByRole('button',{name:'Continue rehearsal',exact:true}).click();await expect(page.getByRole('button',{name:'Start premiere',exact:true})).toBeVisible();expect((await saved(page)).payload.certificate).not.toBeNull();
 expect(errors).toEqual([]);await writeFile(`${evidence}/${label}-route.json`,JSON.stringify({at:new Date().toISOString(),viewport:page.viewportSize(),visits,errors,scope:'Fresh automated browser route and captures; separate from independent native visual acceptance.'},null,2)+'\n');
});
