import {test,expect,type Page} from '@playwright/test';
import {copy} from '../src/core/content.js';
import {exposed} from '../src/core/evidence.js';
import {start,target,settled,saved,go,workstation,putTile,premiere} from './helpers.js';
const button=(page:Page,id:string)=>page.getByRole('button',{name:copy(id),exact:true});
test('TASK11.08 recording controls expose only displayed components; vocabulary and enlargement return safely',async({page})=>{
 await start(page);await target(page,'ST.ACCESS.E2');await settled(page);await button(page,'CT.CLIP.NEXT').click();await page.locator('[data-content-id="CT.MEDIA.FRAME2"]').scrollIntoViewIfNeeded();await button(page,'CT.CLIP.NEXT').click();await page.locator('[data-content-id="CT.MEDIA.END"]').scrollIntoViewIfNeeded();let state=await saved(page);expect(exposed(state.payload,'E2.a/end')).toBe(true);expect(exposed(state.payload,'E3.a')).toBe(false);
 await button(page,'CT.CLIP.DESCRIBE').click();await page.locator('[data-content-id="CT.SRC.E2.A"]').scrollIntoViewIfNeeded();state=await saved(page);expect(exposed(state.payload,'E2.a')).toBe(true);
 await button(page,'CT.MEDIA.RECORDING').click();await button(page,'CT.CLIP.PLAY').click();await expect(page.locator('[data-content-id="CT.MEDIA.FRAME3"]')).toBeVisible();await button(page,'CT.CLIP.REPLAY').click();await button(page,'CT.CLIP.PAUSE').click();await button(page,'CT.SOURCE.ENLARGE').click();await expect(page.locator('.enlarged')).toBeVisible();await page.locator('.task-close button').click();await expect(page.locator('.enlarged')).toHaveCount(0);
 await target(page,'ST.SOURCE.E1');await settled(page);const word=page.locator('[data-word="PREMIERE"]').first();await word.click();await expect(page.getByRole('heading',{name:'premiere',exact:true})).toBeFocused();await page.getByRole('button',{name:'Return to the passage',exact:true}).click();await expect(word).toBeFocused();
});
test('TASK11.09 Ari full account before recovery and limited after recovery; source origin remains explicit',async({page})=>{
 await start(page);await go(page,'ST.EXIT.WK','Workshop');await go(page,'WK.EXIT.MD','Media room');await target(page,'ACT.ARI');await settled(page);await button(page,'CT.TALK.FILMING').click();await page.locator('[data-content-id="CT.SRC.E5.B"]').scrollIntoViewIfNeeded();const before=await saved(page);expect(before.payload.grants.some(g=>g.viaAccessId==='NPC.ARI.FILMING')).toBe(true);
 await button(page,'CT.TALK.REQUEST').click();await expect(page.locator('.reader')).toBeVisible();await page.locator('.task-close button').click();await expect(page.getByRole('heading',{name:'Ari animation maker',exact:true})).toBeFocused();
 await target(page,'ACT.LOOP');await settled(page);await target(page,'ACT.ARI');await settled(page);await button(page,'CT.TALK.FILMING').click();await expect(page.getByText(copy('CT.ARI.FOLLOWING'),{exact:true})).toBeVisible();expect((await saved(page)).payload.grants.some(g=>g.viaAccessId==='NPC.ARI.FILMING_AFTER')).toBe(true);
});
test('TASK11.13 Maximum Toast can be ignored, canceled, revealed, interrupted, magnified and replayed',async({page})=>{
 await start(page);await go(page,'ST.EXIT.WK','Workshop');await target(page,'WK.TOAST');await settled(page);await page.locator('.task-close button').click();expect((await saved(page)).payload.physical.objects.toastRevealed).toBe(false);
 await target(page,'WK.TOAST');await settled(page);await button(page,'CT.TOAST.START').click();await expect(button(page,'CT.TOAST.LOOK')).toBeDisabled();await expect(page.getByText(copy('CT.TOAST.ARMS'),{exact:true}).last()).toBeVisible();await button(page,'CT.TOAST.SKIP').click();await expect(page.getByText(copy('CT.TOAST.PUNCHLINE'),{exact:true}).last()).toBeVisible();await button(page,'CT.TOAST.LOOK').click();await expect(page.getByText(copy('CT.TOAST.ENLARGED'),{exact:true})).toBeVisible();
 await button(page,'CT.TOAST.REPLAY').click();await expect(button(page,'CT.TOAST.LOOK')).toBeDisabled();await expect(button(page,'CT.TOAST.LOOK')).toBeEnabled();const state=await saved(page);expect(state.payload.physical.objects.toastRevealed).toBe(true);expect(state.payload.physical.caddyHost).toBe('MD.RACK.STATION');expect(state.payload.physical.loop.mode).toBe('standby');
 await page.screenshot({path:'output/playwright/maximum-toast.png',fullPage:true});
});
test('TASK11.09/13 actual addressed explanation, recorded revision and own-room aftermath',async({page})=>{
 await workstation(page);await button(page,'CT.PLAN.STORY').click();await page.getByRole('textbox').fill('First I will cross.');await button(page,'CT.PLAN.RECORD').click();await page.getByRole('textbox').fill('Pip and the seed will cross, then plant together.');await button(page,'CT.PLAN.RECORD').click();let state=await saved(page);expect(state.payload.records.at(-1)?.previousRecordId).toBe(state.payload.records.at(-2)?.id);expect(state.payload.npcReceived).toEqual([]);
 await button(page,'CT.PLAN.EXPLAIN').click();await settled(page);state=await saved(page);expect(state.payload.records.at(-1)?.recipient).toBe('ACT.JO');expect(state.payload.records.at(-1)?.kind).toBe('jo-explanation');
 await target(page,'ST.RAIL');await settled(page);await putTile(page,'BRIDGE');await putTile(page,'PLANT','Joined Boats');await putTile(page,'BLOOM','Hill');await premiere(page);await button(page,'CT.ENDING.REACTIONS').click();await expect(page.locator('.reaction-person')).toHaveAccessibleName('Remy');await button(page,'CT.ENDING.NEXT').click();await expect(page.locator('.reaction-person')).toHaveAccessibleName('Ari');await button(page,'CT.ENDING.NEXT').click();await expect(page.getByText('Pip and the seed will cross, then plant together.',{exact:true})).toBeVisible();
});
