import type { CaseState, Preferences, Session, Point, Order } from '../../contracts/types.js';
export interface View {page:'home'|'world'|'objects'|'map'|'goal'|'settings'|'pause'|'reader'|'notes'|'notice'|'kit'|'talk'|'plan'|'lead'|'present'|'work'|'story'|'help'|'toast'|'ending'|'confirm'|'recovery';sourceId?:string;accessId?:string;ref?:string;frame?:number;actor?:'ACT.JO'|'ACT.REMY'|'ACT.ARI';topic?:'search'|'story';cts?:string[];selected?:string[];dialogue?:string[];action?:string;previous?:View;}
export interface Delivery {actor:'ACT.JO'|'ACT.REMY'|'ACT.ARI';refs:string[];text:string;topic:'search'|'story';plan:boolean;}
export interface Intent {id:string;target:string;action:string;path:Point[];stage:'approaching'|'operating';delivery?:Delivery;returnView?:View;}
export interface Runtime {intent:Intent|null;loopHistory:Point[];clockMs:number;cueElapsedMs:number;operationElapsedMs:number;view:View;caption:string[];captionSlots:Record<string,string|number>;contextRevision:number;pendingSaveToken:string|null;lastHandled:string[];artFailure:boolean;canvasFailure:boolean;bootGeneration:string;homeStatus:'checking'|'empty'|'saved'|'read-error'|'version'|'damaged'|'conflict'|'run';savedCandidate:CaseState|null;lastRailOrder:Order|null;hasLiveVisit:boolean;restorePreservesSlots:boolean;preferenceFailed:boolean;toastElapsed:number|null;toastReplay:boolean;coachTransport:'authored'|'development';helpPresentation:import('../coach/lifecycle.js').Presentation|null;helpSubmission:string|null;helpOpportunity:import('../coach/lifecycle.js').Opportunity|null;npcHelp:{id:string;actor:string;ct:string;displayed:boolean}|null;}
export interface State {case:CaseState;session:Session;preferences:Preferences;runtime:Runtime;}
export const IDENTITY={caseId:'sparkfest-little-bridge-001',contentVersion:3,contentRevision:1} as const;
export function newCase(id:string):CaseState{return {caseRunId:id,revision:0,lastObservationSeq:0,physical:{room:'SC.ST',avatar:[20,50],facing:'up',loop:{room:'SC.MD',feet:[68,45],mode:'standby'},objects:{modelTabTried:false,briefOpen:false,storyNoteOpen:false,filmingRequestOpen:false,noticeFlat:false,dockFlapOpen:false,rackOpened:false,previewTried:false,toastRevealed:false},caddyHost:'MD.RACK.STATION',order:[],arrangementRevision:0},grants:[],exposures:[],selectedLead:null,comparisons:[],drafts:([ 'private','search-plan','story-plan','coach-search','coach-story'] as const).map(id=>({id,text:'',selectedRefs:[],revision:0})),records:[],npcReceived:[],playback:null,runHistory:[],certificate:null,premiere:null,observations:[],readerResume:null,worldReturn:{ownerId:'ACC.OBJECTS',actionCtId:null},historyUncertain:false,guidance:{openingDismissed:false,movementDismissed:false,ariInvitationDismissed:false},visitedRooms:['SC.ST'],encounteredActors:[],coachingHistory:[]};}
export function newSession(visitId:string):Session{return {contractKind:'Session',visitId,inputOwner:'home',taskState:'UI.HOME.CHECKING',childState:null,callerState:null,callerReturn:null,focusOwner:null,pendingAction:null,heldTile:null,heldKeys:[],presentation:'arrange',coach:{request:null,status:'idle',winner:null,heldResponse:null,fallbackFocused:false,deadlineElapsedMs:0},saving:{currentRevision:0,requestedRevision:null,acknowledgedRevision:null,knownSlotRevision:null,writeInFlight:false,mode:'normal'},scroll:[]};}
export function initialState(caseId:string,visitId:string,reduced=false):State{return freeze({case:newCase(caseId),session:newSession(visitId),preferences:{contractKind:'Preferences',formatVersion:1,revision:0,sound:'on',motion:reduced?'reduced':'standard',text:'regular',spacing:'standard'},runtime:{intent:null,loopHistory:[[20,50]],clockMs:0,cueElapsedMs:0,operationElapsedMs:0,view:{page:'home'},caption:[],captionSlots:{},contextRevision:0,pendingSaveToken:null,lastHandled:[],artFailure:false,canvasFailure:false,bootGeneration:visitId,homeStatus:'checking',savedCandidate:null,lastRailOrder:null,hasLiveVisit:false,restorePreservesSlots:false,preferenceFailed:false,toastElapsed:null,toastReplay:false,coachTransport:'authored',helpPresentation:null,helpSubmission:null,helpOpportunity:null,npcHelp:null}});}
export function freeze<T>(value:T):T{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);for(const item of Object.values(value))freeze(item);}return value;}
