// Dated supporting-copy changes authorized by 13-EXPERIENCE-AND-LITERACY-CORRECTION.md.
// Source bodies CT.SRC.* and their code-point reference spans remain unchanged.
export const overrides={
 'CT.START.CASE':'Our story needs an ending.',
 'CT.START.START':'Join the crew',
 'CT.GOAL.ASSIGNMENT':"You're running the show with our crew. Find Loop so we can put on The Little Bridge.",
 'CT.GOAL.SEARCH':'Find Loop so our crew can put on The Little Bridge.',
 'CT.GOAL.REHEARSE':"The screen works and the story tiles are ready. Now help Pip keep the promise in Jo's story.",
 'CT.GOAL.LAUNCH':"Your ending works. You're ready to put on the show.",
 'CT.GOAL.AFTER':"You brought Loop back, finished Pip's journey, and put on your crew's first show.",
 'CT.DIRECT.LAUNCH':'Your ending worked in practice. Choose Start premiere to put on the show.',
 'CT.RECOVERY.RUN':'This story could not be continued from where it stopped.',
 'CT.ACCESS.WORK':'Arrange tiles and Watch use the same story. Switching views pauses the paper story; use Continue when you want it to run again.',
 'CT.RAIL.CHANGED':'Your tile order changed. Try this ending in rehearsal.',
 'CT.GOAL.KIT':'Bring the story kit to the Stage desk.',
 'CT.OBJ.WAKE':'Wake Loop',
 'CT.OBJ.WAKE_RESULT':'Loop is awake and ready to follow you.',
 'CT.OBJ.MODEL_RESULT':'Pip reaches the river, but the broken bridge stops him. Grandma is waiting across the water.',
 'CT.JO.MODEL':'Let’s try our paper story on the big screen.',
 'CT.MEDIA.SLATE':'Recording notes',
 'CT.OBJ.SLATE':'Read recording notes',
 'CT.SCENE.MD':'Media room. Ari is beside the recording table. Paper petals lie still in front of a plain wall. The recording notes are on the table. Jo’s and Remy’s mounted notes are beside the space for the story kit. Workshop is through the bottom exit.',
 'CT.SCENE.MD.NO_KIT':'The space for the story kit is empty. Both mounted notes are still here.',
 'CT.ARI.WAIT':"I was finishing the recording and keeping the materials together for you. You're running the show with our crew.",
 'CT.TITLE.E5':"Ari's recording notes and Loop",
 'CT.TALK.SLATE':'Can I see the recording notes?',
 'CT.RAIL.TITLE':'Plan our story',
 'CT.RAIL.HELP':'Place the story tiles in the order you want Loop to play them. Choose a tile, then choose where it goes. You can also drag tiles.',
 'CT.WORK.REHEARSE':'Try this ending',
 'CT.WORK.LAUNCH':'Start premiere',
 'CT.WORK.PREVIEW':'Try the big screen',
 'CT.WORK.CERTIFIED':"Pip reached Grandma, and they planted the seed together. Your ending works. You're ready to put on the show.",
 'CT.WORK.PREVIEW_RESULT':"Loop isn't in the dock. Ari borrowed it to record the last scene. Let's find them and bring our equipment back. Then you can try an ending for Pip.",
 'CT.WORK.MISSING_KIT':'Bring the story kit to the Stage desk so you can plan the ending.',
 'CT.WORK.CHECK':'Try your ending before you put on the show.',
 'CT.CUE.FERRY':'The seed reached Grandma. Pip is still across the river.',
 'CT.CUE.FERRY_EMPTY':"There's no seed here for the boat to carry. The story continues.",
 'CT.GUIDE.PREVIEW':'Try the big screen at the Stage desk.',
 'CT.OBS.LOOP.SEEN':'Loop is here. Our projector can go back to the Stage.',
 'CT.OBS.LOOP.RESPONSE':'Loop turned toward you and is ready to follow.',
 'CT.TOAST.COVERED':'Someone built a very large machine to make a snack. Want to see what it does?',
 'CT.TOAST.PUNCHLINE':'One tiny slice. Maximum effort.',
};
export const additions={
 'CT.SOURCE.LIMIT':'Choose up to two details. To choose a different one, uncheck a selected detail.',
 'CT.ER13.HANDOFF_BOTH':'Set the story kit on the desk, and bring Loop to its dock.',
 'CT.ER13.HANDOFF_LOOP':'Bring Loop to its dock. The story kit is on the desk.',
 'CT.ER13.HANDOFF_KIT':'Set the story kit on the desk. Loop is in its dock.',
 'CT.ER13.KIT_THEN_LOOP':'Set the story kit on the desk. Then find Loop and bring it back.',
 'CT.ER13.KIT_THEN_KNOWN_LOOP':'Set the story kit on the desk. Then return to the Media room and wake Loop.',
 'CT.ER13.RETURN_TO_LOOP':'Return to the Media room and wake Loop so our projector can come back to the Stage.',
 'CT.ER13.LOOP_THEN_KIT':'Bring Loop to its dock. Then collect the story kit.',
 'CT.ER13.RETURN_LOOP':'Bring Loop back to the Stage. The story kit is on the desk.',
 'CT.ER13.WAKE':'Wake Loop so our projector can come back to the Stage.',
 'CT.ER13.HOME':'Join your friends at SparkFest. Find Loop, bring your paper story to life, and put on The Little Bridge.',
 'CT.ER13.SIGN':'SparkFest — stories and inventions made by us',
 'CT.ER13.PROGRAM':"Today's show: The Little Bridge",
 'CT.ER13.INTRO0':"There you are! Welcome to SparkFest. It's our festival of stories and inventions. Today, visitors are coming to see the story we made together.",
 'CT.ER13.INTRO1':"This is Pip, our paper traveler. That's the red backpack you helped make. Our show is called The Little Bridge.",
 'CT.ER13.INTRO2':"Pip promised to visit Grandma and plant a seed with her. But the river washed their bridge away. We still need to make the ending work.",
 'CT.ER13.INTRO3':"You're running the show with us. Loop, our rolling projector, makes these paper characters move on the big screen.",
 'CT.ER13.REMY':"I'm Remy. I made the little boats for our show. I was filming behind the scenes when I saw Loop leave.",
 'CT.ER13.ARI':"You found us! I'm Ari. I record the moving paper scenes for our show.",
 'CT.ER13.SCOPE':'The outdoor practice was canceled. The first public show is still planned.',
 'CT.ER13.PROMISE_SUPPORT':'Pip promised to plant with Grandma. They are still on opposite banks.',
 'CT.ER13.WELCOME':'Welcome to SparkFest! Today, our crew is putting on The Little Bridge. We made the paper characters together. Now we need to bring their story to life on the big screen.',
 'CT.ER13.ENDING':"Pip crossed the river to reach Grandma. Together, they planted the seed in the hill's soil. A lantern-flower opened, and its warm light shone across the water.",
 'CT.ER13.PREMIERE_CONTEXT':'Our premiere is the first public showing of The Little Bridge.',
 'CT.ER13.REHEARSAL_CONTEXT':'In rehearsal, we can try an ending and change it before a show.',
 'CT.ER13.REPLAY_CONTEXT':'Our first show is complete. We can put this ending on the big screen again.',
 'CT.ER13.REPLAY_READY':"Pip reached Grandma, and they planted the seed together. Your ending works. You're ready to replay the show.",
 'CT.ER13.STILL_CONTEXT':'The paper petals stay still indoors.',
 'CT.ER13.TOGETHER_CONTEXT':'Pip and Grandma will plant the seed together.',
};
export function corrected(entries){
 const ids=new Set(entries.map(e=>e.id));
 for(const id of Object.keys(overrides))if(!ids.has(id)||id.startsWith('CT.SRC.'))throw Error('Unreviewed ER13 override '+id);
 return [...entries.map(e=>overrides[e.id]?{...e,text:overrides[e.id]}:e),...Object.entries(additions).map(([id,text])=>({id,text,origin:'N',condition:'ER13 experience correction; view and encounter bounded',sourceLine:null}))];
}
