import {readFile,writeFile} from 'node:fs/promises';
const [id,status,evidence,...description]=process.argv.slice(2);
const planPath='docs/design/evidence-quest-design-v3/11-build-packet/implementation-plan.json';
const p=JSON.parse(await readFile(planPath,'utf8')),task=p.tasks.find(t=>t.id===id);
if(!task||!['IN_PROGRESS','COMPLETE'].includes(status))throw new Error('Existing task ID and explicit status required');
const file='evidence/task-execution.json';
const log=JSON.parse(await readFile(file,'utf8').catch(()=>'{"events":[],"humanAttentionMinutes":null}'));
log.events.push({at:new Date().toISOString(),id,status,evidence,description:description.join(' ')});
await writeFile(file,JSON.stringify(log,null,2)+'\n');
task.status=status;task.execution={evidence,result:description.join(' '),updatedAt:log.events.at(-1).at};
p.schedule.forecast.milestones['M11.CONNECTED'].status=p.tasks.filter(t=>/^TASK11\.(0[1-9]|1[0-6])$/.test(t.id)).every(t=>t.status==='COMPLETE')?'COMPLETE':'IN_PROGRESS';
await writeFile(planPath,JSON.stringify(p,null,2)+'\n');
let md=await readFile('BUILD-STATUS.md','utf8');
const lines=md.split('\n');
const i=lines.findIndex(l=>l.startsWith(`| ${id} |`));
if(i<0)throw new Error('No existing status row');
lines[i]=`| ${id} | ${task.title} | ${status} | ${task.dependsOn.join(', ')} | ${description.join(' ')} [Evidence](${evidence}). |`;
md=lines.join('\n').replace(/^Updated .+?\. Item/m,`Updated ${log.events.at(-1).at}. Item`);
const next=p.tasks.find(t=>/^TASK11\.(0[1-9]|1[0-6])$/.test(t.id)&&t.status!=='COMPLETE');
md=md.replace(/## Current next dependency\n[\s\S]*?\n## Calibration/,`## Current next dependency\n\n${next?`${next.id}: ${next.title}. Follow its recorded dependencies and applicable acceptance checks.`:'TASK11.16 evidence review and final repository verification.'}\n\n## Calibration`);
await writeFile('BUILD-STATUS.md',md);
await writeFile('evidence/measured-schedule.md','# Connected build execution view\n\nGenerated from the existing task plan and dated execution events. Historical forecasts are preserved in REVISED-SCHEDULE.md. Human attention and unmeasured intervals remain unknown; temporary asset work does not calibrate final art.\n\n|Task|Status|Last recorded event|\n|---|---|---|\n'+p.tasks.slice(0,17).map(t=>`|${t.id}|${t.status}|${t.execution?.updatedAt??'No execution event'}|`).join('\n')+'\n');
console.log(`${id} ${status}`);
