import {useEffect,useRef,useState} from 'react';
import {readingContextOf} from './narrativeEdition.js';
import type {GardenStore} from './model.js';
import {boundedWordTarget,type DisplayOrigin} from './readingReference.js';
type Target={source:string|null;paragraph:number;draft:string|null;revision:number;start:number;end:number;word:string;sentence:string;origin?:DisplayOrigin};
export function AdditionalWordHelp({target,reviewed,store,speak,replace,close}:{target:Target;reviewed?:string|undefined;store:GardenStore;speak:(text:string)=>void;replace?:(word:string)=>void;close?:()=>void}){
 const [reply,setReply]=useState<{meaning:string|null;explanation:string;spelling:string|null}|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[checked,setChecked]=useState(false);const active=useRef<AbortController|null>(null);
 const unavailable=reviewed?"An explanation for this sentence isn't available right now.":"Word help isn't available for this word right now. Your writing is unchanged.";
 async function request(disputed:string|null=null){active.current?.abort();const controller=new AbortController();active.current=controller;setReply(null);setNotice('Looking at this word in your sentence…');setBusy(true);const requestId=crypto.randomUUID(),timer=setTimeout(()=>controller.abort(),15000);
  try{const bounded=boundedWordTarget(target),response=await fetch('/api/garden/word',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId,...bounded,...(bounded.origin==='generated-feedback'?{origin:'mixed-display'}:{}),...readingContextOf(store.getSnapshot().chapter),disputed}),signal:controller.signal}),r=await response.json();if(active.current!==controller||controller.signal.aborted)return;
   if(response.ok&&r.requestId===requestId&&r.revision===target.revision&&r.start===bounded.start&&r.end===bounded.end&&r.word===target.word&&r.status==='supported'&&(r.meaning===null||typeof r.meaning==='string'&&r.meaning.length<=240)&&typeof r.explanation==='string'&&r.explanation.length<=320&&(r.spelling===null||replace&&typeof r.spelling==='string'&&/^[A-Za-z]+(?:['’][A-Za-z]+)?$/.test(r.spelling)&&r.spelling.length<=64)) {setReply({meaning:reviewed?null:r.meaning,explanation:r.explanation,spelling:r.spelling});setNotice('');}
   else setNotice(unavailable);
  }catch{if(active.current===controller)setNotice(unavailable);}finally{clearTimeout(timer);if(active.current===controller){active.current=null;setBusy(false);}}
 }
 useEffect(()=>()=>{active.current?.abort();active.current=null;},[]);
 return <div className="g-additional-word">{!reply&&<p role="status">{notice||(reviewed?'':unavailable)}</p>}{reply&&<><p>{reply.spelling?<>Did you mean <strong>{reply.spelling}</strong>?</>:null}</p>{reply.meaning&&<p>{reply.meaning}</p>}<p>{reply.explanation}</p>{reply.spelling&&<><button className="g-secondary" onClick={()=>speak(reply.spelling!)}>Hear suggested word</button><button className="g-primary" disabled={store.getSnapshot().save==='conflict'} onClick={()=>{if(store.getSnapshot().save==='conflict')return;store.send({type:'HELP_USED',id:'spelling'});replace?.(reply.spelling!);}}>Use {reply.spelling}</button><button className="g-secondary" onClick={close}>Keep what I wrote</button></>}{!checked&&<button className="g-secondary" onClick={()=>{setChecked(true);void request([reply.meaning,reply.explanation].filter(Boolean).join(' '));}}>Check this explanation</button>}</>}{!reply&&!checked&&<button className="g-secondary" disabled={busy} onClick={()=>void request()}>Ask for word help</button>}{busy&&<button className="g-secondary" onClick={()=>{active.current?.abort();active.current=null;setBusy(false);setNotice(unavailable);}}>Stop word help</button>}</div>;
}
