/** Separately versioned instructions. Earlier source words and IDs remain intact. */
export const stagedBridgeParagraphs=[
 'These are my two reusable footbridge sections. Six posts and two ropes are beside them. The posts support the ropes along the two sides of the walkway. Keep the middle clear for walking. —Grandma',
 'Look for a crossing where both sections together can reach the banks. Place the first section against the near bank. Seat its two near corner posts and its two center posts in their marked sockets.',
 'Secure a rope along each side of the first section, from a near corner post to a center post. Wrap each rope around its posts, pull it taut and tie a knot. Both sides must be secure before you put your weight on this section.',
 'Walk onto the secured first section. Bring the second section into place and connect the short ends. Seat the two far corner posts. Extend each rope from its center post to the matching far corner post, then wrap, tighten and tie it.',
 'A section can reach the bank and still be loose. If you step onto an unsecured section, it may slip. Keep the secured part in place and recover the loose materials. You can use the same materials again.',
 'My small boat can carry the seed, but it cannot carry Pip. Load the seed at the yellow launch. Steer around the rock to my blue landing. I will come to collect the seed and bring it to our planting spot. You may also carry the seed across the secured bridge.',
 'Keep the boat’s route clear. When you reach the garden, prepare our planting spot with me, place the seed and cover it with soil. The bridge stays in place so everyone can return.',
 'The seed stays dark in a boat or a hand. Its lantern-flower grows only after its roots reach the garden’s soil.'
] as const;
export const bridgeGlossary:Record<string,string>={
 walking:'Moving on foot.',walk:'Move on foot.',rope:'A strong cord used to fasten something.',post:'An upright support.',pull:'Draw something toward you.',tie:'Fasten something by making a knot.',must:'Shows something necessary for the condition described.',second:'The one after the first.',connect:'Join things together.',short:'Not long.',loose:'Not fastened firmly.',spot:'A particular place.',also:'In addition; another possibility.',cover:'Put something over the top. Here, put soil over the seed.',"garden's":'Belonging to the garden.',
 six:'One more than five.',support:'Hold something up or keep it steady.',walkway:'A path or surface meant for walking.',middle:'The part between the two sides.',near:'Closer to Pip’s starting bank in these instructions.',seat:'Fit something firmly into its intended place.',seated:'Fitted firmly into its intended place.',center:'The place where the two bridge sections meet.',socket:'A fitted opening that holds another part.',sockets:'Fitted openings that hold the posts.',wrap:'Pass something around another object.',taut:'Pulled tight without hanging loose.',knot:'A fastening made by looping and tightening rope.',knots:'Fastenings made by looping and tightening rope.',weight:'The downward force of a person or object.',far:'On the opposite side of the crossing.',extend:'Make something reach farther.',matching:'Corresponding to the same side or position.',tighten:'Pull something until it is firm.',unsecured:'Not fastened firmly in place.',slip:'Slide out of position.',recover:'Get back something so it can be used again.',materials:'The things used to build or repair something.',collect:'Go to get something and bring it back.',erect:'Set something upright.'
};
