import {cancelLocalSpeech} from './audio.js';
import {useEffect,useState,useContext} from 'react';
import type {GardenStore} from './model.js';
import {ReadingContext} from './Reading.js';
import {AdditionalWordHelp} from './AdditionalWordHelp.js';
import {supportedWordHelp} from './readingGlossary.js';
export function DraftReader({store,text,revision,speak,practice}:{store:GardenStore;text:string;revision:number;speak:(text:string)=>void;practice:(text:string,id:string)=>void}){
 const reading=useContext(ReadingContext);
 const [open,setOpen]=useState(false),[again,setAgain]=useState(false),[selected,setSelected]=useState<{word:string;sentence:string;start:number;end:number;button:HTMLButtonElement}|null>(null),[undo,setUndo]=useState<{word:string;replacement:string;start:number;revision:number}|null>(null);
 useEffect(()=>setSelected(null),[revision]);
 useEffect(()=>()=>cancelLocalSpeech(),[open,revision]);
 const close=()=>{setSelected(null);requestAnimationFrame(()=>selected?.button.focus());};
 function replace(replacement:string){if(!selected)return;store.send({type:'STORY',event:{kind:'REPLACE_WORD',revision,start:selected.start,end:selected.end,word:selected.word,replacement}});if(store.getSnapshot().chapter.story.solDraft.revision===revision+1){setUndo({word:replacement,replacement:selected.word,start:selected.start,revision:revision+1});close();}}
 let position=0;
 const wordHelp=selected?supportedWordHelp(selected.word,selected.sentence,false,false,true):null;
 return <section className="g-draft-reader"><button className="g-secondary" disabled={!text.trim()} onClick={()=>{setOpen(!open);setSelected(null);}}>Read my ending aloud</button>{open&&<><h3>Your current ending</h3><p>{again?'Choose the words that show why the repair mattered. Try reading those words with more emphasis.':'Read your ending aloud as Sol. Pause at each full stop.'}</p><p>Choose a word if you would like help with its meaning.</p><p className="g-manuscript">{text.split(/([A-Za-z]+(?:['’][A-Za-z]+)?)/g).map((word,index)=>{const start=position;position+=word.length;if(!/^[A-Za-z]/.test(word))return word;let offset=0;const sentence=(text.match(/[^.!?]+[.!?]?/g)??[text]).find(p=>{offset+=p.length;return start<offset;})?.trim()??text;return <button className="g-word" key={index} onClick={e=>{cancelLocalSpeech();setSelected({word,sentence,start,end:start+word.length,button:e.currentTarget});store.send({type:'HELP_USED',id:'word:own-draft'});}}>{word}</button>;})}</p>
  {selected&&<aside className="g-draft-word" aria-label={'Your word: '+selected.word}><h3>{selected.word}</h3><p>{wordHelp?.definition}</p><p>{selected.sentence}</p><AdditionalWordHelp key={revision+':'+selected.start} target={{source:null,paragraph:0,draft:text,revision,start:selected.start,end:selected.end,word:selected.word,sentence:selected.sentence}} reviewed={wordHelp?.definition} store={store} speak={speak} replace={replace} close={close}/><div className="g-row"><button className="g-secondary" onClick={()=>speak(selected.word)}>Hear the word</button><button className="g-secondary" onClick={()=>speak(selected.sentence)}>Hear the sentence</button><button className="g-secondary" onClick={close}>Back to reading my ending</button></div></aside>}
  {undo&&undo.revision===revision&&<button className="g-secondary" onClick={()=>{store.send({type:'STORY',event:{kind:'REPLACE_WORD',revision,start:undo.start,end:undo.start+undo.word.length,word:undo.word,replacement:undo.replacement}});setUndo(null);setSelected(null);}}>Undo spelling change</button>}
  <div className="g-row"><button className="g-secondary" onClick={()=>speak(text)}>Hear this part</button><button className="g-secondary" onClick={()=>cancelLocalSpeech()}>My turn</button><button className="g-secondary" onClick={()=>{cancelLocalSpeech();setAgain(true);}}>Read it again</button><button className="g-secondary" onClick={event=>reading?reading.practice(text,'sol-draft-'+revision,event.currentTarget,'child-draft'):practice(text,'sol-draft-'+revision)}>Read with feedback</button><button className="g-secondary" onClick={()=>{setOpen(false);setSelected(null);document.querySelector<HTMLTextAreaElement>('#sol-ending')?.focus();}}>Back to my ending</button></div>
 </>}</section>;
}
