import {FestivalWelcome,FestivalIntroduction} from './FestivalWelcome.js';
import './playback.css';
import {StoryReadingTools} from './StoryReadingTools.js';
import {readingPages} from './readingPages.js';
import {supportedWordHelp} from './readingGlossary.js';
import {ConversationControls,MaraChoices} from './ConversationControls.js';
import {accountReading,activeConversation,conversationParts,conversationProgress,conversationReady,conversationPresent,needsDockService,sourceVoice,sourceNarration,readerStep} from './conversation.js';
import {cancelLocalSpeech,localSpeech,localSpeechVersion,onLocalSpeechCanceled} from './audio.js';
import {GatheringControls} from './GatheringPanels.js';
import {connectedGathering,gatheringAction,gatheringInstruction,type SpokenLine} from './gathering.js';
import {BakeryConversation} from './BakeryConversation.js';
import {BakeryControls} from './BakeryControls.js';
import {bakeryReady,nearBakery,bakeryInstruction,solAtWorkshop,BAKERY_APPROACH} from './bakery.js';
import {useCallback,useEffect,useLayoutEffect,useRef,useState,useSyncExternalStore,type ReactNode} from 'react';
import {GardenScene} from './GardenScene.js';
import {createGarden,sceneDescription} from './persistence.js';
import {type SourceId,type Panel,type Point,MARA,GRANDMA,GRANDMA_APPROACH,CROSSING,distance,bridgeReady,bridgeCenter,riverHalf,reaches,GAP,LOOSE,encounterDone} from './model.js';
import {sources,normalize,wordHelp,sourcePrefix} from './content.js';
import {ChapterContent,Choices,Reply} from './ChapterPanels.js';
import {AdditionalWordHelp} from './AdditionalWordHelp.js';
import {ReadingSession} from './ReadingSession.js';
import {chapterGoal,SOL_APPROACH,solApproach,solPosition,maraAtGarden,GATHER_MARA,gatheringStarted} from './chapter.js';
import {bridgeAttemptable} from './model.js';
import {readerReturnLabel,roleText} from './interaction.js';
import {captureFocus,restoreViewFocus} from './focus.js';
import {WorldActivityView} from './WorldActivity.js';
import {lanternIds,lanternRecord} from './lanterns.js';
import {ropeCount} from './river.js';
import {MaraWorld} from './MaraWorld.js';
import {birdInstruction} from './mara.js';
import {BoatControls} from './BoatControls.js';
import {ReadingContext,ReadingParagraph,ConversationReadingTools,type ReadingOrigin} from './Reading.js';
import './garden.css';
const movement=new Set(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d']);
function Icon({kind}:{kind:'leaf'|'book'|'bag'|'sound'|'help'|'pause'|'arrow'|'check'|'spark'}){
 const paths={leaf:'M19 4C8 2 3 8 5 15s14 3 14-11ZM5 19 15 9',book:'M3 5c4-2 7-1 9 1 2-2 5-3 9-1v14c-4-2-7-1-9 1-2-2-5-3-9-1V5Zm9 1v14',bag:'M7 7V5a5 5 0 0 1 10 0v2M5 7h14l1 14H4L5 7Zm3 6h8v5H8v-5',sound:'M4 9h4l5-4v14l-5-4H4V9Zm12-2a7 7 0 0 1 0 10m3-13a11 11 0 0 1 0 16',help:'M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 4m0 3v.1M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',pause:'M8 5v14M16 5v14',arrow:'M4 12h15m-6-6 6 6-6 6',check:'m5 12 4 4L19 6',spark:'m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5L12 2'};
 return <svg viewBox="0 0 24 24" className="g-icon" aria-hidden="true"><path d={paths[kind]} fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}
function Tag({children}:{children:ReactNode}){return <span className="g-kicker">{children}</span>;}
export function App(){
 const [{store,saves,dispose}]=useState(createGarden);
 const s=useSyncExternalStore(store.subscribe,store.getSnapshot),c=s.chapter;
 const [viewKey,setViewKey]=useState(0),[word,setWord]=useState<{word:string;sentence:string;button:HTMLButtonElement;draft?:string;component?:string;title?:boolean;source?:string;paragraph?:number;start?:number;end?:number;origin?:ReadingOrigin}|null>(null);
 const [audio,setAudio]=useState(''),[speaking,setSpeaking]=useState(false),[practice,setPractice]=useState(false);
 useEffect(()=>onLocalSpeechCanceled(()=>setSpeaking(false)),[]);
 const [hintNotice,setHintNotice]=useState(''),[readingTarget,setReadingTarget]=useState<{text:string;id:string;origin:ReadingOrigin;title?:string;onTranscript?:((text:string)=>void)}|null>(null);
 useEffect(()=>{setHintNotice('');},[c.runId]);
 const voiceSequence=useRef(0),practiceFocus=useRef<HTMLElement|null>(null);
 const closePractice=()=>{setReadingTarget(null);requestAnimationFrame(()=>practiceFocus.current?.focus());};
 const conversation=activeConversation(s),conversationState=conversation?conversationProgress(c,conversation):null;
 const conversationPart=conversationState?.part??null,conversationPending=!!conversation&&conversationPart!<conversationParts[conversation].length;
 const dockFirst=s.panel==='mara'&&!accountReading(s)&&conversationPresent(s,'mara')&&c.story.phase==='planning'&&needsDockService(c);
 const remoteAccount=accountReading(s);
 const readingKey=readerStep(s);
 const previousReader=useRef({panel:s.panel,key:readingKey});
 const dialog=useRef<HTMLElement>(null),scroll=useRef<HTMLDivElement>(null);
 const failView=useCallback(()=>store.send({type:'VIEW_LOST',lost:true}),[store]);
 const speak=useCallback((text:string,onDone?:()=>void)=>{
  const sequence=++voiceSequence.current;
  cancelLocalSpeech();const version=localSpeechVersion(),valid=()=>voiceSequence.current===sequence&&localSpeechVersion()===version;const synthesis=localSpeech(),Utterance=globalThis.SpeechSynthesisUtterance,voice=synthesis?.getVoices().find(v=>v.localService&&v.lang.startsWith('en'));
  if(!synthesis||!voice||typeof Utterance!=='function'){setAudio("The model reading isn't available right now. You can still read the words or return to the story.");setSpeaking(false);return;}
  const parts=readingPages(text);let index=0;const play=()=>{if(!valid())return;const utterance=new Utterance(parts[index]!.text);utterance.voice=voice;utterance.lang=voice.lang;utterance.rate=.9;utterance.onend=()=>{if(!valid())return;if(++index<parts.length)play();else{setSpeaking(false);onDone?.();}};utterance.onerror=event=>{if(!valid())return;setSpeaking(false);if(event.error==='canceled'||event.error==='interrupted')return;setAudio("The model reading isn't available right now. You can still read the words or return to the story.");};synthesis.speak(utterance);};setAudio('');setSpeaking(true);play();store.send({type:'HELP_USED',id:'model'});
 },[store]);
 const stopAudio=()=>{voiceSequence.current++;cancelLocalSpeech();setSpeaking(false);};
 function inspectScreen(opener:HTMLElement){
  const root=document.querySelector(s.panel?'.garden-reader':'.garden-app');
  const blocks=Array.from(root?.querySelectorAll<HTMLElement>('h1,h2,h3,p,small,blockquote,.g-speaker,[data-readable-text],.g-item strong,.garden-save-error>span,button:not(.g-word),summary,legend')??[]).filter(n=>n.getClientRects().length&&!n.closest('.garden-header,.g-reading-tools,.g-choice-reading')&&!n.parentElement?.closest('blockquote,p,[data-readable-text]'));
  const text=[...(!s.panel?[feedback]:[]),...blocks.map(n=>{if(n.matches('button'))return n.getAttribute('aria-label')??n.textContent??'';const copy=n.cloneNode(true) as HTMLElement;copy.querySelectorAll('.g-reading-tools').forEach(tool=>tool.remove());return copy.textContent??'';})].map(t=>t.trim()).filter(Boolean);
  store.send({type:'INSPECT_TEXT',text:text.slice(0,200),focus:captureFocus(opener)});
 }
 function restart(){if(confirm('Start a new adventure? This adventure will be kept in a local archive.')){stopAudio();store.send({type:'INTERRUPT'});void saves.newAdventure();}}
 useEffect(()=>{document.title='The Garden Adventure · Evidence Quest';void localSpeech()?.getVoices();return()=>{cancelLocalSpeech();dispose();};},[dispose]);
 const open=useCallback((panel:Panel,origin?:Element)=>{store.send({type:'OPEN',panel,focus:captureFocus(origin)});},[store]);
 const close=useCallback(()=>{cancelLocalSpeech();setSpeaking(false);setWord(null);setPractice(false);setReadingTarget(null);store.send({type:'CLOSE'});},[store]);
 const nearMara=distance(c.pip,maraAtGarden(c)?GATHER_MARA:MARA)<1.5,nearGrandma=distance(c.pip,GRANDMA)<1.25,nearSections=distance(c.pip,CROSSING)<1.6,nearSol=distance(c.pip,solPosition(c))<1.5;
 const go=(target:'mara'|'grandma'|'sections'|'sol')=>store.send({type:'GO',point:target==='sol'?solApproach(c):target==='mara'?(maraAtGarden(c)?{x:3.35,z:.4}:{x:-3.5,z:-3.05}):target==='grandma'?GRANDMA_APPROACH:CROSSING,target:target==='sections'?'the bridge pieces':target==='mara'?'Mara':target==='sol'?'Sol':'Grandma'});
 const talk=(who:'mara'|'grandma'|'sol',origin?:Element)=>store.send({type:'TALK',who,focus:captureFocus(origin)});
 useEffect(()=>{
  const down=(e:KeyboardEvent)=>{
   const key=e.key.toLowerCase(),target=e.target as HTMLElement;
   if(key==='escape'){e.preventDefault();cancelLocalSpeech();setSpeaking(false);if(word){setWord(null);requestAnimationFrame(()=>word.button.focus());return;}if(readingTarget){closePractice();return;}if(s.panel){close();return;}if(s.activity){store.send({type:'ACTIVITY_BACK'});return;}if(s.preview||s.bakeryPreview||c.mara.scene?.preview){store.send({type:'CANCEL'});return;}if(s.mode==='bakery-repair'){store.send({type:'BAKERY_STEP',step:'BACK'});return;}if(s.mode==='arrange'){store.send({type:'BACK'});return;}store.send({type:'INTERRUPT'});return;}
   if(target.matches('input,textarea,select,[contenteditable=true]')||s.panel)return;
   if(s.activity){if(key==='i'){e.preventDefault();open('backpack');}return;}
   if(s.mode==='arrange'&&key==='enter'&&s.preview&&(target.closest('.g-select-sections,.g-move-grid,.garden-scene')||!target.closest('button,summary,a'))){e.preventDefault();store.send({type:'PLACE'});return;}
   if(target.closest('button,summary,a')&&(key==='enter'||key===' '))return;
   if(s.mode==='arrange'&&movement.has(key)){e.preventDefault();const v:{[key:string]:Point}={arrowleft:{x:-.1,z:0},a:{x:-.1,z:0},arrowright:{x:.1,z:0},d:{x:.1,z:0},arrowup:{x:0,z:-.1},w:{x:0,z:-.1},arrowdown:{x:0,z:.1},s:{x:0,z:.1}};store.send({type:'NUDGE',...v[key]!});return;}
   if(movement.has(key)){e.preventDefault();store.send({type:'KEY',key,down:true});}
   if(key==='i'){e.preventDefault();open('backpack');}
   if(key==='e'){e.preventDefault();if(nearMara)talk('mara');else if(nearGrandma)talk('grandma');else if(nearSol)talk('sol');else if(nearSections)open('sections');}
  };
  const up=(e:KeyboardEvent)=>{const key=e.key.toLowerCase();if(movement.has(key))store.send({type:'KEY',key,down:false});};
  window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);};
 },[store,s.panel,s.mode,s.preview,s.bakeryPreview,c.mara.scene?.preview,s.activity,word,readingTarget,nearMara,nearGrandma,nearSections,nearSol,close,open]);
 useLayoutEffect(()=>{const newDecision=previousReader.current.panel===s.panel&&previousReader.current.key!==readingKey;previousReader.current={panel:s.panel,key:readingKey};setWord(null);setPractice(false);setReadingTarget(null);setAudio('');cancelLocalSpeech();setSpeaking(false);const root=dialog.current??document.querySelector<HTMLElement>(c.gathering.turn||c.story.phase==='arriving'?'.garden-gathering-controls':s.mode==='bakery-repair'?'.garden-bakery-controls':s.mode==='mara-story'?'.garden-mara-play':s.activity?'.garden-world-activity':!c.started?'.festival-welcome':'.garden-action-bar');if(root)restoreViewFocus(newDecision?null:s.restoreFocus,root);},[s.panel,s.mode,c.story.phase,s.activity?.id,c.gathering.turn?.kind,conversationPart,dockFirst,readingKey]);
 useEffect(()=>{if(word){word.button.closest('p')?.scrollIntoView({block:'nearest'});dialog.current?.querySelector<HTMLElement>('.garden-word-card .g-close')?.focus();}},[word]);
 useEffect(()=>{
  const root=scroll.current;if(!root||!s.panel||word||readingTarget)return;
  function collect(){const box=root!.getBoundingClientRect(),known=new Set(store.getSnapshot().chapter.exposed),ids:string[]=[];for(const token of root!.querySelectorAll<HTMLElement>('[data-source-word]')){const r=token.getBoundingClientRect(),id=token.dataset['sourceWord']!;if(r.height&&r.top>=box.top-1&&r.bottom<=box.bottom+1&&r.left>=box.left-1&&r.right<=box.right+1&&!known.has(id)){ids.push(id);known.add(id);}}
   for(const p of root!.querySelectorAll<HTMLElement>('[data-source-component]')){const id=p.dataset['sourceComponent']!,tokens=Array.from(p.querySelectorAll<HTMLElement>('[data-source-word]'));if(tokens.length&&tokens.every(t=>known.has(t.dataset['sourceWord']!))&&!known.has(id))ids.push(id);}if(ids.length)store.send({type:'EXPOSE_WORDS',ids});}
  const observer=new ResizeObserver(collect);observer.observe(root);root.addEventListener('scroll',collect);const frame=requestAnimationFrame(collect);return()=>{observer.disconnect();root.removeEventListener('scroll',collect);cancelAnimationFrame(frame);};
 },[s.panel,store,practice,word,readingTarget,c.story.phase,conversationPart,dockFirst,readingKey]);
 useEffect(()=>{if(scroll.current&&readingKey)scroll.current.scrollTop=c.reading[readingKey]??0;},[readingKey,practice]);
 const committed=!remoteAccount&&!conversationPending&&(s.panel==='mara'&&(c.page!=='mara'||c.mara.asking!=='none'||!!c.story.plan||c.story.maraReported)||s.panel==='sol'&&c.story.solChoice!=='none'||s.panel==='bakery'&&c.bakery.stage!=='arrival');
 const source=s.panel==='sol'&&c.story.records.sol||dockFirst||committed||s.panel==='report'||s.panel==='mara'&&!remoteAccount&&c.story.phase!=='planning'?null:s.panel==='birdTalk'?sources.story:s.panel&&s.panel in sources?sources[s.panel as SourceId]:null;
 function paragraph(text:string,index:number,id:string){
  let wordIndex=0;const sentenceParts=text.match(/[^.!?]+[.!?]?/g)??[text];let cursor=0;
  return <div className="g-source-part" key={id+index}>{id in sources&&sourceVoice(id as SourceId,index)&&<p className="g-source-voice">{sourceVoice(id as SourceId,index)}</p>}<p data-source-component={sourcePrefix(id)+(index+1)}>
   {text.split(/([A-Za-z]+(?:['’][A-Za-z]+)?)/g).map((token,i,parts)=>{
    const offset=cursor;cursor+=token.length;if(!/^[A-Za-z]/.test(token))return token;
    const n=wordIndex++;let end=0;const sentence=sentenceParts.find(part=>{end+=part.length;return offset<end;})?.trim()??text;
    const trailing=parts[i+1]?.match(/^[.,!?";:]+/)?.[0]??'';if(trailing){parts[i+1]=parts[i+1]!.slice(trailing.length);cursor+=trailing.length;}
    const phrase=word?.component===id+index?wordHelp(word.word,word.sentence).phrase:null,phraseStart=phrase?text.indexOf(phrase):-1;
    return <span className={'g-word-token '+(phrase&&offset>=phraseStart&&offset<phraseStart+phrase.length?'g-phrase-highlight':'')} key={i} data-source-word={sourcePrefix(id)+(index+1)+'.W'+(n+1)}><button className={'g-word '+(['obligation','secure','hesitated','mended','promised'].includes(normalize(token))?'g-focus-word':'')} tabIndex={n===0?0:-1}
     onClick={e=>{stopAudio();setWord({word:token,sentence,button:e.currentTarget,component:id+index,...(id in sources?{source:id}:{draft:text}),paragraph:index,start:offset,end:offset+token.length});store.send({type:'HELP_USED',id:'word:'+id+':'+normalize(token)});}}
     onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();e.stopPropagation();const buttons=Array.from(e.currentTarget.closest('p')!.querySelectorAll<HTMLButtonElement>('.g-word'));const next=buttons[buttons.indexOf(e.currentTarget)+(e.key==='ArrowRight'?1:-1)];next?.focus();}}}>{token}</button>{trailing}</span>;
   })}
  </p></div>;
 }
 function trap(e:React.KeyboardEvent){if(!s.panel||e.key!=='Tab')return;const nodes=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled):not([tabindex="-1"]),input,textarea,select,summary,a[href]')).filter(n=>n.offsetParent!==null&&!n.closest('[inert]'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
 const helpCard=word?supportedWordHelp(word.word,word.sentence,c.exposed.includes('GA.SRC.DUET.4')&&c.exposed.includes('GA.SRC.DUET.5'),word.title,!word.source&&!word.title):null;
 const objective=chapterGoal(c),{goal,next}=objective;
 const construct=s.mode==='arrange'&&!s.panel&&!s.activity,disabled=!!s.action||s.viewLost||s.background,readingOnly=!!s.activity||s.mode==='boat'||s.mode==='mara-story'||remoteAccount;
 const bakeryContext=!s.activity&&s.mode!=='mara-story'&&s.mode!=='boat'&&c.started&&c.story.phase==='planning'&&!bakeryReady(c)&&(nearBakery(c)||c.bakery.stage==='escorting');
 const bakeryActive=!s.panel&&bakeryContext;
 const gatheringActive=!s.panel&&s.mode==='walk'&&connectedGathering(c)&&(c.story.phase==='arriving'||!!c.gathering.turn||gatheringAction(s.action?.kind??''));
 const renderText=(line:SpokenLine)=><ReadingParagraph origin={line.origin??'authored-display'}>{line.text}</ReadingParagraph>;
 const backLabel=readerReturnLabel(s);
 const description=sceneDescription(s),gatheringHelp=s.mode==='mara-story'?null:gatheringInstruction(c);
 function showHint(text:string,id:string){setHintNotice(text);store.send({type:'HELP_USED',id});store.send({type:'NOTICE',text});}
 function pointToNext(){const id=objective.target,marker=document.querySelector<HTMLElement>('.garden-scene [data-garden-marker="'+id+'"]');marker?.classList.add('is-pointed');setTimeout(()=>marker?.classList.remove('is-pointed'),3000);showHint(id==='sol'?(solAtWorkshop(c)?'Sol’s workshop is beyond the bench.':'Sol is helping Rina at the bakery. Follow the path to the right, past his workshop.'):id==='mara'?'Mara is at the passenger dock until she has finished work.':id==='sections'?'The wooden bridge pieces are beside the river.':id==='lanterns'?'The lantern flowers around the planting circle hold the garden’s stories.':'Grandma is beside the planting circle.','where-next');}
 function crossingHint(){showHint(s.preview?'Choose Place section to keep the new position, or press Escape to cancel.':bridgeReady(c)?'Both ends are secure. Return to Pip, then walk across.':c.joined&&riverHalf(bridgeCenter(c).z)>1.55?"The sections won't reach across here. Look along the river for a place where the banks are closer together.":c.joined&&reaches(c,'west')&&reaches(c,'east')?(c.west||c.east?LOOSE:'Fasten one end to each bank before Pip crosses.'):c.joined?GAP:c.seed==='grandma'?'Grandma has the seed, but Pip still needs to cross. Join and fasten the two bridge sections.':'Bring the short ends of the bridge sections together. Turn them to face the same way.','crossing-hint');}
 const practicePart=(text:string,id:string,opener?:HTMLElement,origin:ReadingOrigin='authored-display',title?:string)=>{practiceFocus.current=opener??document.activeElement as HTMLElement;stopAudio();setReadingTarget({text,id,origin,...(title?{title}:{})});};
 const shownParagraphs=source?source.paragraphs.map((text,index)=>({text,index})).filter(({index})=>s.panel==='birdTalk'?index<=5:conversation?conversationParts[conversation][Math.min(conversationPart!,conversationParts[conversation].length-1)]!.some(i=>i===index):true):[];
 const renderSource=(id:SourceId,index?:number)=>sources[id].paragraphs.flatMap((p,i)=>index===undefined||index===i?[paragraph(p,i,id)]:[]);
 const feedback=s.notice||(s.mode==='mara-story'?birdInstruction(s):bakeryActive?bakeryInstruction(s):s.activity?s.activity.kind==='ending-rehearsal'?'Choose these words for Sol, or return to your draft.':s.activity.kind==='lantern-inspect'?'Read this flower’s story with help, or return to Pip.':s.activity.kind==='ending-presentation'?'Loop plays the whole story. Pause, replay or open the full text with reading help.':'Confirm this plan with Grandma, or return to change it.':next),isHint=!!hintNotice&&hintNotice===s.notice;
 return <ReadingContext.Provider value={s.panel?{word:target=>{stopAudio();setWord(target);store.send({type:'HELP_USED',id:'word:dialogue:'+normalize(target.word)});},speak,practice:practicePart,compose:(text,id,opener,onTranscript)=>{practiceFocus.current=opener;stopAudio();setReadingTarget({text,id,origin:'mixed-display',onTranscript});},stop:stopAudio,speaking}:null}><main className={'garden-app '+(c.largeText?'garden-large ':'')+(c.largestText?'garden-largest ':'')+(c.roomierText?'garden-roomier ':'')+(c.reducedMotion?'garden-reduced-motion ':'')+(s.panel?'has-reader ':'')+(!c.started?'in-studio':'')} role={s.panel?'dialog':undefined} aria-modal={s.panel?true:undefined} aria-labelledby={s.panel?'garden-reader-title':undefined} onKeyDown={trap}>
  <header className="garden-header"><a href="/garden" className="garden-brand" aria-label="Garden Adventure" inert={!!s.panel} aria-hidden={!!s.panel}><span className="garden-seal"><Icon kind="leaf"/></span><span>Evidence Quest<span className="garden-brand-sub">THE GARDEN ADVENTURE</span></span></a>
   <div className="garden-header-right"><span className="g-save" aria-live="polite">{s.save==='saved'&&s.savedRevision>=c.revision?'Saved in this browser':s.save==='saving'?'Saving…':s.save==='loading'?'Opening your adventure…':''}</span>
    <nav className="garden-tools" aria-label={s.panel?'Reading tools':'Game tools'} inert={!!word||!!readingTarget}>
     <button className="g-icon-button" aria-label="Backpack" title="Backpack" onClick={e=>open('backpack',e.currentTarget)} disabled={!c.started||s.panel==='backpack'}><Icon kind="bag"/><span>Backpack</span>{c.page==='pip'&&<i className="g-dot"/>}</button>
     <button className="g-icon-button" aria-label="Read what’s on screen" title="Reading help for these words and choices" disabled={!c.started||!!s.action||!!s.readingInspection||s.panel==='help'} onClick={e=>inspectScreen(e.currentTarget)}><Icon kind="book"/><span>Read screen</span></button>
     <button className="g-icon-button" aria-label="Help" title="Help" onClick={e=>open('help',e.currentTarget)} disabled={s.panel==='help'}><Icon kind="help"/><span>Help</span></button>
     <button className="g-icon-button" aria-label="Pause" title="Pause" onClick={e=>open('pause',e.currentTarget)} disabled={s.panel==='pause'}><Icon kind="pause"/><span>Pause</span></button>
    </nav>
   </div>
  </header>
  {['failed','conflict','damaged','version'].includes(s.save)&&<div className="garden-save-error" role="alert">
   <span>{s.save==='failed'?"Your latest changes haven't been saved yet. Keep this page open and try saving again.":s.save==='conflict'?'Another window has newer progress. Load it before making more saved changes.':s.save==='version'?'This saved adventure belongs to a different content version. It has been kept safely.':'The latest save could not be read. Your earlier progress has been kept.'}</span>
   {s.save==='failed'&&<button onClick={()=>void saves.retry()}>Retry save</button>}{s.save==='conflict'&&<button onClick={()=>void saves.takeControl()}>Load latest progress</button>}
   {saves.canRestore()&&['damaged','version'].includes(s.save)&&<button onClick={()=>void saves.restorePrevious()}>Restore previous save</button>}
  </div>}
  {c.started&&!s.panel&&<div className="garden-status garden-feedback" role="status" aria-live="polite" aria-atomic="true">
   <div className="garden-feedback-content" key={feedback}><span className="garden-feedback-icon"><Icon kind={isHint?'help':s.action?'spark':'leaf'}/></span><div><strong>{isHint?'Hint':'What’s happening'}</strong><p>{feedback}</p></div></div>
  </div>}
  <div className={'garden-play-area '+(construct?'is-constructing':s.mode==='boat'?'is-boat':bakeryActive?'is-bakery':gatheringActive?'is-gathering':'')}>
   <div className="garden-world" inert={!!s.panel}>
    {s.mode==='mara-story'&&c.mara.scene?<MaraWorld key={viewKey} s={s} store={store} onError={failView} onRestore={()=>{store.send({type:'VIEW_LOST',lost:false});setViewKey(k=>k+1);}}/>:s.activity?<WorldActivityView s={s} store={store} open={open} speak={speak} audio={audio} speaking={speaking} stopAudio={stopAudio}/>:<>
    {c.started&&<GardenScene key={viewKey} store={store} onError={failView}/>}
    {!c.started&&s.ready&&<FestivalWelcome onBegin={()=>store.send({type:'BEGIN'})} onReadHelp={opener=>open('festival',opener)} disabled={['damaged','version'].includes(s.save)}/>}
    {c.started&&!s.panel&&s.mode!=='boat'&&s.mode!=='arrange'&&!bakeryActive&&!gatheringActive&&s.action?.kind!=='keepMemory'&&s.action?.kind!=='dockService'&&!(distance(c.pip,solPosition(c))<2.1&&['escorting','done'].includes(c.bakery.stage)&&!gatheringStarted(c))&&<aside className="garden-goal"><Tag>YOUR ADVENTURE</Tag><h1>{goal}</h1><p>{next}</p><button className="g-hint-button" onClick={pointToNext}><Icon kind="help"/> Where is that?</button></aside>}
    {construct&&<div className="garden-director"><Icon kind="spark"/><span>DIRECTOR MODE</span><span>Pip waits on the bank.</span></div>}
    {c.started&&!s.panel&&<span className="garden-location"><span className="g-location-dot"/>{nearBakery(c)?'Rina’s bakery':c.pip.x<0?'The riverbank':'Grandma’s garden'}</span>}
    {c.started&&!s.panel&&s.mode!=='boat'&&<details className="garden-access" open={!!s.viewDrafts.disclosures['world-places']} onToggle={e=>store.send({type:'DISCLOSURE',id:'world-places',open:e.currentTarget.open})}><summary>Places & scene description</summary><p>{description}</p><div className="g-row"><button onClick={()=>go('mara')}>Go to Mara</button><button onClick={()=>go('sections')}>Go to the bridge pieces</button><button onClick={()=>go('grandma')}>Go to Grandma</button><button onClick={()=>go('sol')}>Go to Sol</button>{c.crossed&&<button onClick={e=>open('lanterns',e.currentTarget)}>Open lantern stories</button>}{(nearSections||nearGrandma)&&(c.seed!=='pip'||c.crossed)&&<button onClick={()=>store.send({type:'FERRY'})}>Watch the empty seed boat</button>}</div>{c.crossed&&<details open={!!s.viewDrafts.disclosures['world-flowers']} onToggle={e=>store.send({type:'DISCLOSURE',id:'world-flowers',open:e.currentTarget.open})}><summary>Inspect a particular flower</summary><div className="g-row">{lanternIds.filter(id=>id!=='pip'||c.bloomed).map(id=><button key={id} onClick={e=>store.send({type:'INSPECT_LANTERN',lantern:id,focus:captureFocus(e.currentTarget)})}>{lanternRecord(c,id).title} · {lanternRecord(c,id).author}</button>)}</div></details>}</details>}
    {s.viewLost&&<div className="garden-view-error" role="alert"><h2>The garden view needs a moment.</h2><p>Your saved story is still here.</p><button onClick={()=>{store.send({type:'VIEW_LOST',lost:false});setViewKey(k=>k+1);}}>Restore view</button><button onClick={e=>open('help',e.currentTarget)}>Read the story so far</button></div>}
    </>}
   </div>
   {gatheringActive&&<GatheringControls s={s} store={store} open={open}/>}
  {bakeryActive&&<BakeryControls s={s} store={store}/>}
   {s.mode==='boat'&&!s.panel&&<BoatControls s={s} store={store}/>}
   {construct&&<aside className="garden-builder" aria-label="Arrange the bridge pieces" aria-busy={!!s.action}>
    <Tag>REPAIR THE FOOTBRIDGE</Tag><h2>Two sections.<br/>One way across.</h2><p className="g-builder-instruction">Grandma’s two sections can make a footbridge. Place them between the opposing posts, join their short ends and fasten both banks.</p><p className="g-small">{ropeCount(c,'box')?`${ropeCount(c,'box')} repair ${ropeCount(c,'box')===1?'rope remains':'ropes remain'} in Grandma’s box.`:`${ropeCount(c,'pip')} repair ropes in Pip’s backpack. ${ropeCount(c,'attached')} attached to the bridge.`}</p>{ropeCount(c,'box')>0&&<button className="g-secondary" disabled={disabled} onClick={()=>store.send({type:'COLLECT_ROPES'})}>Take the repair ropes</button>}
    <button className="g-hint-button" onClick={crossingHint}><Icon kind="help"/> Give me a hint</button>
    <button className="g-text-button" onClick={e=>open('sections',e.currentTarget)}><Icon kind="book"/> Read the crossing note</button>
    <div className="g-select-sections"><button disabled={disabled} onClick={()=>store.send({type:'SELECT',section:'a'})} aria-pressed={s.selection==='a'}>Section A</button><button disabled={disabled} onClick={()=>store.send({type:'SELECT',section:'b'})} aria-pressed={s.selection==='b'}>Section B</button></div>
    <span className="g-small">{c.joined?'Moving both joined sections':'Selected: Section '+s.selection.toUpperCase()}</span>
    <div className="g-post-choices" aria-label="Preview section at a crossing post"><strong>Place between the posts</strong><button disabled={disabled} onClick={()=>store.send({type:'POST_PREVIEW',site:'narrow',side:'west'})}>Narrow crossing · dock-side post</button><button disabled={disabled} onClick={()=>store.send({type:'POST_PREVIEW',site:'narrow',side:'east'})}>Narrow crossing · garden-side post</button><button disabled={disabled} onClick={()=>store.send({type:'POST_PREVIEW',site:'wide',side:'west'})}>Try the wide crossing</button></div><div className="g-move-grid"><button disabled={disabled} aria-label="Move section up" onClick={()=>store.send({type:'NUDGE',x:0,z:-.1})}>↑</button><button disabled={disabled} aria-label="Move section left" onClick={()=>store.send({type:'NUDGE',x:-.1,z:0})}>←</button><button disabled={disabled} aria-label="Move section right" onClick={()=>store.send({type:'NUDGE',x:.1,z:0})}>→</button><button disabled={disabled} aria-label="Move section down" onClick={()=>store.send({type:'NUDGE',x:0,z:.1})}>↓</button></div>
    <div className="g-row"><button className="g-secondary" disabled={disabled||c.joined||!!s.preview} onClick={()=>store.send({type:'ROTATE',direction:-1})}>↶ Turn</button><button className="g-secondary" disabled={disabled||c.joined||!!s.preview} onClick={()=>store.send({type:'ROTATE',direction:1})}>Turn ↷</button></div>
    {s.preview&&<button className="g-primary" disabled={disabled} onClick={()=>store.send({type:'PLACE'})}>Place section <kbd>Enter</kbd></button>}
    <button className="g-primary" disabled={disabled||c.joined||!!s.preview} onClick={()=>store.send({type:'JOIN'})}>{c.joined?'Sections joined':'Join sections'}</button>
    <div className="g-attachments"><button onClick={()=>store.send({type:'FASTEN',end:'west'})} disabled={disabled||!c.joined||c.west}><span>{c.west?'✓':'○'}</span> Fasten dock-side end</button><button onClick={()=>store.send({type:'FASTEN',end:'east'})} disabled={disabled||!c.joined||c.east}><span>{c.east?'✓':'○'}</span> Fasten garden-side end</button></div>
    {(c.west||c.east)&&<button className="g-text-button" disabled={disabled} onClick={()=>store.send({type:'ADJUST'})}>Release ropes to move sections</button>}
    <button className="g-secondary" onClick={()=>store.send({type:'BACK'})}>Back to Pip <Icon kind="arrow"/></button>
   </aside>}
   {s.panel&&<section className={'garden-reader '+(['writing','lanterns','studio'].includes(s.panel)?'g-wide-reader':'')} ref={dialog}>
    <div className="g-reader-top" inert={!!readingTarget||!!word}><Tag>{source?.id==='sol'?'Sol’s original draft':source?.author??(s.panel==='grandma'?'GRANDMA’S GARDEN':s.panel==='help'?'A HAND WHEN YOU NEED IT':'YOUR ADVENTURE')}</Tag><button className="g-close" aria-label={'Close page. '+backLabel} onClick={close}>×</button></div>
    <h2 inert={!!readingTarget||!!word} id="garden-reader-title" tabIndex={-1}>{s.panel==='duet'?<>The Unexpected <button className="g-word g-title-word" onClick={e=>{stopAudio();setWord({word:'Duet',sentence:'The Unexpected Duet',button:e.currentTarget,title:true});store.send({type:'HELP_USED',id:'word:duet:title'});}}>Duet</button></>:({festival:'SparkFest and Loop',mara:source?.title??'At Mara’s dock',sol:c.story.records.sol?'A Small Repair':source?.title??'A conversation with Sol',bakery:source?.title??'At Rina’s bakery',endingWords:'Pip’s adventure',writing:'Finish a story with Sol',planner:'A gathering that works',gathering:'Stories in the garden',lanterns:'The garden’s stories',studio:'Loop’s picture show'}[s.panel as string]??source?.title??(s.panel==='report'?'Tell Grandma what you learned':s.panel==='grandma'?'A visit with Grandma':s.panel==='backpack'?'Pip’s backpack':s.panel==='help'?(s.readingInspection?'Read what’s on screen':'A little help'):s.panel==='complete'?'A promise kept.':'Take your time.'))}</h2>
    <p className="g-reader-context" hidden={!!word||!!readingTarget}>{s.mode==='bakery-repair'?'You direct Sol’s roof repair; Pip waits beside the ladder':s.mode==='mara-story'?'Mara’s earlier story · You guide Mara; Pip stays in the garden':s.activity?.kind==='lantern-inspect'?'Reading help · Return to the same lantern when you are ready':s.activity?.kind==='ending-presentation'?'Reading help · Loop is waiting at this picture':s.activity?'Reading help · Your preview is paused':remoteAccount?'Rereading an earlier account · Pip stays where you left him':s.panel==='festival'?'SparkFest’s story studio · Meet Jo and Loop':s.panel==='backpack'?'Pip’s carried things and their pages':s.panel==='help'||s.panel==='pause'?roleText(s):'Read here, then choose what Pip says or does.'}</p>
    <div className="garden-reading-scroll" inert={!!readingTarget||!!word} ref={scroll} onScroll={e=>{if(readingKey)store.send({type:'READ_POSITION',id:readingKey,position:e.currentTarget.scrollTop});}}>
     <ConversationReadingTools root={scroll}/>
     {source&&<><ReadingParagraph className="g-reading-tip"><Icon kind="book"/> Click a word for its meaning and pronunciation.</ReadingParagraph>
      {sourceNarration[source.id]&&<ReadingParagraph className="g-source-context">{sourceNarration[source.id]}</ReadingParagraph>}
      <div className="garden-passage">{shownParagraphs.map(({text,index})=>paragraph(text,index,source.id))}</div>
      {s.panel==='mara'&&conversation&&!conversationPending&&<ReadingParagraph className="g-small">Mara’s page is called <em>The Torn Wing</em>. {c.page==='pip'?'Pip is carrying her copy.':c.page==='grandma'?'Grandma has her copy.':''}</ReadingParagraph>}
     </>}
     {audio&&!word&&<ReadingParagraph role="status" className="g-audio-notice">{audio}</ReadingParagraph>}
     {source&&!practice&&(['story','empty','picnic','duet'].includes(source.id)||source.id==='sol'&&remoteAccount)?<StoryReadingTools chapter={c} id={source.id as 'story'|'empty'|'picnic'|'duet'|'sol'}/>:source&&!practice&&(source.id!=='sol'||conversationPending)&&<div className="g-row g-reading-actions"><button className="g-text-button" onClick={()=>speaking?stopAudio():speak(shownParagraphs.map(p=>p.text).join(' '))}><Icon kind="sound"/>{speaking?'Stop listening':'Hear this page'}</button><button className="g-text-button" onClick={()=>{practicePart(shownParagraphs[0]!.text,source.id+'-practice');store.send({type:'HELP_USED',id:'oral-practice:'+source.id});}}>Read a short part aloud</button></div>}

     {s.panel==='festival'&&<FestivalIntroduction/>}
     {s.panel==='help'&&<button className="g-secondary" onClick={e=>open('festival',e.currentTarget)}>About SparkFest and Loop</button>}
     {dockFirst&&<><Reply who="Mara">A boat is arriving. I need to help these passengers ashore. We can talk when they are safely off the boat.</Reply><ReadingParagraph>Pip waits at the dock while Mara does her work.</ReadingParagraph></>}
     {s.panel==='mara'&&!remoteAccount&&c.story.phase!=='planning'&&<Reply who="Mara">{c.story.plan?.time==='usual'?(c.story.grandmaCopy==='mara'?'Thank you for bringing Grandma’s story. I’ll read it after work.':c.story.phase==='closed'?'I’m still helping passengers here. I’d like to hear how the gathering went.':'I’m still helping passengers. I’ll stay at the dock while you share stories in the garden.'):'I’m glad we found a time when I could join everyone in the garden.'}</Reply>}
     {s.panel==='bakery'&&!remoteAccount&&!conversationPending&&conversationReady(c,'bakery')&&<BakeryConversation s={s} store={store}/>}
     {s.panel==='sol'&&c.bakery.edition==='earlier-chapter'&&<section className="g-plan-notebook"><h3>Earlier adventure</h3><ReadingParagraph>This save already met Sol before the bakery sequence was added. Its original story is preserved. A new adventure lets you play the repair, baking and visit.</ReadingParagraph><button className="g-secondary" onClick={restart}>Start a new adventure</button></section>}

     {s.panel==='backpack'&&<><ReadingParagraph>Things Pip is carrying.</ReadingParagraph>{c.bakery.tile==='pip'&&<div className="g-item"><span><strong>Rina’s spare roof tile</strong><small>Rina gave permission. Bring this intact tile to Sol.</small></span></div>}{c.bakery.stage==='escorting'&&<ReadingParagraph>Rina carries the thank-you loaf. She is waiting for Pip or walking with him along the bakery path.</ReadingParagraph>}{c.bakery.met&&<button className="g-secondary" onClick={e=>open('bakery',e.currentTarget)}>Read the bakery account</button>}{c.bakery.edition==='earlier-chapter'&&<ReadingParagraph>This saved adventure used the earlier Sol story. Start a new adventure from Pause to play the bakery, roof repair and thank-you visit. This adventure will be archived.</ReadingParagraph>}{s.mode==='mara-story'&&<ReadingParagraph>Pip is waiting in the present garden. Mara’s tape belongs to the earlier story and is not in this backpack.</ReadingParagraph>}{c.mara.returnOffered&&<ReadingParagraph>{c.story.grandmaCopy==='mara'?'Pip delivered Grandma’s actual story to Mara.':c.story.records.grandma&&c.story.plan?.time==='later'?'Mara heard Grandma’s story at the gathering.':'Pip offered to bring Mara a story if she is still working during the gathering.'}</ReadingParagraph>}{c.mara.asking!=='none'&&<section className="g-plan-notebook"><h3>A conversation to follow up</h3><ReadingParagraph>{c.mara.asking==='pending'?'Pip promised to ask Grandma about starting later. He has not asked yet.':'Pip asked Grandma about starting later. She agreed. Invitations and the reader still depend on the actual chosen plan.'}</ReadingParagraph></section>}{ropeCount(c,'pip')>0&&<div className="g-item"><span><strong>{ropeCount(c,'pip')} repair ropes</strong><small>Grandma’s ropes for securing the footbridge.</small></span></div>}{c.seed==='pip'&&<div className="g-item"><Icon kind="leaf"/><span><strong>A lantern seed</strong><small>Plant it with Grandma before dark.</small></span></div>}
      {c.page==='pip'&&<div className="g-item"><Icon kind="book"/><span><strong>The Torn Wing</strong><small>A copy of Mara’s story for Grandma.</small></span><button onClick={e=>open('story',e.currentTarget)}>Read</button></div>}
      <div className="g-item"><Icon kind="book"/><span><strong>Grandma’s letter</strong><small>Written before the storm.</small></span><button onClick={e=>open('opening',e.currentTarget)}>Read</button></div>
      {c.story.grandmaCopy==='pip'&&<div className="g-item"><Icon kind="book"/><span><strong>The Empty Bench</strong><small>Grandma’s copy for Mara.</small></span><button onClick={e=>open('empty',e.currentTarget)}>Read</button></div>}{c.seed!=='pip'&&<ReadingParagraph className="g-muted">{c.seed==='soil'?'The seed is planted in Grandma’s garden.':c.seed==='boat'?'The seed is aboard the small boat.':'Grandma is holding the seed.'}</ReadingParagraph>}{c.page==='grandma'&&<ReadingParagraph className="g-muted">Grandma has Mara’s page now.</ReadingParagraph>}
     </>}
     {s.panel==='help'&&s.readingInspection&&<><ReadingParagraph>These are the words and choices you just saw. Reading them leaves your choices open. Return to the game to act.</ReadingParagraph>{s.readingInspection.text.map((text,index)=><ReadingParagraph origin="mixed-display" key={index}>{text}</ReadingParagraph>)}</>}
     {s.panel==='help'&&!s.readingInspection&&<><ReadingParagraph className="g-help-goal">{goal}</ReadingParagraph><h3>Story so far</h3><ReadingParagraph>Pip promised to plant a lantern seed with Grandma. The storm washed away the footbridge.</ReadingParagraph>
      {conversationReady(c,'mara')&&<ReadingParagraph>Mara explained that her work hours changed. At the usual gathering time, she still has passengers to help.</ReadingParagraph>}
      {!gatheringHelp&&<ReadingParagraph>{description}</ReadingParagraph>}{gatheringHelp?<><h3>At the gathering</h3><ReadingParagraph>{gatheringHelp}</ReadingParagraph></>:<><h3>Making your way</h3>{bakeryContext&&<ReadingParagraph>{bakeryInstruction(s)} Help and Pause stop travel and cancel unplaced tile previews. Rina waits with her loaf when Pip leaves the bakery path.</ReadingParagraph>}{s.mode==='mara-story'&&<ReadingParagraph>{birdInstruction(s)} Help and Pause stop Mara’s travel. A tape preview is canceled; an already placed strip stays where you placed it.</ReadingParagraph>}{s.mode==='boat'&&<ReadingParagraph>You control the seed boat while Pip waits on the bank. Launch it, then click water, use the arrow keys or choose a direction. Go around the rock. The blue landing is where Grandma can receive the seed. To cancel, return to the yellow launch and unload. Help and Pause stop the boat where it is.</ReadingParagraph>}<ReadingParagraph>Click a place to walk there, or use WASD and the arrow keys. Approach a person, then choose Talk or press E.</ReadingParagraph><ReadingParagraph>In Arrange bridge, drag a section or select it and click where it should go. The same Move and Turn buttons work without dragging.</ReadingParagraph></>}
      <button className="g-secondary" onClick={e=>open('opening',e.currentTarget)}>Read Grandma’s letter</button>{conversationReady(c,'mara')&&<button className="g-secondary" onClick={e=>open('mara',e.currentTarget)}>Reread Mara’s account</button>}
     </>}
     {s.panel==='pause'&&<><ReadingParagraph>Your adventure waits while you read, explore or take a break.</ReadingParagraph><label className="g-setting"><input type="checkbox" checked={c.largeText} onChange={e=>store.send({type:'SETTING',key:'largeText',value:e.target.checked})}/> Larger reading text</label><label className="g-setting"><input type="checkbox" checked={c.reducedMotion} onChange={e=>store.send({type:'SETTING',key:'reducedMotion',value:e.target.checked})}/> Reduced motion</label><ReadingParagraph className="g-small">Progress stays in this browser. Starting a new adventure keeps an archive of this one.</ReadingParagraph>
      <label className="g-setting"><input type="checkbox" checked={!!c.largestText} onChange={e=>store.send({type:'SETTING',key:'largestText',value:e.target.checked})}/> Largest reading text</label><label className="g-setting"><input type="checkbox" checked={!!c.roomierText} onChange={e=>store.send({type:'SETTING',key:'roomierText',value:e.target.checked})}/> More space between lines</label>
     </>}
     {(!readingOnly||s.panel==='endingWords'||(s.activity?.kind==='lantern-inspect'||remoteAccount)&&s.panel==='sol'&&!!c.story.records.sol)&&<ChapterContent key={s.panel} s={s} store={store} open={open} renderSource={renderSource} renderText={renderText} speak={speak} practice={practicePart}/>}{s.panel==='complete'&&<><div className="g-completion-flower"><Icon kind="leaf"/></div><ReadingParagraph>Pip crossed the river and planted the seed with Grandma. He had kept his promise.</ReadingParagraph><div className="g-success-line"><Icon kind="check"/> The crossing stays open.</div><div className="g-success-line"><Icon kind="check"/> The lantern-flower has taken root.</div><div className="g-success-line"><Icon kind="check"/> Grandma has Mara’s page—and understands why she couldn’t visit.</div><ReadingParagraph className="g-muted">Grandma opens <em>The Torn Wing</em>. There is another story to discover.</ReadingParagraph></>}
     {!readingOnly&&s.panel==='mara'&&<MaraChoices s={s} store={store}/>}
     {s.panel==='birdTalk'&&<Choices label="You are speaking as Mara. Choose your response."><button className="g-primary" onClick={()=>store.send({type:'MARA_STEP',step:'ASK'})}>Would you like some help?</button></Choices>}
     {!readingOnly&&s.panel==='opening'&&!s.panelTrail.some(p=>!!p.panel)&&<Choices label="Ready to help Grandma?"><button className="g-primary" onClick={()=>store.send({type:'START_PLAY'})}>Start playing <Icon kind="arrow"/></button></Choices>}
     {!readingOnly&&s.panel==='sections'&&<Choices label="What will Pip do next?"><button className="g-primary" disabled={c.crossed} onClick={()=>store.send({type:'ARRANGE'})}>Arrange bridge <Icon kind="arrow"/></button><button className="g-alternative" disabled={!!s.action} onClick={()=>{store.send({type:'BACK'});store.send({type:'FERRY'});}}>{c.seed==='pip'&&!c.crossed?'Load the seed into the boat':'Watch the empty seed boat'}</button></Choices>}
     {s.panel==='complete'&&<Choices label="What would you like to do next?"><button className="g-primary" onClick={close}>Explore the garden</button><button className="g-alternative" onClick={restart}>Play from the beginning</button><button className="g-secondary" onClick={e=>open('story',e.currentTarget)}>Read Mara’s story again</button></Choices>}
     {s.panel==='pause'&&c.started&&<button className="g-alternative" onClick={restart}>Start a new adventure</button>}
     {s.action&&<ReadingParagraph className="g-small" role="status">{s.notice}</ReadingParagraph>}

    </div>
     {readingTarget&&<div inert={!!word}><ReadingSession store={store} key={readingTarget.id} text={readingTarget.text} target={readingTarget.id} title={readingTarget.title} origin={readingTarget.origin} onTranscript={readingTarget.onTranscript} speak={speak} modelNotice={audio} onClose={closePractice}/></div>}
     {word&&<aside className="garden-word-card" aria-label={'Word help: '+word.word}><div className="g-row"><Tag>WORD EXPLORER</Tag><button aria-label="Close word help" className="g-close" onClick={()=>{stopAudio();setWord(null);requestAnimationFrame(()=>word.button.focus());}}>×</button></div><h3>{helpCard!.title}</h3><p>{helpCard!.definition}</p>{helpCard!.explanation&&<p className="g-word-context">{helpCard!.explanation}</p>}{(word.source||word.draft)&&helpCard!.explanation===word.sentence&&<AdditionalWordHelp key={word.component+':'+word.start} target={{source:word.source??null,paragraph:word.paragraph!,draft:word.draft??null,revision:c.revision,start:word.start!,end:word.end!,word:word.word,sentence:word.sentence,...(!word.source?{origin:word.origin??'authored-display' as const}:{})}} reviewed={helpCard!.definition} store={store} speak={speak}/>} <div className="g-row"><button className="g-secondary" onClick={()=>speak(word.word)}><Icon kind="sound"/> Hear the word</button>{helpCard!.phrase&&<button className="g-secondary" onClick={()=>speak(helpCard!.phrase!)}>Hear the phrase</button>}<button className="g-secondary" onClick={()=>speak(word.sentence)}>{word.title?'Hear the title':'Hear the sentence'}</button><button className="g-secondary" onClick={()=>{const text=word.draft??(word.source?sources[word.source as SourceId]?.paragraphs[word.paragraph??0]:word.sentence)??word.sentence;practicePart(text,'word-passage',word.button,word.origin);setWord(null);}}>Read this passage aloud</button>{speaking&&<button className="g-secondary" onClick={stopAudio}>Stop listening</button>}</div>{audio&&<p role="status" className="g-audio-notice">{audio}</p>}</aside>}
    <footer className="g-reader-actions" hidden={!!word||!!readingTarget}><ConversationControls s={s} store={store} close={close} backLabel={backLabel}/></footer>
   </section>}
  </div>
  {c.started&&!s.panel&&!s.activity&&s.mode!=='mara-story'&&<footer className="garden-action-bar">
   <span className="g-world-role">{roleText(s)}</span>
   <div className="garden-nearby" aria-label="Nearby actions">
    {gatheringActive?<span className="g-small">Follow the gathering here. Help and Pause keep your place.</span>:bakeryActive?<span className="g-small">{s.mode==='bakery-repair'?'You direct Sol’s repair':'You guide Pip · Rina and Sol do their own work'}</span>:s.mode==='boat'?<span className="g-small">You steer the boat · Pip waits on the bank</span>:s.mode==='arrange'?<span className="g-small">Drag to move · Click to place · Escape to cancel</span>:<>
     {nearMara?<button className="g-primary" disabled={disabled} onClick={e=>talk('mara',e.currentTarget)}>Talk to Mara <kbd>E</kbd></button>:!conversationReady(c,'mara')&&<button className="g-primary" disabled={disabled} onClick={()=>go('mara')}>Go to Mara <Icon kind="arrow"/></button>}
     {nearSections&&!c.crossed?<><button className="g-primary" disabled={disabled} onClick={()=>store.send({type:'ARRANGE'})}>Arrange bridge</button><button className="g-secondary" disabled={disabled} onClick={e=>open('sections',e.currentTarget)}>Read the note</button></>:!c.crossed&&<button className="g-secondary" disabled={disabled} onClick={()=>go('sections')}>Go to the bridge pieces</button>}
     {bridgeAttemptable(c)&&!c.crossed&&<button className="g-primary" disabled={disabled} onClick={()=>store.send({type:'TRY_CROSS'})}>Try crossing the bridge</button>}{nearSol&&!bakeryActive&&<button className="g-primary" disabled={disabled} onClick={e=>talk('sol',e.currentTarget)}>Talk to Sol</button>}{c.crossed&&!nearSol&&!bakeryActive&&<button className="g-secondary" disabled={disabled} onClick={()=>go('sol')}>{gatheringStarted(c)?'Go to Sol':solAtWorkshop(c)?'Go to Sol’s workshop':'Go to Rina’s bakery'}</button>}{bridgeReady(c)&&!nearGrandma&&<button className="g-primary" disabled={disabled} onClick={()=>go('grandma')}>Go to Grandma <Icon kind="arrow"/></button>}
     {nearGrandma&&<button className="g-primary" disabled={disabled} onClick={e=>talk('grandma',e.currentTarget)}>Talk to Grandma <kbd>E</kbd></button>}
     {s.pendingBloom&&<button className="g-secondary" disabled={disabled} onClick={()=>store.send({type:'BLOOM'})}>Continue</button>}
     {c.crossed&&<button className="g-secondary" onClick={e=>open('lanterns',e.currentTarget)}>Lantern stories</button>}{encounterDone(c)&&<button className="g-primary" onClick={e=>open('studio',e.currentTarget)}>Watch your ending</button>}
     {c.story.ending&&<button className="g-alternative" disabled={disabled} onClick={restart}>Play from the beginning</button>}
    </>}
   </div>
  </footer>}
 </main></ReadingContext.Provider>;
}
