import {StoryReadingTools} from './StoryReadingTools.js';
import {solContributionSpeech} from './storyReading.js';
import {ContinuousPlayback} from './ContinuousPlayback.js';
import {ReadingParagraph,ReadWords,ReadingTools,type ReadingOrigin} from './Reading.js';
import type {ReactNode} from 'react';
import {Choices,Reply} from './Dialogue.js';
import {ReadingDetails} from './ReadingDetails.js';
import type {GardenState,GardenStore,Panel,SourceId} from './model.js';
import {arrivalNext,gatheringAction,turnLines,witnessedQuestion,welcomeWords,type SpokenLine} from './gathering.js';
import {speechAttributes,speechDocument} from './readingSpeech.js';
import {voiceSpeaker,type SpeechRequest,type SpeechSpeak} from './voiceTypes.js';
import {editionOf,maintenanceOf} from './narrativeEdition.js';
type Props={s:GardenState;store:GardenStore;open:(panel:Panel,origin?:Element)=>void;renderSource:(id:SourceId,index?:number)=>ReactNode;renderText:(line:SpokenLine)=>ReactNode;speak:SpeechSpeak;practice:(text:string,id:string,opener?:HTMLElement,origin?:ReadingOrigin,title?:string,speech?:SpeechRequest)=>void};
const arrivalLabel={finalBoat:'Bring the last boat alongside',finalPassengers:'Help the last passengers ashore',solArrival:'Let Sol walk to the garden',maraArrival:'Let Mara cross to the garden',bringCushions:'Bring out Grandma’s cushions',finishGrandmaPage:'Finish Grandma’s account'};
export function GatheringControls({s,store,open}:{s:GardenState;store:GardenStore;open:(panel:Panel,origin?:Element)=>void}){
 const c=s.chapter,g=c.gathering,t=g.turn,next=arrivalNext(c),lines=t?turnLines(c):[],line=t?lines[t.index]:null,busy=!!s.action||s.background||s.viewLost;
 return <section className="garden-gathering-controls" aria-label="The gathering in the game">
  <span className="g-kicker">{t?'SPEAKING TO THE PEOPLE HERE':'YOUR PLAN HAPPENS HERE'}</span><h2 tabIndex={-1}>{line?line.who+' is speaking':c.story.phase==='arriving'?'Friends on their way':'Grandma’s garden'}</h2>
  {line?<><ContinuousPlayback s={s} store={store}/><ReadingParagraph className="g-gathering-caption" role="status" origin={line.origin??'authored-display'}>{line.text}</ReadingParagraph>{line.attribution&&<ReadingParagraph className="g-small">{line.attribution}</ReadingParagraph>}<ReadingParagraph className="g-small">{t?.kind==='receipt'?'Pip and Mara are at the dock. Mara has the copy and is still on duty.':c.story.plan?.time==='usual'?'Pip, Sol and Grandma are here. Mara remains at work.':'Pip, Sol, Mara and Grandma are here.'}</ReadingParagraph><button className="g-secondary" disabled={busy} onClick={e=>open('gathering',e.currentTarget)}>Read the whole story with help</button></>:<><ReadingParagraph>{s.notice}</ReadingParagraph>{next&&<button className="g-primary" disabled={busy} onClick={()=>store.send({type:'STORY',event:{kind:'CONTINUE_ARRIVAL'}})}>{arrivalLabel[next]}</button>}{!next&&!gatheringAction(s.action?.kind??'')&&<button className="g-primary" onClick={e=>open('gathering',e.currentTarget)}>Return to the gathering</button>}</>}
 </section>;
}
export function GatheringReader({s,store,open,renderSource,renderText,speak,practice}:Props){
 const c=s.chapter,f=c.story,g=c.gathering,send=(event:import('./chapter.js').StoryEvent)=>store.send({type:'STORY',event});
 if(g.turn){const lines=turnLines(c),parts=lines.map((line,index):SpeechRequest=>({text:line.text,speaker:voiceSpeaker(line.who),origin:line.origin??'authored-display',revision:g.turn!.contribution?.revision??c.revision,owner:c.runId+':gathering:'+g.turn!.kind+':'+index,...(line.source?{source:{id:line.source,paragraph:line.paragraph??0,edition:editionOf(c),...(maintenanceOf(c)?{maintenanceEdition:maintenanceOf(c)!}:{}),start:0,end:line.text.length}}:{})})),speech=speechDocument(parts);return <><ReadingParagraph>The telling is paused. Read the complete text at your own pace. When you return to the game, choose Resume story.</ReadingParagraph>{(g.turn.kind==='sol'||g.turn.kind==='add-ending')&&<StoryReadingTools chapter={c} id="sol" version="current-turn"/>}{g.turn.kind==='grandma'&&<StoryReadingTools chapter={c} id="empty"/>}{g.turn.kind==='mara'&&<StoryReadingTools chapter={c} id="story"/>}<section aria-label="Complete telling">{lines.map((line,index)=><div key={index} {...speechAttributes(parts[index])}><h3>{line.who} says</h3>{line.source?renderSource(line.source as SourceId,line.paragraph):renderText(line)}{line.attribution&&<ReadingParagraph speech={{text:line.attribution,speaker:'narrator',origin:'authored-display'}}>{line.attribution}</ReadingParagraph>}</div>)}</section>{!['sol','add-ending','grandma','mara'].includes(g.turn.kind)&&<ReadingTools text={speech.text} label="the complete conversation" origin="mixed-display" speech={speech}/>}</>;}
 if(f.phase==='planning')return <><ReadingParagraph>The gathering has not begun.</ReadingParagraph><button className="g-primary" onClick={e=>open('planner',e.currentTarget)}>Plan with Grandma</button></>;
 if(f.phase==='arriving')return <><ReadingParagraph>Your plan is bringing people to the garden. Continue their journey in the game.</ReadingParagraph></>;
 if(f.phase==='welcome'){const speech:SpeechRequest={text:welcomeWords(c),speaker:'pip',origin:'authored-display',revision:f.plan!.revision};return <><div className="g-dialogue-response" data-speech-speaker="grandma"><strong>Grandma says</strong><ReadingParagraph>You helped arrange today’s gathering, Pip. Would you like to welcome everyone?</ReadingParagraph></div><h3>Pip’s welcome</h3><div {...speechAttributes(speech)}>{renderText({who:'Pip',text:speech.text})}</div><button className="g-secondary" onClick={()=>speak(speech)}>Hear the welcome</button><button className="g-secondary" onClick={event=>practice(speech.text,'welcome-'+f.plan!.revision,event.currentTarget,'authored-display',undefined,speech)}>Practise the welcome</button><button className="g-primary" onClick={()=>send({kind:'NEXT_STORY'})}>Welcome everyone in the garden</button></>;}
 if(f.phase==='mara')return <><ReadingParagraph>{f.plan?.reader==='mara'?'Mara will tell her story.':f.plan?.time==='usual'?'Pip will read Mara’s page. Mara is still at work.':'Pip will read Mara’s page while Mara listens.'}</ReadingParagraph><h3>The Torn Wing · by Mara</h3>{renderSource('story')}<StoryReadingTools chapter={c} id="story"/>{c.mara.sharedAt==='gathering'?<button className="g-primary" onClick={()=>send({kind:'NEXT_STORY'})}>Invite Sol to share</button>:<button className="g-primary" onClick={()=>send({kind:'SHARE_MARA'})}>Share The Torn Wing</button>}</>;
 if(f.phase==='sol')return <><StoryReadingTools chapter={c} id="sol"/><h3>A Small Repair · Sol’s original manuscript</h3>{renderSource('sol')}{f.solChoice==='prepared'&&f.solEnding&&<><h3>{f.solEnding.origin==='child'?'Your suggested ending, chosen by Sol':'Prepared ending from Sol’s account'}</h3>{f.solEnding.origin==='child'?<><ReadingParagraph origin="child-draft" speech={solContributionSpeech(c,f.solEnding)}>{f.solEnding.text}</ReadingParagraph><ReadingParagraph>The picture follows the event you chose. Your suggested words have not been checked against Sol’s account.</ReadingParagraph></>:renderSource(f.solEnding.scene==='thanks'?'thanksEnding':'breadEnding')}</>}<ReadingParagraph>{f.solChoice==='prepared'?'Sol will share the version you chose, even if your working draft changed later.':'Sol will share the draft. An unfinished ending is a valid contribution.'}</ReadingParagraph><button className="g-primary" onClick={()=>send({kind:'NEXT_STORY'})}>Let Sol share with everyone</button></>;
 if(f.phase==='discussion'){const last=f.questions.at(-1);return <>
  {last?<><Reply who="Sol">{last==='bread'?'Yes. The flour stayed dry, and Rina baked the bread she promised.':'Later, Rina came to my workshop with a loaf of bread to thank me.'}</Reply><h3>An ending from Sol’s account</h3>{renderSource(last==='bread'?'breadEnding':'thanksEnding')}</>:<Reply who="Sol">That’s as far as I’ve written. What would you like to hear about next?</Reply>}
  <Choices label={last?'What would you like Sol to do next?':'You are Pip. Choose your response.'}>
   {f.questions.map(q=><button className="g-primary" key={'ending-'+q} onClick={()=>send({kind:'ADD_ENDING',scene:q})}>Add and share the {q==='bread'?'bread':'thank-you'} ending</button>)}
   {(['bread','thanks'] as const).filter(q=>!f.questions.includes(q)).map(q=><button key={q} className={q==='bread'?'g-primary':'g-alternative'} onClick={()=>send({kind:'ASK_SOL',question:q})}>{witnessedQuestion[q]}</button>)}
   <button className="g-secondary" onClick={()=>send({kind:'KEEP_DRAFT'})}>Keep the draft as it is</button>
  </Choices>
  {f.questions.length>1&&<ReadingDetails id="sol-earlier-replies" s={s} store={store}><summary>Reread Sol’s earlier reply</summary>{renderSource(f.questions[0]==='bread'?'breadEnding':'thanksEnding')}</ReadingDetails>}
 </>;}
 if(f.phase==='grandma'){
  if(!g.solDisclosed)return <><ReadingParagraph>Grandma has heard Sol’s story. She wants to understand why he stopped bringing stories before today.</ReadingParagraph><button className="g-primary" onClick={()=>send({kind:'NEXT_STORY'})}>Hear Grandma ask Sol</button></>;
  if(!g.cushions)return <><ReadingParagraph>Grandma now understands why her friends stayed away. Her spare cushions are in the storage beside the bench.</ReadingParagraph><button className="g-primary" onClick={()=>send({kind:'NEXT_STORY'})}>Let Grandma bring out the cushions</button></>;
  if(!g.pageComplete)return <><ReadingParagraph>The cushions are back on the bench. Grandma has been writing about the evenings she spent waiting. Now she can add what she learned today.</ReadingParagraph><button className="g-primary" onClick={()=>send({kind:'NEXT_STORY'})}>Let Grandma finish her account</button></>;
  return <><h3>The Empty Bench · by Grandma</h3><ReadingParagraph>Grandma has finished her own story. The first part describes the garden before today.</ReadingParagraph>{renderSource('empty')}<StoryReadingTools chapter={c} id="empty"/><button className="g-primary" onClick={()=>send({kind:'NEXT_STORY'})}>Let Grandma share her story</button></>;
 }
 return null;
}
