/** Authored word help for the literary edition. Earlier exact definitions take precedence. */
export const literaryGlossary:Record<string,string>={
  "shares":"Lets other people hear, use or take part in something.",
  "soon":"In a short time.",
  "asking":"Saying a question or making a request.",
  "lay":"Put something down carefully in a particular place.",
  "pause": "Stop for a while, intending to continue.",
  "permission": "Agreement that someone may do something.",
  "damaged": "Harmed or broken so it may not work properly.",
  "opening": "A space where something is missing or things do not meet.",
  "words": "Units of language that carry meaning.",
  "part": "One piece of a larger whole.",
  "already": "Before now or sooner than expected.",
  "ask": "Say something to request help or information.",
  "instead": "In place of something else.",
  "explanation": "Words that make something clearer.",
  "sack": "A large strong bag used to hold materials.",
  "dough": "A mixture of flour and liquid that is worked and baked into bread.",
  "shaped": "Give something a particular form.",
  "loaves": "More than one loaf of bread.",
  "gap": "A space where something is missing or things do not meet.",
  "agreed": "Decided something together.",
  "helping": "Making a task easier for someone.",
  "please": "A polite word used when asking someone to do something.",
  "listen": "Pay attention to sounds or spoken words.",
  "copy": "Another page or version containing the same words.",
  "writing": "Putting ideas into written words.",
  "whole": "All of something, from beginning to end.",
  "paused": "Stop for a while, intending to continue.",
  "sparkfest": "The festival where children share stories and things they have made.",
  "loop": "Jo’s rolling projector, which shows the paper story’s pictures on a screen.",
  "rolling": "Moving on wheels or by turning over and over.",
  "projector": "A device that uses light to show pictures on a screen.",
  "pictures": "Images showing people, places or events.",
  "choose": "Decide which possibility you want.",
  "responds": "Answers someone.",
  "aloud": "Using your voice so the words can be heard.",
  "version": "A particular form of a story or other work.",
  "know": "Have information about something.",
  "start": "Begin doing something.",
  "covered": "Put something over an area to protect or hide it.",
  "baking": "Making food such as bread in an oven.",
  "different": "Not the same as another thing.",
  "oven": "An enclosed space that heats food for baking.",
  "customers": "People who buy things from a shop or business.",
  "listening": "Pay attention to sounds or spoken words.",
  "carrying": "Holding something while taking it somewhere.",
  "remember": "Bring something back to mind.",
  "account": "Someone’s description of what happened.",
  "actually": "Really; as it happened, rather than only being imagined or planned.",
  "real": "Really; as it happened, rather than only being imagined or planned.",
  "added": "Put something more with what was already there.",
  "adventure": "An experience involving exploration, challenges or discoveries.",
  "against": "Touching or pressing on something.",
  "ago": "Before the present time.",
  "along": "Following the length or direction of something.",
  "among": "In the middle of, or as part of, a group.",
  "angle": "The direction from which something is viewed.",
  "any": "One or more, without choosing a particular one.",
  "anything": "Any thing, without specifying which.",
  "apart": "Separated by a distance.",
  "aren't": "Short for are not.",
  "arms": "The parts of the body between the shoulders and hands.",
  "arranging": "Putting things into a chosen order or position.",
  "arrive": "Reach a place.",
  "as": "While something happens, or in the way described.",
  "aside": "To one side, out of the way.",
  "begun": "Started.",
  "behind": "At the back of something.",
  "being": "Existing, happening, or in a particular state.",
  "below": "At a lower position.",
  "bent": "Moved into a curved or lowered position.",
  "better": "More suitable or successful than before.",
  "between": "In the space separating two things.",
  "bottom": "The lowest part of something.",
  "breath": "Air taken into or let out of the lungs.",
  "bringing": "Carrying something toward a person or place.",
  "came": "Moved toward or arrived at a place.",
  "can't": "Short for cannot.",
  "careful": "Paying attention to avoid harm or mistakes.",
  "catch": "Stop and hold something that is moving.",
  "ceiling": "The inside surface above a room.",
  "change": "Make or become different.",
  "chasing": "Following something to catch or reach it.",
  "check": "Look carefully to find out whether something is right.",
  "children": "Young people.",
  "chose": "Selected from the things available.",
  "climbing": "Moving up or down using steps, hands or feet.",
  "considered": "Thought about something carefully.",
  "counting": "Finding a number; counting on someone means relying on them.",
  "crack": "A narrow split in a surface.",
  "cups": "Small containers used for drinking.",
  "cut": "Divide something with a sharp edge.",
  "day": "The time from one midnight to the next, or its daylight hours.",
  "days": "More than one day.",
  "didn't": "Short for did not.",
  "done": "Finished or carried out.",
  "door": "An entrance that can be opened and closed.",
  "down": "Toward a lower place.",
  "dragging": "Pulling something along a surface.",
  "drew": "Pulled or took in; drew breath means breathed in.",
  "drips": "Small amounts of liquid falling separately.",
  "drops": "Small amounts of liquid falling separately.",
  "drop": "Fall or move to a lower position.",
  "duet": "Music performed by two people together.",
  "eased": "Moved something slowly and carefully.",
  "easier": "Less difficult.",
  "eat": "Take food into the mouth and swallow it.",
  "eaten": "Taken food into the mouth and swallowed it.",
  "edges": "The outer boundaries of something.",
  "else": "Another or different thing.",
  "ended": "Came to a finish.",
  "ends": "Comes to a finish.",
  "evenings": "The times between the later part of the day and night.",
  "exactly": "Precisely, without a difference.",
  "expected": "Thought something was likely to happen.",
  "falling": "Moving downward.",
  "farther": "At or to a greater distance.",
  "fetch": "Go and get something, then bring it back.",
  "finally": "After waiting or after other things have happened.",
  "finds": "Discovers or comes upon something.",
  "fingers": "The moving parts of the hand used to touch and hold.",
  "finished": "Completed.",
  "firm": "Steady and secure.",
  "fist": "A hand closed tightly with its fingers curled inward.",
  "fit": "Be the right size or position for a place.",
  "fitted": "Put something into its intended place.",
  "fix": "Repair or put something right.",
  "flapped": "Moved back and forth loosely.",
  "floor": "The surface at the bottom of a room.",
  "flowers": "The parts of plants that produce seeds; here, the garden’s lantern flowers.",
  "folded": "Bent one part over another.",
  "folds": "Lines or shapes made by bending material over itself.",
  "follow": "Go after something or understand how events connect.",
  "followed": "Came after something.",
  "foot": "The part at the end of a leg that supports standing and walking.",
  "funny": "Amusing; likely to make someone laugh.",
  "gave": "Handed something to someone.",
  "gently": "With care and little force.",
  "gives": "Hands something to someone or makes it available.",
  "glad": "Pleased about something.",
  "go": "Move from one place to another.",
  "good": "Suitable, useful or pleasing.",
  "grew": "Became larger or developed.",
  "grown": "Became larger or developed.",
  "grip": "A firm hold.",
  "guessing": "Forming an idea without being certain.",
  "guide": "Help someone find a way or decide what to do.",
  "handle": "Hold, move or take care of something.",
  "happens": "Takes place.",
  "haven't": "Short for have not.",
  "having": "Possessing, experiencing or taking part in something.",
  "hers": "Belonging to the female person already mentioned.",
  "herself": "That female person, acting on her own or being referred to again.",
  "hold": "Keep something in your hands or in a particular position.",
  "hoping": "Wanting something to happen.",
  "hot": "Having a high temperature.",
  "hung": "Was suspended, with a part pointing downward.",
  "i'm": "Short for I am.",
  "i've": "Short for I have.",
  "imagining": "Forming a picture or idea in the mind.",
  "improvements": "Changes that make something better.",
  "inside": "Within a place or object.",
  "it's": "Short for it is or it has.",
  "joins": "Comes together with someone or something.",
  "just": "Only, exactly, or a very short time before.",
  "kite": "An object that can be held on a string and lifted by the wind.",
  "knew": "Had information or understanding about something.",
  "known": "Had information or understanding about something.",
  "knowing": "Having information or understanding.",
  "laid": "Put something down carefully.",
  "lanterns": "Lights held in protective coverings; here, flowers that keep story pictures.",
  "late": "After the expected or usual time.",
  "laughing": "Making sounds that show amusement.",
  "let": "Allowed something to happen.",
  "light": "Brightness that makes things visible; here, daylight or the lanterns’ glow.",
  "line": "A narrow mark or a row of written words.",
  "long": "Extending a large distance or lasting much time.",
  "longest": "For more time or distance than the others.",
  "looked": "Directed the eyes toward something.",
  "looking": "Directing the eyes toward something.",
  "looks": "Directs the eyes, or appears a certain way.",
  "lower": "Not as high.",
  "maker": "The person who makes something.",
  "makes": "Creates something or causes it to happen.",
  "making": "Creating something or causing it to happen.",
  "mara's": "Belonging to Mara.",
  "meet": "Come together with someone.",
  "meets": "Comes together with someone.",
  "might": "Shows that something is possible.",
  "mine": "Belonging to the speaker.",
  "missed": "Felt the absence of someone or something.",
  "moment": "A short time or a particular part of an event.",
  "more": "A greater amount.",
  "most": "The greatest amount, or nearly all.",
  "mostly": "Mainly; for the largest part.",
  "move": "Change position.",
  "moved": "Changed position.",
  "narrow": "Not wide.",
  "near": "Close by.",
  "nearly": "Almost.",
  "needed": "Required something.",
  "neither": "Not one and not the other of two.",
  "nobody": "No person.",
  "nothing": "No thing.",
  "nowhere": "No place.",
  "once": "On one occasion; for once means on this occasion, unlike usual.",
  "open": "Unfold or make accessible; an open ending is still unfinished.",
  "opened": "Made accessible or unfolded.",
  "operator": "A person who controls a machine or vehicle.",
  "opposite": "On the other side.",
  "ordered": "Asked a business to supply something.",
  "ordinary": "Usual or familiar, rather than unusual.",
  "others": "Additional people or things.",
  "outside": "Beyond the inside of a place or object.",
  "own": "Belonging specifically to the person mentioned.",
  "palm": "The inner surface of the hand.",
  "pass": "Move past someone or something.",
  "passed": "Moved past someone or something.",
  "pattered": "Made repeated small, light tapping sounds.",
  "piece": "A part of something.",
  "pip's": "Belonging to Pip.",
  "places": "Positions or locations.",
  "planting": "Putting a seed or plant into soil.",
  "playing": "Taking part in an activity, or making music with an instrument.",
  "poor": "Here, not working very well as the thing described.",
  "probably": "Likely to happen or be true.",
  "quite": "Fully, exactly, or to some extent, depending on the sentence.",
  "raised": "Lifted to a higher position.",
  "rather": "Preferably; rather hear means prefer to hear.",
  "reaches": "Gets to a person or place.",
  "reaching": "Moving toward something to touch or get to it.",
  "remembers": "Brings an earlier experience back to mind.",
  "replacing": "Putting one thing in the place of another.",
  "right": "Correct or suitable in this situation.",
  "room": "Space or an opportunity for someone or something.",
  "sat": "Rested with the body supported on a seat.",
  "saw": "Noticed something with the eyes.",
  "says": "Speaks particular words.",
  "scrape": "A rough sound made as something rubs across a surface.",
  "screen": "A surface on which pictures can be shown.",
  "seated": "Sitting down.",
  "see": "Notice with the eyes, or understand.",
  "seeing": "Noticing with the eyes.",
  "sensible": "Practical and reasonable.",
  "settled": "Moved into a position and became still.",
  "shines": "Gives or sends out light.",
  "shiny": "Reflecting light.",
  "shoulders": "The parts of the body where the arms join the upper body.",
  "show": "Let someone see or understand something.",
  "side": "An edge or surface of something.",
  "sit": "Rest with the body supported on a seat.",
  "size": "How big something is.",
  "slightly": "By a small amount.",
  "smaller": "Not as big.",
  "smile": "A pleased expression made with the mouth.",
  "smoothed": "Pressed gently to make a surface flat.",
  "sort": "A kind or type.",
  "sounds": "Noises that can be heard, or seems when heard.",
  "spend": "Use an amount of time or money.",
  "stand": "Be upright on the feet.",
  "standing": "Being upright on the feet.",
  "steady": "Not shaking or changing much.",
  "step": "A movement of one foot, or a surface used when moving up or down.",
  "stops": "Ceases to move or continue.",
  "storage": "A place where things are kept until needed.",
  "straight": "Without a bend or fold.",
  "stretched": "Extended as far as needed or possible.",
  "suggest": "Offer an idea for someone to consider.",
  "sure": "Certain or confident.",
  "take": "Carry or receive something.",
  "taken": "Carried or received.",
  "talking": "Speaking with someone.",
  "tap": "A small, light knock or its sound.",
  "tapped": "Made a small, light knocking sound.",
  "tear": "A place where material has been ripped.",
  "than": "Introduces the second part of a comparison.",
  "that's": "Short for that is or that has.",
  "there's": "Short for there is or there has.",
  "they're": "Short for they are.",
  "thinking": "Using the mind to consider something.",
  "though": "Even while, or despite the fact that.",
  "thumb": "The short, thick digit beside the fingers.",
  "tilted": "Moved into a sloping position.",
  "tip": "The end of a narrow or pointed object.",
  "tipped": "Tilted something so its contents moved out.",
  "tray": "A flat container used to carry or bake things.",
  "trips": "Journeys from one place to another.",
  "trying": "Making an effort to do something.",
  "turned": "Moved to face another direction.",
  "under": "Below something, often with that thing above or covering it.",
  "underneath": "Below something, often with that thing above or covering it.",
  "unexpected": "Not thought likely to happen.",
  "unfolded": "Opened something that had been folded.",
  "unless": "Except if.",
  "up": "Toward a higher place.",
  "usual": "Happening regularly or normally.",
  "very": "Adds emphasis to the word that follows.",
  "voice": "The sound a person makes when speaking.",
  "wanted": "Wished to have or do something.",
  "warm": "Comfortably hot.",
  "watch": "Look at something for a time.",
  "welcome": "An expression of pleasure that someone has arrived.",
  "whenever": "Every time that something happens.",
  "whether": "Introduces possibilities or a question about something.",
  "which": "Identifies or asks about one of several things.",
  "who": "Identifies or asks about a person.",
  "windy": "With a lot of moving air.",
  "wish": "Want something to happen or be different.",
  "without": "Not having or using something.",
  "worked": "Did a task or made an effort.",
  "world": "The setting in which people or story characters live.",
  "worth": "Valuable or meaningful enough to do or share.",
  "yes": "A word used to agree or confirm.",
  "yesterday": "The day before today.",
  "yet": "Up to this time, or despite what was just said.",
  "you'd": "Short for you would or you had.",
  "you've": "Short for you have."
};
