import {useEffect,useRef,useState,type ReactNode} from 'react';
import {cancelLocalSpeech,wav} from './audio.js';
import {ReadWords} from './Reading.js';
import {displayReadingTarget,type DisplayOrigin} from './readingReference.js';
export function ReadingPractice({text,target:activity,speak,onClose,onTranscript,modelNotice='',origin='authored-display',navigation,title}:{modelNotice?:string;title?:string|undefined;text:string;target:string;speak:(t:string)=>void;onClose:()=>void;onTranscript?:(text:string)=>void;origin?:DisplayOrigin;navigation?:(busy:boolean)=>ReactNode}){
 const [phase,setPhase]=useState<'ready'|'permission'|'listening'|'review'>('ready'),[notice,setNotice]=useState(''),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[transcript,setTranscript]=useState<string|null>(null);
 const root=useRef<HTMLElement>(null);
 const resources=useRef<{stream:MediaStream;context:AudioContext;node:AudioWorkletNode;chunks:Float32Array[];count:number;resolve:(()=>void)|undefined}|null>(null),attempt=useRef(0),blob=useRef<Blob|null>(null),urlRef=useRef(''),request=useRef<AbortController|null>(null),audio=useRef<HTMLAudioElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(true);
 function revoke(){audio.current?.pause();if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current='';blob.current=null;setUrl('');}
 function cancelFeedback(){request.current?.abort();request.current=null;setBusy(false);}
 async function stop(record=true){const r=resources.current;if(!r)return;resources.current=null;r.stream.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);await new Promise<void>(resolve=>{r.resolve=resolve;r.node.port.postMessage('stop');setTimeout(resolve,200);});r.node.disconnect();r.node.port.close();await r.context.close();if(!alive.current||!record)return;
  const samples=new Float32Array(r.count);let offset=0;for(const chunk of r.chunks){samples.set(chunk,offset);offset+=chunk.length;}const bytes=wav(samples,r.context.sampleRate);blob.current=new Blob([bytes],{type:'audio/wav'});urlRef.current=URL.createObjectURL(blob.current);setUrl(urlRef.current);setPhase('review');
 }
 async function start(){if(resources.current||phase==='permission')return;cancelFeedback();revoke();cancelLocalSpeech();setTranscript(null);setNotice('');setPhase('permission');const token=++attempt.current;let stream:MediaStream|null=null,context:AudioContext|null=null;
  try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,sampleRate:16000,echoCancellation:true,noiseSuppression:true},video:false});if(!alive.current||token!==attempt.current){stream.getTracks().forEach(t=>t.stop());return;}context=new AudioContext({sampleRate:16000});await context.audioWorklet.addModule('/garden-recorder.js');if(!alive.current||token!==attempt.current){stream.getTracks().forEach(t=>t.stop());await context.close();return;}
   const node=new AudioWorkletNode(context,'garden-recorder'),source=context.createMediaStreamSource(stream),r={stream,context,node,chunks:[] as Float32Array[],count:0,resolve:undefined as (()=>void)|undefined};resources.current=r;
   node.port.onmessage=(e:MessageEvent<{samples?:Float32Array;done?:boolean}>)=>{if(e.data.samples){const remaining=context!.sampleRate*120-r.count,chunk=e.data.samples.slice(0,remaining);if(chunk.length){r.chunks.push(chunk);r.count+=chunk.length;}}if(e.data.done)r.resolve?.();};
   source.connect(node);node.connect(context.destination);await context.resume();if(!alive.current||token!==attempt.current){void stop(false);return;}setPhase('listening');stream.getAudioTracks().forEach(track=>track.addEventListener('ended',()=>{setNotice('The microphone stopped. You can review what was recorded or try again.');void stop();},{once:true}));timer.current=setTimeout(()=>{setNotice('That’s two minutes. Your microphone is off. You can review this reading or record a shorter part.');void stop();},120000);
  }catch{stream?.getTracks().forEach(t=>t.stop());if(context&&context.state!=='closed')await context.close();if(alive.current){setPhase('ready');setNotice('You can practise without the microphone. Microphone access is not available right now.');}}
 }
 async function feedback(){if(!blob.current||request.current)return;const controller=new AbortController();request.current=controller;setBusy(true);setNotice('Checking your reading…');const currentAttempt=attempt.current,timeout=setTimeout(()=>controller.abort(),30000);
  try{const bytes=new Uint8Array(await blob.current.arrayBuffer());let binary='';for(let offset=0;offset<bytes.length;offset+=16384)binary+=String.fromCharCode(...bytes.subarray(offset,offset+16384));const target=onTranscript?activity:await displayReadingTarget(text,origin);if(controller.signal.aborted||request.current!==controller)return;const requestId=crypto.randomUUID();const response=await fetch(onTranscript?'/api/garden/transcript':'/api/garden/reading',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId,attempt:currentAttempt,target,text:onTranscript?'':text,audio:btoa(binary),job:onTranscript?'transcript':'reading'}),signal:controller.signal});const data=await response.json() as {requestId?:string;attempt?:number;target?:string;status?:string;feedback?:string;text?:string};if(request.current!==controller||currentAttempt!==attempt.current||!alive.current)return;const matches=data.requestId===requestId&&data.attempt===currentAttempt&&data.target===target;if(response.ok&&matches&&data.status==='transcript'&&typeof data.text==='string'&&data.text.length<=4000){setTranscript(data.text);setNotice('Check these words and change anything the listener misheard.');}else setNotice(response.ok&&matches&&['supported','uncertain'].includes(data.status??'')&&typeof data.feedback==='string'&&data.feedback.length<=320?data.feedback:onTranscript?'The listener is unavailable right now. You can type your answer instead.':"Reading feedback isn't available right now. You can still practise or return to the story.");}
  catch{if(request.current===controller&&alive.current)setNotice("Reading feedback isn't available right now. You can still practise or return to the story.");}
  finally{clearTimeout(timeout);if(request.current===controller){request.current=null;setBusy(false);}}
 }
 useEffect(()=>{alive.current=true;const hide=()=>{if(resources.current)void stop();};window.addEventListener('blur',hide);document.addEventListener('visibilitychange',hide);return()=>{alive.current=false;attempt.current++;request.current?.abort();cancelLocalSpeech();if(timer.current)clearTimeout(timer.current);const r=resources.current;resources.current=null;r?.stream.getTracks().forEach(t=>t.stop());r?.node.disconnect();r?.node.port.close();void r?.context.close();audio.current?.pause();if(urlRef.current)URL.revokeObjectURL(urlRef.current);blob.current=null;window.removeEventListener('blur',hide);document.removeEventListener('visibilitychange',hide);};},[]);
 useEffect(()=>{root.current?.querySelector<HTMLButtonElement>('button')?.focus();},[]);
 useEffect(()=>{if(phase==='listening')root.current?.querySelector<HTMLButtonElement>('.g-practice-heading .g-primary')?.focus();},[phase]);
 return <section ref={root} className="g-practice-overlay" role="dialog" aria-modal="true" aria-label={onTranscript?'Spoken answer':'Reading practice'} data-recording={phase} data-local-audio-bytes={blob.current?.size??0} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();e.preventDefault();onClose();}if(e.key==='Tab'){const nodes=Array.from(root.current?.querySelectorAll<HTMLElement>('button:not(:disabled),textarea,audio,summary')??[]).filter(n=>n.offsetParent!==null),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}e.stopPropagation();}}}>
  <div className="g-row g-practice-heading"><strong>{onTranscript?'Say your answer':title??'Reading practice'}</strong>{phase==='listening'&&<button className="g-primary" onClick={()=>void stop()}>Stop</button>}<button className="g-close" aria-label="Close reading practice" onClick={onClose}>×</button></div>{navigation?.(phase==='permission'||phase==='listening')}<p className="g-practice-words" onClickCapture={()=>audio.current?.pause()}>{phase==='listening'||phase==='permission'?text:<ReadWords text={text} origin={origin}/>}</p>{modelNotice&&<p role="status" className="g-audio-notice">{modelNotice}</p>}
  <p className={phase==='listening'?'g-mic-live':'g-mic-off'} role="status">{phase==='listening'?'● Listening…':phase==='permission'?'Waiting for microphone permission…':phase==='review'?'Microphone off. You can listen to your recording or get feedback.':"Your microphone is off. Choose Start listening when you're ready to read."}</p>
  {phase==='ready'&&<p>Your recording is sent for feedback only when you choose Get feedback.</p>}
  <div className="g-row">{phase!=='listening'&&<button className="g-primary" disabled={phase==='permission'} onClick={()=>void start()}>{phase==='review'?'Start a new recording':'Start listening'}</button>}{!onTranscript&&phase!=='listening'&&phase!=='permission'&&<button className="g-secondary" onClick={()=>{audio.current?.pause();speak(text);}}>Hear this part</button>}</div>
  {url&&<><audio ref={audio} src={url} controls aria-label="Hear my reading" onPlay={()=>cancelLocalSpeech()} onError={()=>setNotice("This browser could not play the recording. You can read again or return to the story.")}/><div className="g-row"><button className="g-primary" disabled={busy} onClick={()=>void feedback()}>{onTranscript?'Get my words':'Get feedback'}</button><button className="g-secondary" onClick={()=>{attempt.current++;cancelFeedback();revoke();setPhase('ready');setNotice('');setTranscript(null);}}>Discard recording</button>{busy&&<button className="g-secondary" onClick={()=>{cancelFeedback();setNotice('Feedback stopped. Your recording is still here.');}}>Stop feedback</button>}</div></>}
  {transcript!==null&&<><label>Check your words<textarea value={transcript} onChange={e=>setTranscript(e.target.value)}/></label><button className="g-primary" onClick={()=>{onTranscript?.(transcript);onClose();}}>Use these words</button></>}
  {notice&&<p role="status">{notice}</p>}<p className="g-small">You can listen to this recording during practice. The game removes it when you leave or start a new recording.</p><details><summary>About reading feedback</summary><p>Live listening feedback is not available in this local demo. Recording and replay stay in this practice window. Nothing is saved to your adventure or sent automatically.</p></details><button className="g-secondary" onClick={onClose}>Back to the story</button>
 </section>;
}
