import {completeConversation} from './garden-play-actions.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {GardenStore,initialGarden,CROSSING,MARA,GRANDMA_APPROACH,type Point} from '../src/garden/model.js';
import {SOL_APPROACH,planProblems,type StoryEvent} from '../src/garden/chapter.js';
import {validChapter,unpack,checksum} from '../src/garden/persistence.js';
import {turnLines} from '../src/garden/gathering.js';
import {advance,finishBakery,finishArrivals,finishSpokenTurn,shareTornWing,tellGrandmaStory} from './garden-play-actions.js';
let serial=0;
const event=(s:GardenStore,event:StoryEvent)=>s.send({type:'STORY',event});
function close(s:GardenStore){for(let i=0;i<20&&s.getSnapshot().panel;i++)s.send({type:'CLOSE'});}
function go(s:GardenStore,point:Point){close(s);s.send({type:'GO',point});advance(s);assert.ok(Math.hypot(s.getSnapshot().chapter.pip.x-point.x,s.getSnapshot().chapter.pip.z-point.z)<.02);}
function ready(prepared=true){
 const s=new GardenStore(initialGarden('gather-'+serial++),()=>String(serial++));s.send({type:'BOOT'});s.send({type:'BEGIN'});s.send({type:'START_PLAY'});
 go(s,{x:MARA.x,z:MARA.z+.95});s.send({type:'TALK',who:'mara'});completeConversation(s);s.send({type:'TAKE_PAGE'});advance(s);event(s,{kind:'WATCH_DUTY'});advance(s);
 go(s,CROSSING);s.send({type:'COLLECT_ROPES'});advance(s);s.send({type:'ARRANGE'});for(const[section,x]of [['a',-.775],['b',.775]] as const){s.send({type:'SELECT',section});s.send({type:'PREVIEW',point:{x,z:3}});s.send({type:'PLACE'});}s.send({type:'JOIN'});s.send({type:'FASTEN',end:'west'});s.send({type:'FASTEN',end:'east'});s.send({type:'BACK'});
 go(s,GRANDMA_APPROACH);s.send({type:'PLANT'});advance(s);finishBakery(s);go(s,SOL_APPROACH);s.send({type:'TALK',who:'sol'});completeConversation(s);
 if(prepared){event(s,{kind:'FINISH_WITH_SOL'});event(s,{kind:'EDIT',text:'Rina brought me a loaf to thank me.'});event(s,{kind:'SELECT_ENDING',contribution:{text:s.getSnapshot().chapter.story.solDraft.text,scene:'thanks',origin:'child',revision:s.getSnapshot().chapter.story.solDraft.revision}});}else event(s,{kind:'BRING_DRAFT'});
 go(s,GRANDMA_APPROACH);event(s,{kind:'REPORT_MARA'});event(s,{kind:'REPORT_SOL'});event(s,{kind:'PLAN',time:'later',reader:'pip'});go(s,SOL_APPROACH);event(s,{kind:'INVITE',who:'sol'});go(s,{x:MARA.x,z:MARA.z+.95});event(s,{kind:'INVITE',who:'mara'});go(s,GRANDMA_APPROACH);
 assert.ok(planProblems(s.getSnapshot().chapter).some(x=>x.includes('report the agreed')));event(s,{kind:'REPORT_ARRANGEMENTS'});assert.deepEqual(planProblems(s.getSnapshot().chapter),[]);return s;
}
function boot(c:ReturnType<GardenStore['getSnapshot']>['chapter']){const s=new GardenStore(initialGarden('restore-'+serial++),()=>String(serial++));s.send({type:'BOOT',chapter:c});return s;}
test('Gathering arrival commits each physical stage once and never invents arrival on reload',()=>{
 const s=ready(),prior=structuredClone(s.getSnapshot().chapter);assert.equal(prior.mara.service,'served');event(s,{kind:'BEGIN_GATHERING'});assert.equal(s.getSnapshot().action?.kind,'finalBoat');s.send({type:'TICK',ms:80});s.send({type:'OPEN',panel:'help'});assert.equal(s.getSnapshot().chapter.gathering.arrival,'boat-moored');assert.equal(s.getSnapshot().chapter.story.phase,'arriving');close(s);
 const restored=boot(s.getSnapshot().chapter);advance(restored);assert.equal(restored.getSnapshot().chapter.gathering.arrival,'boat-moored');const waiting={...restored.getSnapshot().chapter.pip};restored.send({type:'GO',point:SOL_APPROACH});advance(restored);assert.deepEqual(restored.getSnapshot().chapter.pip,waiting);assert.equal(restored.getSnapshot().chapter.gathering.arrival,'boat-moored');event(restored,{kind:'CONTINUE_ARRIVAL'});assert.equal(restored.getSnapshot().action?.kind,'finalPassengers');
 const crashed=boot(restored.getSnapshot().chapter);assert.equal(crashed.getSnapshot().chapter.gathering.arrival,'boat-moored');event(crashed,{kind:'CONTINUE_ARRIVAL'});advance(crashed);assert.equal(crashed.getSnapshot().chapter.gathering.arrival,'passengers-ashore');assert.equal(crashed.getSnapshot().chapter.mara.service,'served');finishArrivals(crashed);assert.equal(crashed.getSnapshot().chapter.gathering.welcome,false);
 for(const key of ['seed','river','bakery','page'] as const)assert.deepEqual(crashed.getSnapshot().chapter[key],prior[key]);assert.ok(validChapter(crashed.getSnapshot().chapter));
});
test('Actual speaking turns preserve exact selected words and paragraph through source support and reload',()=>{
 const s=ready();event(s,{kind:'EDIT',text:'This working revision is not the ending selected for Sol.'});const chosen=structuredClone(s.getSnapshot().chapter.story.solEnding);event(s,{kind:'BEGIN_GATHERING'});finishArrivals(s);s.send({type:'OPEN',panel:'gathering'});assert.equal(s.getSnapshot().chapter.gathering.welcome,false);event(s,{kind:'NEXT_STORY'});assert.equal(s.getSnapshot().panel,null);assert.equal(s.getSnapshot().chapter.story.phase,'welcome');finishSpokenTurn(s);shareTornWing(s);event(s,{kind:'NEXT_STORY'});event(s,{kind:'NEXT_STORY'});event(s,{kind:'TURN_NEXT'});const c=s.getSnapshot().chapter;assert.equal(c.gathering.turn?.index,1);assert.equal(c.gathering.solPerformed,null);assert.ok(turnLines(c).some(line=>line.text===chosen!.text&&line.attribution?.includes('suggested ending')));
 const restored=boot(c);const current=structuredClone(restored.getSnapshot().chapter.gathering.turn);restored.send({type:'OPEN',panel:'help'});assert.deepEqual(restored.getSnapshot().chapter.gathering.turn,current);close(restored);restored.send({type:'GO',point:SOL_APPROACH});assert.deepEqual(restored.getSnapshot().chapter.pip,c.pip);finishSpokenTurn(restored);assert.deepEqual(restored.getSnapshot().chapter.gathering.solPerformed,chosen);assert.equal(restored.getSnapshot().chapter.gathering.solDisclosed,false);assert.equal(restored.getSnapshot().chapter.gathering.pageComplete,false);restored.send({type:'OPEN',panel:'empty'});assert.notEqual(restored.getSnapshot().panel,'empty');
 tellGrandmaStory(restored);assert.equal(restored.getSnapshot().chapter.gathering.grandmaPerformed,true);assert.ok(validChapter(restored.getSnapshot().chapter));
});
test('Draft discussion and Grandma’s knowledge require actual spoken turns; corrupt phase claims are rejected',()=>{
 const s=ready(false);event(s,{kind:'BEGIN_GATHERING'});finishArrivals(s);event(s,{kind:'NEXT_STORY'});finishSpokenTurn(s);shareTornWing(s);event(s,{kind:'NEXT_STORY'});event(s,{kind:'NEXT_STORY'});finishSpokenTurn(s);assert.equal(s.getSnapshot().chapter.story.phase,'discussion');event(s,{kind:'ASK_SOL',question:'thanks'});assert.deepEqual(s.getSnapshot().chapter.story.questions,[]);assert.match(turnLines(s.getSnapshot().chapter)[0]!.text,/tell everyone about Rina/);finishSpokenTurn(s);assert.deepEqual(s.getSnapshot().chapter.story.questions,['thanks']);event(s,{kind:'ADD_ENDING',scene:'thanks'});assert.equal(s.getSnapshot().chapter.story.solOutcome,null);finishSpokenTurn(s);assert.equal(s.getSnapshot().chapter.story.solOutcome,'developed');tellGrandmaStory(s);
 const damaged=structuredClone(s.getSnapshot().chapter);damaged.story.phase='grandma';assert.equal(validChapter(damaged),false);const raw={format:1,content:'garden-chapter-3',revision:1,writer:'explicit-synthetic-corruption',payload:damaged,checksum:checksum(JSON.stringify(damaged))};assert.equal(unpack(raw),null);
});

test('Changing the selected wording preserves compatible invitations and Grandma’s readiness report',()=>{
 const s=ready();const prior=structuredClone(s.getSnapshot().chapter.story);go(s,SOL_APPROACH);event(s,{kind:'EDIT',text:'My repair kept the flour dry, so Rina could bake.'});const draft=s.getSnapshot().chapter.story.solDraft;event(s,{kind:'SELECT_ENDING',contribution:{...draft,scene:'bread',origin:'child'}});assert.equal(s.getSnapshot().chapter.story.solReported,true);assert.equal(s.getSnapshot().chapter.story.solInvitation,prior.solInvitation);assert.deepEqual(s.getSnapshot().chapter.story.maraInvitation,prior.maraInvitation);assert.deepEqual(planProblems(s.getSnapshot().chapter),[]);
 event(s,{kind:'BRING_DRAFT'});assert.equal(s.getSnapshot().chapter.story.solReported,false);assert.equal(s.getSnapshot().chapter.story.solInvitation,prior.solInvitation);go(s,GRANDMA_APPROACH);event(s,{kind:'REPORT_SOL'});assert.deepEqual(planProblems(s.getSnapshot().chapter),[]);assert.ok(validChapter(s.getSnapshot().chapter));
});
